%% ================================================================
%  FINAL ARTICLE-PLANNING HISTORICAL DECOMPOSITION
%  SOE-BVAR
%
%  Uses final locked BVAR:
%
%       p = 2
%       lambda = 0.20
%       stable-only posterior
%       10,000 retained draws
%
%  Selected episodes:
%
%       GFC
%       Commodity-boom appreciation
%       Post-boom depreciation
%       COVID shock
%       COVID rebound
%       2022Q1-2026Q2
%       2025Q4-2026Q2
%
%  Components remain separate:
%
%       Global activity
%       Commodity prices
%       Global risk / VIX
%       Domestic macro
%       Relative yields
%       Other exchange-rate shocks
%
%% ================================================================

clear;
clc;
close all;


%% ================================================================
% 1. PATHS
%% ================================================================

folder = ...
    fileparts(mfilename('fullpath'));


addpath(fullfile(folder,'_func'));


resultDir = ...
    fullfile(folder,'results');


figDir = ...
    fullfile(folder,'figures');


if ~exist(figDir,'dir')
    mkdir(figDir);
end


dataFile = ...
    fullfile( ...
        folder, ...
        'data', ...
        'data_collected.xlsx');


BVARfile = ...
    fullfile( ...
        resultDir, ...
        'bvar_soe_baseline_lambda020_stable.mat');


assert(isfile(BVARfile));

assert( ...
    exist('historical_decomposition','file') == 2);


%% ================================================================
% 2. LOAD FINAL BVAR
%% ================================================================

S = ...
    load(BVARfile);


BVAR = ...
    S.BVAR;


clear S


y = ...
    BVAR.y;


[T,N] = ...
    size(y);


p = ...
    BVAR.p;


nDraws = ...
    size(BVAR.phi_draws,3);


assert(N == 7);

assert(p == 2);

assert(~isempty(BVAR.e_draws));


fprintf('\n');
fprintf('============================================================\n');
fprintf('FINAL BVAR HISTORICAL DECOMPOSITION\n');
fprintf('============================================================\n');

fprintf('Posterior draws: %d\n',nDraws);


%% ================================================================
% 3. SHOCK POSITIONS
%% ================================================================

shock_us = 1;

shock_comm = 2;

shock_vix = 3;

shock_augdp = 4;

shock_inf = 5;

shock_spread = 6;

shock_er = 7;


%% ================================================================
% 4. LOAD DATES
%% ================================================================

data = readtable( ...
    dataFile, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


if ~isdatetime(data.quarter_start)

    if isnumeric(data.quarter_start)

        data.quarter_start = ...
            datetime( ...
                data.quarter_start, ...
                'ConvertFrom','excel');

    else

        data.quarter_start = ...
            datetime(data.quarter_start);

    end

end


sample = ...
    data.quarter_start >= datetime(1995,1,1) ...
    & data.quarter_start <= datetime(2026,4,1);


D = ...
    data(sample,:);


assert(height(D) == T);


%% ================================================================
% 5. FINAL EPISODES
%% ================================================================

episodeNames = { ...
    'GFC', ...
    'Commodity-boom appreciation', ...
    'Post-boom depreciation', ...
    'COVID shock', ...
    'COVID rebound', ...
    '2022Q1-2026Q2', ...
    '2025Q4-2026Q2'};


plotLabels = { ...
    'GFC', ...
    'Commodity boom', ...
    'Post-boom', ...
    'COVID shock', ...
    'COVID rebound', ...
    '2022-26', ...
    'Late-2025-26'};


episodeStart = [ ...
    datetime(2008,7,1); ...
    datetime(2009,7,1); ...
    datetime(2013,1,1); ...
    datetime(2020,1,1); ...
    datetime(2020,4,1); ...
    datetime(2022,1,1); ...
    datetime(2025,10,1)];


episodeEnd = [ ...
    datetime(2009,4,1); ...
    datetime(2011,4,1); ...
    datetime(2015,7,1); ...
    datetime(2020,1,1); ...
    datetime(2021,4,1); ...
    datetime(2026,4,1); ...
    datetime(2026,4,1)];


nEpisodes = ...
    length(episodeNames);


%% ================================================================
% 6. EPISODE INDICES
%% ================================================================

episode_i0 = ...
    nan(nEpisodes,1);


episode_i1 = ...
    nan(nEpisodes,1);


ActualChange = ...
    nan(nEpisodes,1);


for ee = 1:nEpisodes

    episode_i0(ee) = ...
        find( ...
            D.quarter_start < episodeStart(ee), ...
            1, ...
            'last');


    episode_i1(ee) = ...
        find( ...
            D.quarter_start <= episodeEnd(ee), ...
            1, ...
            'last');


    assert( ...
        ~isempty(episode_i0(ee)) ...
        && ~isempty(episode_i1(ee)));


    ActualChange(ee) = ...
        y(episode_i1(ee),shock_er) ...
        - y(episode_i0(ee),shock_er);

end


%% ================================================================
% 7. COMPONENT NAMES
%% ================================================================

componentNames = { ...
    'Baseline dynamics', ...
    'Global activity', ...
    'Commodity prices', ...
    'Global risk (VIX)', ...
    'Domestic macro', ...
    'Relative yields', ...
    'Other exchange-rate shocks'};


nComponents = ...
    length(componentNames);


CI70 = ...
    [0.15 0.85];


CI95 = ...
    [0.025 0.975];


%% ================================================================
% PART A
% POSTERIOR-MEAN-MODEL POINT DECOMPOSITION
%% ================================================================

%% 8. POSTERIOR-MEAN PARAMETERS

phi_point = ...
    BVAR.phi_mean;


Sigma_point = ...
    BVAR.SIGMA_mean;


e_point = ...
    BVAR.e_mean;


[B_point,flag] = ...
    chol( ...
        Sigma_point, ...
        'lower');


assert(flag == 0);


%% ================================================================
% 9. HISTORICAL DECOMPOSITION
%% ================================================================

HD_point = ...
    historical_decomposition( ...
        phi_point, ...
        e_point, ...
        B_point);


HDrtwi_point = ...
    HD_point{shock_er};


baseline_point = ...
    constructVARBaseline( ...
        phi_point, ...
        y, ...
        p);


%% ================================================================
% 10. DISPLAY COMPONENTS
%% ================================================================

HD_grouped_point = [ ...
    HDrtwi_point(:,shock_us) ...
    HDrtwi_point(:,shock_comm) ...
    HDrtwi_point(:,shock_vix) ...
    HDrtwi_point(:,shock_augdp) ...
        + HDrtwi_point(:,shock_inf) ...
    HDrtwi_point(:,shock_spread) ...
    HDrtwi_point(:,shock_er)];


%% ================================================================
% 11. EPISODE POINT CONTRIBUTIONS
%% ================================================================

PointContrib = ...
    nan(nEpisodes,nComponents);


PointError = ...
    nan(nEpisodes,1);


for ee = 1:nEpisodes

    i0 = ...
        episode_i0(ee);


    i1 = ...
        episode_i1(ee);


    PointContrib(ee,1) = ...
        baseline_point(i1,shock_er) ...
        - baseline_point(i0,shock_er);


    PointContrib(ee,2:7) = ...
        HD_grouped_point(i1,:) ...
        - HD_grouped_point(i0,:);


    PointError(ee) = ...
        ActualChange(ee) ...
        - sum(PointContrib(ee,:));

end


assert( ...
    max(abs(PointError)) < 1e-8);


%% ================================================================
% PART B
% POSTERIOR UNCERTAINTY
%% ================================================================

%% 12. STORAGE

EpisodeDraws = ...
    nan( ...
        nEpisodes, ...
        nComponents, ...
        nDraws);


maxPosteriorAccountingError = ...
    0;


fprintf('\nCalculating posterior HDs...\n');


tic;


%% ================================================================
% 13. POSTERIOR LOOP
%% ================================================================

for ss = 1:nDraws

    phi_s = ...
        BVAR.phi_draws(:,:,ss);


    Sigma_s = ...
        BVAR.SIGMA_draws(:,:,ss);


    e_s = ...
        BVAR.e_draws(:,:,ss);


    [B_s,flag] = ...
        chol( ...
            Sigma_s, ...
            'lower');


    assert(flag == 0);


    %% HD

    HD_s = ...
        historical_decomposition( ...
            phi_s, ...
            e_s, ...
            B_s);


    HDrtwi_s = ...
        HD_s{shock_er};


    %% Baseline

    baseline_s = ...
        constructVARBaseline( ...
            phi_s, ...
            y, ...
            p);


    %% Components

    grouped_s = [ ...
        HDrtwi_s(:,shock_us) ...
        HDrtwi_s(:,shock_comm) ...
        HDrtwi_s(:,shock_vix) ...
        HDrtwi_s(:,shock_augdp) ...
            + HDrtwi_s(:,shock_inf) ...
        HDrtwi_s(:,shock_spread) ...
        HDrtwi_s(:,shock_er)];


    %% Accounting

    err_s = ...
        y(:,shock_er) ...
        - baseline_s(:,shock_er) ...
        - sum(HDrtwi_s,2);


    maxPosteriorAccountingError = ...
        max( ...
            maxPosteriorAccountingError, ...
            max(abs(err_s)));


    %% Episode contributions

    for ee = 1:nEpisodes

        i0 = ...
            episode_i0(ee);


        i1 = ...
            episode_i1(ee);


        EpisodeDraws(ee,1,ss) = ...
            baseline_s(i1,shock_er) ...
            - baseline_s(i0,shock_er);


        EpisodeDraws(ee,2:7,ss) = ...
            grouped_s(i1,:) ...
            - grouped_s(i0,:);

    end


    if mod(ss,1000) == 0

        fprintf( ...
            '  Draw %d of %d\n', ...
            ss,nDraws);

    end

end


fprintf( ...
    'Completed in %.1f seconds.\n', ...
    toc);


assert( ...
    maxPosteriorAccountingError < 1e-8);


%% ================================================================
% 14. POSTERIOR SUMMARIES
%% ================================================================

PosteriorMedian = ...
    nan(nEpisodes,nComponents);


Lower70 = ...
    nan(nEpisodes,nComponents);


Upper70 = ...
    nan(nEpisodes,nComponents);


Lower95 = ...
    nan(nEpisodes,nComponents);


Upper95 = ...
    nan(nEpisodes,nComponents);


for ee = 1:nEpisodes

    for cc = 1:nComponents

        vals = ...
            squeeze( ...
                EpisodeDraws(ee,cc,:));


        PosteriorMedian(ee,cc) = ...
            median(vals);


        q70 = ...
            quantile(vals,CI70);


        q95 = ...
            quantile(vals,CI95);


        Lower70(ee,cc) = ...
            q70(1);


        Upper70(ee,cc) = ...
            q70(2);


        Lower95(ee,cc) = ...
            q95(1);


        Upper95(ee,cc) = ...
            q95(2);

    end

end


%% ================================================================
% 15. POINT-DECOMPOSITION TABLE
%% ================================================================

BVAR_Point = table( ...
    string(episodeNames(:)), ...
    D.quarter_start(episode_i0), ...
    D.quarter_start(episode_i1), ...
    ActualChange, ...
    PointContrib(:,1), ...
    PointContrib(:,2), ...
    PointContrib(:,3), ...
    PointContrib(:,4), ...
    PointContrib(:,5), ...
    PointContrib(:,6), ...
    PointContrib(:,7), ...
    PointError, ...
    'VariableNames', ...
    { ...
    'Episode', ...
    'PreviousQuarter', ...
    'EndQuarter', ...
    'Observed_RTWI_Change', ...
    'Baseline_Dynamics', ...
    'Global_Activity', ...
    'Commodity_Prices', ...
    'VIX', ...
    'Domestic_Macro', ...
    'Relative_Yields', ...
    'Other_FX', ...
    'Accounting_Error'});


fprintf('\n');
fprintf('============================================================\n');
fprintf('BVAR POSTERIOR-MEAN-MODEL POINT DECOMPOSITION\n');
fprintf('============================================================\n');

disp(BVAR_Point);


%% ================================================================
% 16. LONG-FORM POSTERIOR TABLE
%% ================================================================

BVAR_Posterior = ...
    table();


for ee = 1:nEpisodes

    for cc = 1:nComponents

        newRow = table( ...
            string(episodeNames{ee}), ...
            string(componentNames{cc}), ...
            ActualChange(ee), ...
            PointContrib(ee,cc), ...
            PosteriorMedian(ee,cc), ...
            Lower70(ee,cc), ...
            Upper70(ee,cc), ...
            Lower95(ee,cc), ...
            Upper95(ee,cc), ...
            'VariableNames', ...
            { ...
            'Episode', ...
            'Component', ...
            'Observed_RTWI_Change', ...
            'PosteriorMeanModel_Point', ...
            'PosteriorMedian', ...
            'Lower70', ...
            'Upper70', ...
            'Lower95', ...
            'Upper95'});


        BVAR_Posterior = ...
            [BVAR_Posterior;newRow];

    end

end


%% ================================================================
% PART C
% FINAL STACKED FIGURE
%% ================================================================

componentColors = [ ...
    0.0000 0.4470 0.7410
    0.8500 0.3250 0.0980
    0.9290 0.6940 0.1250
    0.4940 0.1840 0.5560
    0.4660 0.6740 0.1880
    0.3010 0.7450 0.9330
    0.8000 0.0000 0.5000];


x = ...
    1:nEpisodes;


figure( ...
    'Color','w', ...
    'Position',[80 100 1400 650]);


b = bar( ...
    x, ...
    PointContrib, ...
    'stacked');


for cc = 1:nComponents

    b(cc).FaceColor = ...
        componentColors(cc,:);

end


hold on;


hActual = plot( ...
    x, ...
    ActualChange, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',8);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


xticks(x);

xticklabels(plotLabels);

xtickangle(18);


ylabel( ...
    'Contribution to RTWI change, log points');


title( ...
    'BVAR: What Drove Major Australian Dollar Episodes?');


grid on;
box off;


set( ...
    gca, ...
    'FontSize',11, ...
    'Layer','top');


legend( ...
    [b(:);hActual], ...
    [componentNames {'Observed change'}], ...
    'Location','eastoutside');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '43_bvar_hd_final_episodes.png'), ...
    'Resolution',300);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '43_bvar_hd_final_episodes.pdf'), ...
    'ContentType','vector');


%% ================================================================
% PART D
% INDIVIDUAL-SHOCK POSTERIOR UNCERTAINTY
%
% No aggregation of relative yields and other FX.
%
% Six panels:
%
% global activity
% commodity
% VIX
% domestic macro
% relative yields
% other FX
%% ================================================================

figure( ...
    'Color','w', ...
    'Position',[50 50 1450 850]);


tiledlayout( ...
    2,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');


shockPanels = ...
    2:7;


for jj = 1:length(shockPanels)

    cc = ...
        shockPanels(jj);


    nexttile;


    %% 95% interval

    errorbar( ...
        x, ...
        PosteriorMedian(:,cc), ...
        PosteriorMedian(:,cc) ...
            - Lower95(:,cc), ...
        Upper95(:,cc) ...
            - PosteriorMedian(:,cc), ...
        'k', ...
        'LineStyle','none', ...
        'LineWidth',1.0, ...
        'CapSize',7);


    hold on;


    %% 70% interval

    errorbar( ...
        x, ...
        PosteriorMedian(:,cc), ...
        PosteriorMedian(:,cc) ...
            - Lower70(:,cc), ...
        Upper70(:,cc) ...
            - PosteriorMedian(:,cc), ...
        'k', ...
        'LineStyle','none', ...
        'LineWidth',2.7, ...
        'CapSize',5);


    %% Posterior median

    plot( ...
        x, ...
        PosteriorMedian(:,cc), ...
        'ko', ...
        'MarkerFaceColor','k', ...
        'MarkerSize',6);


    yline( ...
        0, ...
        'k:', ...
        'HandleVisibility','off');


    xticks(x);

    xticklabels(plotLabels);

    xtickangle(25);


    ylabel( ...
        'Contribution, log points');


    title( ...
        componentNames{cc});


    grid on;
    box off;


    set( ...
        gca, ...
        'FontSize',9);

end


sgtitle( ...
    'BVAR Historical Contributions: Posterior Uncertainty');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '44_bvar_hd_final_uncertainty.png'), ...
    'Resolution',300);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '44_bvar_hd_final_uncertainty.pdf'), ...
    'ContentType','vector');


%% ================================================================
% 17. EXPORT EXCEL
%% ================================================================

outputFile = ...
    fullfile( ...
        resultDir, ...
        'bvar_hd_final_episodes.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    BVAR_Point, ...
    outputFile, ...
    'Sheet','point_HD');


writetable( ...
    BVAR_Posterior, ...
    outputFile, ...
    'Sheet','posterior_HD');


%% ================================================================
% 18. SAVE MATLAB RESULTS
%% ================================================================

bvar_hd_final = struct();


bvar_hd_final.episodeNames = ...
    episodeNames;


bvar_hd_final.episodeStart = ...
    episodeStart;


bvar_hd_final.episodeEnd = ...
    episodeEnd;


bvar_hd_final.ActualChange = ...
    ActualChange;


bvar_hd_final.PointContrib = ...
    PointContrib;


bvar_hd_final.PosteriorMedian = ...
    PosteriorMedian;


bvar_hd_final.Lower70 = ...
    Lower70;


bvar_hd_final.Upper70 = ...
    Upper70;


bvar_hd_final.Lower95 = ...
    Lower95;


bvar_hd_final.Upper95 = ...
    Upper95;


bvar_hd_final.componentNames = ...
    componentNames;


bvar_hd_final.PointTable = ...
    BVAR_Point;


bvar_hd_final.PosteriorTable = ...
    BVAR_Posterior;


bvar_hd_final.maxPosteriorAccountingError = ...
    maxPosteriorAccountingError;


save( ...
    fullfile( ...
        resultDir, ...
        'bvar_hd_final_episodes.mat'), ...
    'bvar_hd_final', ...
    '-v7.3');


fprintf('\n');
fprintf('============================================================\n');
fprintf('FINAL BVAR HD COMPLETE\n');
fprintf('============================================================\n');

fprintf( ...
    'Maximum point accounting error: %.3e\n', ...
    max(abs(PointError)));


fprintf( ...
    'Maximum posterior accounting error: %.3e\n', ...
    maxPosteriorAccountingError);


%% ================================================================
% LOCAL FUNCTION
%% ================================================================

function baseline = ...
    constructVARBaseline( ...
    phi, ...
    y, ...
    p)

% ================================================================
% No-shock VAR path:
%
%   intercept
%   initial conditions
%   all structural shocks set to zero
%
% Same mean-backcasting convention as the final BVAR work.
%% ================================================================

    [T,N] = ...
        size(y);


    initialMean = ...
        mean(y,1);


    baseline_ext = [ ...
        repmat(initialMean,p,1); ...
        zeros(T,N)];


    for t = 1:T

        thisValue = ...
            phi(1,:);


        for lag = 1:p

            rows = ...
                2 + (lag-1)*N : ...
                1 + lag*N;


            thisValue = ...
                thisValue ...
                + baseline_ext(p+t-lag,:) ...
                * phi(rows,:);

        end


        baseline_ext(p+t,:) = ...
            thisValue;

    end


    baseline = ...
        baseline_ext(p+1:end,:);

end