%% ================================================================
%  AUSTRALIAN DOLLAR DRIVERS
%  SOE-BVAR: POSTERIOR FEVD AND HISTORICAL DECOMPOSITION
%
%  Baseline BVAR:
%
%    Sample: 1995Q1-2026Q2
%    p = 2
%    lambda = 0.20
%    exact SOE block restriction
%    posterior conditioned on stability
%
%  Main outputs:
%
%    1. RTWI posterior FEVD
%       - posterior median
%       - 70% credible interval
%       - 95% credible interval
%       - optional classical SVAR comparison
%
%    2. Posterior-mean historical decomposition
%       - exact accounting identity
%       - full sample / post-2007
%       - selected historical episodes
%
%    3. Posterior uncertainty around episode contributions
%
%  IMPORTANT:
%
%  The stacked historical decomposition uses the posterior-mean
%  parameter model so that contributions sum exactly.
%
%  Posterior medians and credible intervals are reported separately
%  for episode contributions.
%% ================================================================

clear;
clc;
close all;


%% 1. PATHS

folder = fileparts(mfilename('fullpath'));

addpath(fullfile(folder,'_func'));


filePath = ...
    fullfile(folder,'data','data_collected.xlsx');


resultDir = ...
    fullfile(folder,'results');


figDir = ...
    fullfile(folder,'figures');


if ~exist(resultDir,'dir')
    mkdir(resultDir);
end


if ~exist(figDir,'dir')
    mkdir(figDir);
end


BVARfile = ...
    fullfile( ...
        resultDir, ...
        'bvar_soe_baseline_lambda020_stable.mat');


assert(isfile(BVARfile), ...
    'Final BVAR results file not found.');

assert(exist('calculate_IRF_FEVD','file') == 2, ...
    'calculate_IRF_FEVD.m not found.');

assert(exist('historical_decomposition','file') == 2, ...
    'historical_decomposition.m not found.');


%% 2. LOAD FINAL BVAR

S = load(BVARfile);

BVAR = ...
    S.BVAR;


if isfield(S,'Variables')

    Variables = ...
        S.Variables;

else

    Variables = { ...
        'US Real GDP gap', ...
        'Commodity prices', ...
        'VIX', ...
        'Australian Real GDP gap', ...
        'Trimmed mean inflation', ...
        'AU-US 2yr spread', ...
        'Real TWI'};

end


clear S


%% 3. IMPORT DATA
%
% Needed mainly for dates and article labels.
%
% The transformed BVAR data themselves are already stored in BVAR.y.

data = readtable( ...
    filePath, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


dateVars = { ...
    'quarter_start', ...
    'quarter_end'};


for ii = 1:length(dateVars)

    v = dateVars{ii};

    if ~isdatetime(data.(v))

        if isnumeric(data.(v))

            data.(v) = datetime( ...
                data.(v), ...
                'ConvertFrom','excel');

        else

            data.(v) = ...
                datetime(data.(v));

        end

    end

end


%% 4. SAMPLE

sampleStart = ...
    datetime(1995,1,1);

sampleEnd = ...
    datetime(2026,4,1);


sample = ...
    data.quarter_start >= sampleStart & ...
    data.quarter_start <= sampleEnd;


D = ...
    data(sample,:);


yr = ...
    year(D.quarter_start);


qtr = ...
    ceil(month(D.quarter_start)/3);


yearlab = ...
    yr + (qtr-1)/4;


quarterlab = ...
    string(yr) + "Q" + string(qtr);


%% 5. BVAR DATA / SETTINGS

y = ...
    BVAR.y;


[T,N] = ...
    size(y);


p = ...
    BVAR.p;


n_foreign = ...
    BVAR.n_foreign;


assert(T == height(D));
assert(N == 7);
assert(p == 2);
assert(n_foreign == 3);


%% 6. SHOCK POSITIONS

shock_us = 1;

shock_comm = 2;

shock_vix = 3;

shock_augdp = 4;

shock_inf = 5;

shock_spread = 6;

shock_er = 7;


%% 7. POSTERIOR SETTINGS

nDraws = ...
    size(BVAR.phi_draws,3);


assert( ...
    size(BVAR.SIGMA_draws,3) == nDraws);


assert( ...
    ~isempty(BVAR.e_draws), ...
    ['BVAR.e_draws is empty. Re-estimate final BVAR with ' ...
     'options.store_residuals = true.']);


assert( ...
    size(BVAR.e_draws,3) == nDraws);


fprintf('\n============================================================\n');
fprintf('BVAR POSTERIOR FEVD + HISTORICAL DECOMPOSITION\n');
fprintf('============================================================\n');

fprintf('Posterior draws: %d\n',nDraws);

fprintf('Sample: %s to %s\n', ...
    char(quarterlab(1)), ...
    char(quarterlab(end)));

fprintf('Posterior median root: %.4f\n', ...
    median(BVAR.root_draws));

fprintf('Maximum retained root: %.4f\n', ...
    max(BVAR.root_draws));


%% 8. CREDIBLE INTERVALS

CI70 = ...
    [0.15 0.85];


CI95 = ...
    [0.025 0.975];


%% ================================================================
% PART A
% POSTERIOR FEVD
%% ================================================================

%% 9. FEVD SETTINGS

horFEVD = 20;


selectedHorizons = ...
    [1 4 8 12 20];


% Store RTWI FEVD:
%
% shock x horizon x posterior draw

FEVD_rtwi_draws = ...
    nan( ...
        N, ...
        horFEVD, ...
        nDraws);


fprintf('\nCalculating posterior FEVDs...\n');


%% 10. CALCULATE FEVD FOR EVERY POSTERIOR DRAW

tic;


for ss = 1:nDraws

    phi_s = ...
        BVAR.phi_draws(:,:,ss);


    Sigma_s = ...
        BVAR.SIGMA_draws(:,:,ss);


    [B_s,flag] = ...
        chol( ...
            Sigma_s, ...
            'lower');


    assert(flag == 0, ...
        'Sigma draw %d is not positive definite.',ss);


    [~,FEVD_s] = ...
        calculate_IRF_FEVD( ...
            phi_s, ...
            B_s, ...
            horFEVD, ...
            'FEVD');


    rtwiFEVD_s = ...
        squeeze( ...
            FEVD_s( ...
                shock_er, ...
                :, ...
                :));


    % Previous classical scripts use columns 1:H
    % for forecast horizons 1:H.

    FEVD_rtwi_draws(:,:,ss) = ...
        rtwiFEVD_s(:,1:horFEVD);


    if mod(ss,1000) == 0

        fprintf('  FEVD draw %d of %d\n', ...
            ss,nDraws);

    end

end


fprintf('FEVD posterior calculation: %.1f seconds\n',toc);


%% 11. POSTERIOR FEVD SUMMARIES

FEVD_median = ...
    median( ...
        FEVD_rtwi_draws, ...
        3);


FEVD_mean = ...
    mean( ...
        FEVD_rtwi_draws, ...
        3);


FEVD_CI70 = ...
    quantile( ...
        FEVD_rtwi_draws, ...
        CI70, ...
        3);


FEVD_CI95 = ...
    quantile( ...
        FEVD_rtwi_draws, ...
        CI95, ...
        3);


%% 12. GROUPED FEVD DRAWS
%
% Because structural shocks are orthogonal, FEVD shares can be
% summed within the groups.

FEVD_commRisk_draws = ...
    FEVD_rtwi_draws(shock_comm,:,:) ...
    + FEVD_rtwi_draws(shock_vix,:,:);


FEVD_yieldFX_draws = ...
    FEVD_rtwi_draws(shock_spread,:,:) ...
    + FEVD_rtwi_draws(shock_er,:,:);


FEVD_commRisk_median = ...
    squeeze( ...
        median( ...
            FEVD_commRisk_draws, ...
            3));


FEVD_yieldFX_median = ...
    squeeze( ...
        median( ...
            FEVD_yieldFX_draws, ...
            3));


FEVD_commRisk_CI70 = ...
    squeeze( ...
        quantile( ...
            FEVD_commRisk_draws, ...
            CI70, ...
            3));


FEVD_commRisk_CI95 = ...
    squeeze( ...
        quantile( ...
            FEVD_commRisk_draws, ...
            CI95, ...
            3));


FEVD_yieldFX_CI70 = ...
    squeeze( ...
        quantile( ...
            FEVD_yieldFX_draws, ...
            CI70, ...
            3));


FEVD_yieldFX_CI95 = ...
    squeeze( ...
        quantile( ...
            FEVD_yieldFX_draws, ...
            CI95, ...
            3));


%% 13. OPTIONAL CLASSICAL SVAR COMPARATOR

classicalFile = ...
    fullfile( ...
        resultDir, ...
        'classical_svar2_baseline_locked.mat');


haveClassical = ...
    isfile(classicalFile);


if haveClassical

    C = ...
        load(classicalFile);


    phi_classical = ...
        C.classical_baseline.results.phi;


    B_classical = ...
        C.classical_baseline.results.B;


    [~,FEVD_classical_full] = ...
        calculate_IRF_FEVD( ...
            phi_classical, ...
            B_classical, ...
            horFEVD, ...
            'FEVD');


    FEVD_classical = ...
        squeeze( ...
            FEVD_classical_full( ...
                shock_er, ...
                :, ...
                1:horFEVD));


    clear C

else

    FEVD_classical = [];

end


%% 14. ARTICLE FEVD FIGURE

h = ...
    (1:horFEVD)';


plotShockIdx = [ ...
    shock_comm ...
    shock_vix ...
    shock_spread ...
    shock_er];


plotTitles = { ...
    'Commodity-price shocks', ...
    'Global-risk / VIX shocks', ...
    'Relative-yield shocks', ...
    'Other exchange-rate shocks'};


figure( ...
    'Color','w', ...
    'Position',[100 70 1100 760]);


t = tiledlayout( ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


for pp = 1:length(plotShockIdx)

    shock = ...
        plotShockIdx(pp);


    point = ...
        FEVD_median(shock,:)';


    ci70 = ...
        squeeze( ...
            FEVD_CI70( ...
                shock, ...
                :, ...
                :));


    ci95 = ...
        squeeze( ...
            FEVD_CI95( ...
                shock, ...
                :, ...
                :));


    nexttile;


    [h95,h70,hMedian] = ...
        plotCredibleBands( ...
            h, ...
            point, ...
            ci70, ...
            ci95);


    if haveClassical

        hClassical = plot( ...
            h, ...
            FEVD_classical(shock,:)', ...
            '--k', ...
            'LineWidth',1.3);

    end


    title(plotTitles{pp});

    xlabel('Forecast horizon');

    ylabel('Share of RTWI variance (%)');

    xlim([1 horFEVD]);


    if pp == 1

        if haveClassical

            legend( ...
                [hMedian h70 h95 hClassical], ...
                { ...
                'BVAR posterior median', ...
                '70% credible interval', ...
                '95% credible interval', ...
                'Classical SVAR(2)'}, ...
                'Location','best', ...
                'FontSize',8);

        else

            legend( ...
                [hMedian h70 h95], ...
                { ...
                'BVAR posterior median', ...
                '70% credible interval', ...
                '95% credible interval'}, ...
                'Location','best', ...
                'FontSize',8);

        end

    end

end


%sgtitle(t, ...
%    'What Explains Forecast Errors in the Australian Dollar?');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '29_bvar_rtwi_fevd_articlefig.png'), ...
    'Resolution',300);

print( ...
    gcf, ...
    fullfile(figDir,'figure2_fevd_article.svg'), ...
    '-dsvg');

%% 15. GROUPED FEVD FIGURE

figure( ...
    'Color','w', ...
    'Position',[100 100 1050 430]);


tiledlayout( ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% Commodity + risk

nexttile;


plotCredibleBands( ...
    h, ...
    FEVD_commRisk_median(:), ...
    FEVD_commRisk_CI70, ...
    FEVD_commRisk_CI95);


title('Commodity + global-risk shocks');

xlabel('Forecast horizon');

ylabel('Share of RTWI variance (%)');

xlim([1 horFEVD]);


%% Yield + other FX

nexttile;


plotCredibleBands( ...
    h, ...
    FEVD_yieldFX_median(:), ...
    FEVD_yieldFX_CI70, ...
    FEVD_yieldFX_CI95);


title('Relative-yield + other exchange-rate shocks');

xlabel('Forecast horizon');

ylabel('Share of RTWI variance (%)');

xlim([1 horFEVD]);


sgtitle( ...
    'Broader Channels Behind Australian-Dollar Forecast Errors');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '30_bvar_rtwi_fevd_grouped.png'), ...
    'Resolution',300);


%% 16. FEVD SELECTED-HORIZON TABLE

FEVD_Table = table();


shockNames = { ...
    'Commodity prices', ...
    'VIX', ...
    'Relative yields', ...
    'Other exchange-rate shocks'};


for pp = 1:length(plotShockIdx)

    shock = ...
        plotShockIdx(pp);


    for hh = selectedHorizons

        med = ...
            FEVD_median(shock,hh);


        ci70 = ...
            squeeze( ...
                FEVD_CI70( ...
                    shock, ...
                    hh, ...
                    :));


        ci95 = ...
            squeeze( ...
                FEVD_CI95( ...
                    shock, ...
                    hh, ...
                    :));


        if haveClassical

            classicalValue = ...
                FEVD_classical(shock,hh);

        else

            classicalValue = ...
                NaN;

        end


        newRow = table( ...
            string(shockNames{pp}), ...
            hh, ...
            med, ...
            ci70(1), ...
            ci70(2), ...
            ci95(1), ...
            ci95(2), ...
            classicalValue, ...
            'VariableNames', ...
            { ...
            'Shock', ...
            'Horizon', ...
            'BVAR_Median', ...
            'Lower70', ...
            'Upper70', ...
            'Lower95', ...
            'Upper95', ...
            'Classical_SVAR'});


        FEVD_Table = ...
            [FEVD_Table;newRow];

    end

end


fprintf('\n============================================================\n');
fprintf('BVAR RTWI FEVD - SELECTED HORIZONS\n');
fprintf('============================================================\n');

disp(FEVD_Table);


%% ================================================================
% PART B
% POSTERIOR-MEAN HISTORICAL DECOMPOSITION
%% ================================================================

%% 17. POSTERIOR-MEAN PARAMETER MODEL

phi_point = ...
    BVAR.phi_mean;


Sigma_point = ...
    BVAR.SIGMA_mean;


e_point = ...
    BVAR.e_mean;


[B_point,flag] = ...
    chol( ...
        Sigma_point, ...
        'lower');


assert(flag == 0);


%% 18. HISTORICAL DECOMPOSITION - POINT MODEL

HD_point = ...
    historical_decomposition( ...
        phi_point, ...
        e_point, ...
        B_point);


baseline_point = ...
    constructVARBaseline( ...
        phi_point, ...
        y, ...
        p);


HDrtwi_point = ...
    HD_point{shock_er};


%% 19. ARTICLE GROUPS

HD_global_point = ...
    HDrtwi_point(:,shock_us);


HD_comm_point = ...
    HDrtwi_point(:,shock_comm);


HD_vix_point = ...
    HDrtwi_point(:,shock_vix);


HD_domestic_point = ...
    HDrtwi_point(:,shock_augdp) ...
    + HDrtwi_point(:,shock_inf);


HD_spread_point = ...
    HDrtwi_point(:,shock_spread);


HD_fx_point = ...
    HDrtwi_point(:,shock_er);


HD_grouped_point = [ ...
    HD_global_point ...
    HD_comm_point ...
    HD_vix_point ...
    HD_domestic_point ...
    HD_spread_point ...
    HD_fx_point];


HD_groupLabels = { ...
    'Global activity', ...
    'Commodity prices', ...
    'Global risk (VIX)', ...
    'Domestic macro', ...
    'Relative yields', ...
    'Other exchange-rate shocks'};


rtwi_baseline_point = ...
    baseline_point(:,shock_er);


rtwi_actual = ...
    y(:,shock_er);


rtwi_totalShock_point = ...
    sum( ...
        HDrtwi_point, ...
        2);


%% 20. EXACT POINT-MODEL ACCOUNTING CHECK

pointAccountingError = ...
    rtwi_actual ...
    - rtwi_baseline_point ...
    - rtwi_totalShock_point;


fprintf('\nMaximum posterior-mean HD accounting error: %.3e\n', ...
    max(abs(pointAccountingError)));


assert( ...
    max(abs(pointAccountingError)) < 1e-8);


%% 21. POST-2007 HISTORICAL DECOMPOSITION FIGURE

focus = ...
    D.quarter_start >= datetime(2007,1,1);


figure( ...
    'Color','w', ...
    'Position',[70 100 1400 650]);


b = bar( ...
    yearlab(focus), ...
    HD_grouped_point(focus,:), ...
    'stacked', ...
    'BarWidth',1);


hold on;


hTotal = plot( ...
    yearlab(focus), ...
    rtwi_totalShock_point(focus), ...
    '-k', ...
    'LineWidth',2);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xlabel('Year');

ylabel('Contribution to Real TWI, log points');


title( ...
    'BVAR: Drivers of the Australian Dollar Since 2007');


legend( ...
    [b(:);hTotal], ...
    [HD_groupLabels {'Actual minus baseline'}], ...
    'Location','eastoutside');


xlim([ ...
    yearlab(find(focus,1,'first')) ...
    yearlab(end)]);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '31_bvar_hd_rtwi_since_2007.png'), ...
    'Resolution',300);


%% ================================================================
% PART C
% POSTERIOR UNCERTAINTY FOR HISTORICAL EPISODES
%% ================================================================

%% 22. HISTORICAL EPISODES

episodeNames = { ...
    'GFC', ...
    'Commodity-boom appreciation', ...
    'Post-boom depreciation', ...
    'COVID shock', ...
    'COVID rebound', ...
    'Recent period'};


episodeStart = [ ...
    datetime(2008,7,1); ...
    datetime(2009,7,1); ...
    datetime(2013,1,1); ...
    datetime(2020,1,1); ...
    datetime(2020,4,1); ...
    datetime(2022,1,1)];


episodeEnd = [ ...
    datetime(2009,4,1); ...
    datetime(2011,4,1); ...
    datetime(2015,7,1); ...
    datetime(2020,1,1); ...
    datetime(2021,4,1); ...
    datetime(2026,4,1)];


nEpisodes = ...
    length(episodeNames);


%% 23. EPISODE INDICES

episode_i0 = ...
    nan(nEpisodes,1);


episode_i1 = ...
    nan(nEpisodes,1);


episodeActualChange = ...
    nan(nEpisodes,1);


for ee = 1:nEpisodes

    episode_i0(ee) = ...
        find( ...
            D.quarter_start < episodeStart(ee), ...
            1, ...
            'last');


    episode_i1(ee) = ...
        find( ...
            D.quarter_start <= episodeEnd(ee), ...
            1, ...
            'last');


    episodeActualChange(ee) = ...
        rtwi_actual(episode_i1(ee)) ...
        - rtwi_actual(episode_i0(ee));

end


%% 24. POINT-MODEL EPISODE CONTRIBUTIONS
%
% Columns:
%
% 1 baseline
% 2 global activity
% 3 commodity
% 4 VIX
% 5 domestic macro
% 6 spread
% 7 other FX

nBasicComponents = ...
    7;


Episode_point = ...
    nan(nEpisodes,nBasicComponents);


for ee = 1:nEpisodes

    i0 = ...
        episode_i0(ee);


    i1 = ...
        episode_i1(ee);


    Episode_point(ee,1) = ...
        rtwi_baseline_point(i1) ...
        - rtwi_baseline_point(i0);


    Episode_point(ee,2:7) = ...
        HD_grouped_point(i1,:) ...
        - HD_grouped_point(i0,:);

end


pointEpisodeError = ...
    episodeActualChange ...
    - sum(Episode_point,2);


assert( ...
    max(abs(pointEpisodeError)) < 1e-8);


%% 25. POSTERIOR EPISODE STORAGE

Episode_draws = ...
    nan( ...
        nEpisodes, ...
        nBasicComponents, ...
        nDraws);


maxPosteriorAccountingError = ...
    0;


fprintf('\nCalculating posterior historical decompositions...\n');


tic;


%% 26. HD FOR EVERY POSTERIOR DRAW

for ss = 1:nDraws

    phi_s = ...
        BVAR.phi_draws(:,:,ss);


    Sigma_s = ...
        BVAR.SIGMA_draws(:,:,ss);


    e_s = ...
        BVAR.e_draws(:,:,ss);


    [B_s,flag] = ...
        chol( ...
            Sigma_s, ...
            'lower');


    assert(flag == 0);


    HD_s = ...
        historical_decomposition( ...
            phi_s, ...
            e_s, ...
            B_s);


    baseline_s = ...
        constructVARBaseline( ...
            phi_s, ...
            y, ...
            p);


    HDrtwi_s = ...
        HD_s{shock_er};


    grouped_s = [ ...
        HDrtwi_s(:,shock_us) ...
        HDrtwi_s(:,shock_comm) ...
        HDrtwi_s(:,shock_vix) ...
        HDrtwi_s(:,shock_augdp) ...
            + HDrtwi_s(:,shock_inf) ...
        HDrtwi_s(:,shock_spread) ...
        HDrtwi_s(:,shock_er)];


    %% Exact full-sample accounting diagnostic

    err_s = ...
        rtwi_actual ...
        - baseline_s(:,shock_er) ...
        - sum(HDrtwi_s,2);


    maxPosteriorAccountingError = ...
        max( ...
            maxPosteriorAccountingError, ...
            max(abs(err_s)));


    %% Episodes

    for ee = 1:nEpisodes

        i0 = ...
            episode_i0(ee);


        i1 = ...
            episode_i1(ee);


        Episode_draws(ee,1,ss) = ...
            baseline_s(i1,shock_er) ...
            - baseline_s(i0,shock_er);


        Episode_draws(ee,2:7,ss) = ...
            grouped_s(i1,:) ...
            - grouped_s(i0,:);

    end


    if mod(ss,1000) == 0

        fprintf('  HD draw %d of %d\n', ...
            ss,nDraws);

    end

end


fprintf('Posterior HD calculation: %.1f seconds\n',toc);


fprintf('Maximum posterior HD accounting error: %.3e\n', ...
    maxPosteriorAccountingError);


assert( ...
    maxPosteriorAccountingError < 1e-8);


%% 27. EPISODE POSTERIOR SUMMARIES

Episode_median = ...
    median( ...
        Episode_draws, ...
        3);


Episode_CI70 = ...
    quantile( ...
        Episode_draws, ...
        CI70, ...
        3);


Episode_CI95 = ...
    quantile( ...
        Episode_draws, ...
        CI95, ...
        3);


%% 28. GROUPED EPISODE POSTERIOR DRAWS

Episode_commRisk_draws = ...
    Episode_draws(:,3,:) ...
    + Episode_draws(:,4,:);


Episode_yieldFX_draws = ...
    Episode_draws(:,6,:) ...
    + Episode_draws(:,7,:);


Episode_commRisk_median = ...
    squeeze( ...
        median( ...
            Episode_commRisk_draws, ...
            3));


Episode_yieldFX_median = ...
    squeeze( ...
        median( ...
            Episode_yieldFX_draws, ...
            3));


Episode_commRisk_CI70 = ...
    squeeze( ...
        quantile( ...
            Episode_commRisk_draws, ...
            CI70, ...
            3));


Episode_commRisk_CI95 = ...
    squeeze( ...
        quantile( ...
            Episode_commRisk_draws, ...
            CI95, ...
            3));


Episode_yieldFX_CI70 = ...
    squeeze( ...
        quantile( ...
            Episode_yieldFX_draws, ...
            CI70, ...
            3));


Episode_yieldFX_CI95 = ...
    squeeze( ...
        quantile( ...
            Episode_yieldFX_draws, ...
            CI95, ...
            3));


%% 29. ARTICLE EPISODE CHART - POINT MODEL

componentLabels = { ...
    'Baseline dynamics', ...
    'Global activity', ...
    'Commodity prices', ...
    'Global risk (VIX)', ...
    'Domestic macro', ...
    'Relative yields', ...
    'Other exchange-rate shocks'};


x = ...
    1:nEpisodes;


%% ---------------------------------------------------------------
% Create figure FIRST
%% ---------------------------------------------------------------

figure( ...
    'Color','w', ...
    'Position',[90 80 1300 700]);


%% ---------------------------------------------------------------
% Stacked historical decomposition
%% ---------------------------------------------------------------

b = bar( ...
    x, ...
    Episode_point, ...
    'stacked');


hold on;


hActual = plot( ...
    x, ...
    episodeActualChange, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',7);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xlim([0.5 nEpisodes+0.5]);


ylabel( ...
    'Contribution to RTWI change, log points');


% No title for article figure
%
% title( ...
%     'BVAR: What Drove Major Australian Dollar Episodes?');


set( ...
    gca, ...
    'FontSize',11, ...
    'TickLabelInterpreter','none', ...
    'Layer','top');


%% ---------------------------------------------------------------
% Article-style horizontal episode labels
%% ---------------------------------------------------------------

ax = gca;


% Keep tick positions but remove MATLAB's default labels

xticks(x);

xticklabels( ...
    repmat({''},1,nEpisodes));


% Get final y-limits AFTER the bars have been drawn

yl = ylim;


% Put labels just below the plotting area

labelY = ...
    yl(1) - 0.035*(yl(2)-yl(1));


% Single-line labels

text( ...
    x(1), ...
    labelY, ...
    'GFC', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',11, ...
    'Clipping','off');


text( ...
    x(6), ...
    labelY, ...
    'Recent period', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',11, ...
    'Clipping','off');


% Two-line labels

text( ...
    x(2), ...
    labelY, ...
    {'Commodity boom','appreciation'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',11, ...
    'Clipping','off');


text( ...
    x(3), ...
    labelY, ...
    {'Post boom','depreciation'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',11, ...
    'Clipping','off');


text( ...
    x(4), ...
    labelY, ...
    {'COVID','shock'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',11, ...
    'Clipping','off');


text( ...
    x(5), ...
    labelY, ...
    {'COVID','rebound'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',11, ...
    'Clipping','off');


%% ---------------------------------------------------------------
% Give the custom labels some extra room below the axes
%% ---------------------------------------------------------------

ax.Position = [ ...
    ax.Position(1), ...
    ax.Position(2) + 0.055, ...
    ax.Position(3), ...
    ax.Position(4) - 0.055];


%% ---------------------------------------------------------------
% Legend
%% ---------------------------------------------------------------

legend( ...
    [b(:);hActual], ...
    [componentLabels {'Observed change'}], ...
    'Location','eastoutside');


%% ---------------------------------------------------------------
% Export
%% ---------------------------------------------------------------

exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '32_bvar_hd_selected_episodes_articlefig.png'), ...
    'Resolution',300);

% High-quality vector version for Canva
print( ...
    gcf, ...
    fullfile(figDir,'figure3_hd_article.svg'), ...
    '-dsvg');

%% 30. POSTERIOR EPISODE TABLE - INDIVIDUAL COMPONENTS

EpisodePosteriorTable = table();


for ee = 1:nEpisodes

    for cc = 1:nBasicComponents

        ci70 = ...
            squeeze( ...
                Episode_CI70( ...
                    ee, ...
                    cc, ...
                    :));


        ci95 = ...
            squeeze( ...
                Episode_CI95( ...
                    ee, ...
                    cc, ...
                    :));


        newRow = table( ...
            string(episodeNames{ee}), ...
            string(componentLabels{cc}), ...
            episodeActualChange(ee), ...
            Episode_point(ee,cc), ...
            Episode_median(ee,cc), ...
            ci70(1), ...
            ci70(2), ...
            ci95(1), ...
            ci95(2), ...
            'VariableNames', ...
            { ...
            'Episode', ...
            'Component', ...
            'ObservedChange', ...
            'PosteriorMeanModelPoint', ...
            'PosteriorMedian', ...
            'Lower70', ...
            'Upper70', ...
            'Lower95', ...
            'Upper95'});


        EpisodePosteriorTable = ...
            [EpisodePosteriorTable;newRow];

    end

end


%% 31. GROUPED-CHANNEL EPISODE TABLE

EpisodeGroupedTable = table();


for ee = 1:nEpisodes

    %% Commodity + risk

    ci70 = ...
        Episode_commRisk_CI70(ee,:);


    ci95 = ...
        Episode_commRisk_CI95(ee,:);


    pointValue = ...
        Episode_point(ee,3) ...
        + Episode_point(ee,4);


    row1 = table( ...
        string(episodeNames{ee}), ...
        "Commodity + global risk", ...
        episodeActualChange(ee), ...
        pointValue, ...
        Episode_commRisk_median(ee), ...
        ci70(1), ...
        ci70(2), ...
        ci95(1), ...
        ci95(2), ...
        'VariableNames', ...
        { ...
        'Episode', ...
        'Channel', ...
        'ObservedChange', ...
        'PosteriorMeanModelPoint', ...
        'PosteriorMedian', ...
        'Lower70', ...
        'Upper70', ...
        'Lower95', ...
        'Upper95'});


    %% Yield + FX

    ci70 = ...
        Episode_yieldFX_CI70(ee,:);


    ci95 = ...
        Episode_yieldFX_CI95(ee,:);


    pointValue = ...
        Episode_point(ee,6) ...
        + Episode_point(ee,7);


    row2 = table( ...
        string(episodeNames{ee}), ...
        "Relative yield + other FX", ...
        episodeActualChange(ee), ...
        pointValue, ...
        Episode_yieldFX_median(ee), ...
        ci70(1), ...
        ci70(2), ...
        ci95(1), ...
        ci95(2), ...
        'VariableNames', ...
        { ...
        'Episode', ...
        'Channel', ...
        'ObservedChange', ...
        'PosteriorMeanModelPoint', ...
        'PosteriorMedian', ...
        'Lower70', ...
        'Upper70', ...
        'Lower95', ...
        'Upper95'});


    EpisodeGroupedTable = ...
        [EpisodeGroupedTable;row1;row2];

end


fprintf('\n============================================================\n');
fprintf('BVAR GROUPED HISTORICAL EPISODE CONTRIBUTIONS\n');
fprintf('============================================================\n');

disp(EpisodeGroupedTable);


%% 32. GROUPED EPISODE UNCERTAINTY FIGURE
%
% Posterior median with 70% intervals.
%
% 95% intervals remain in the output table.

figure( ...
    'Color','w', ...
    'Position',[100 100 1100 700]);


tiledlayout( ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% Commodity + risk

nexttile;


errorbar( ...
    x, ...
    Episode_commRisk_median, ...
    Episode_commRisk_median ...
        - Episode_commRisk_CI70(:,1), ...
    Episode_commRisk_CI70(:,2) ...
        - Episode_commRisk_median, ...
    'ok', ...
    'MarkerFaceColor','k', ...
    'LineWidth',1.4);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(x);

xticklabels(episodeNames);

xtickangle(15);


ylabel('Contribution, log points');

title('Commodity + global-risk channel');


%% Yield + FX

nexttile;


errorbar( ...
    x, ...
    Episode_yieldFX_median, ...
    Episode_yieldFX_median ...
        - Episode_yieldFX_CI70(:,1), ...
    Episode_yieldFX_CI70(:,2) ...
        - Episode_yieldFX_median, ...
    'ok', ...
    'MarkerFaceColor','k', ...
    'LineWidth',1.4);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(x);

xticklabels(episodeNames);

xtickangle(15);


ylabel('Contribution, log points');

title('Relative-yield + other exchange-rate channel');


sgtitle( ...
    'BVAR Historical Contributions with 70% Credible Intervals');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '33_bvar_hd_episode_uncertainty.png'), ...
    'Resolution',300);


%% ================================================================
% PART D
% EXPORT
%% ================================================================

%% 33. DIAGNOSTIC SUMMARY

BVAR_Diagnostics = table( ...
    BVAR.root_mean_phi, ...
    BVAR.root_median_phi, ...
    median(BVAR.root_draws), ...
    quantile(BVAR.root_draws,0.95), ...
    quantile(BVAR.root_draws,0.99), ...
    max(BVAR.root_draws), ...
    100*BVAR.info.stability_rejection_rate, ...
    BVAR.info.maxForbiddenCoefficient, ...
    maxPosteriorAccountingError, ...
    'VariableNames', ...
    { ...
    'PosteriorMeanRoot', ...
    'PosteriorMedianRoot', ...
    'MedianDrawRoot', ...
    'P95DrawRoot', ...
    'P99DrawRoot', ...
    'MaximumDrawRoot', ...
    'StabilityRejectionPercent', ...
    'MaximumForbiddenCoefficient', ...
    'MaximumHDAccountingError'});


%% 34. WRITE EXCEL RESULTS

outputFile = ...
    fullfile( ...
        resultDir, ...
        'bvar_fevd_hd_results.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    FEVD_Table, ...
    outputFile, ...
    'Sheet','FEVD');


writetable( ...
    EpisodePosteriorTable, ...
    outputFile, ...
    'Sheet','HD_episodes');


writetable( ...
    EpisodeGroupedTable, ...
    outputFile, ...
    'Sheet','HD_grouped');


writetable( ...
    BVAR_Diagnostics, ...
    outputFile, ...
    'Sheet','diagnostics');


%% 35. SAVE MATLAB RESULTS

bvar_article = struct();


bvar_article.FEVD_rtwi_draws = ...
    FEVD_rtwi_draws;


bvar_article.FEVD_median = ...
    FEVD_median;


bvar_article.FEVD_CI70 = ...
    FEVD_CI70;


bvar_article.FEVD_CI95 = ...
    FEVD_CI95;


bvar_article.FEVD_commRisk_draws = ...
    FEVD_commRisk_draws;


bvar_article.FEVD_yieldFX_draws = ...
    FEVD_yieldFX_draws;


bvar_article.HD_grouped_point = ...
    HD_grouped_point;


bvar_article.baseline_point = ...
    baseline_point;


bvar_article.Episode_point = ...
    Episode_point;


bvar_article.Episode_draws = ...
    Episode_draws;


bvar_article.EpisodePosteriorTable = ...
    EpisodePosteriorTable;


bvar_article.EpisodeGroupedTable = ...
    EpisodeGroupedTable;


bvar_article.BVAR_Diagnostics = ...
    BVAR_Diagnostics;


save( ...
    fullfile( ...
        resultDir, ...
        'bvar_fevd_hd_results.mat'), ...
    'bvar_article', ...
    '-v7.3');


fprintf('\n============================================================\n');
fprintf('BVAR FEVD + HISTORICAL DECOMPOSITION COMPLETE\n');
fprintf('============================================================\n');

fprintf('Maximum HD accounting error: %.3e\n', ...
    maxPosteriorAccountingError);

fprintf('\nResults workbook:\n%s\n', ...
    outputFile);


%% ================================================================
% LOCAL FUNCTIONS
%% ================================================================

function baseline = ...
    constructVARBaseline( ...
    phi, ...
    y, ...
    p)

% ================================================================
% No-shock VAR path generated by:
%
%   - intercept
%   - initial conditions
%
% Uses the SAME mean-backcasting convention as olsvar and bvar_soe.
%% ================================================================


    [T,N] = ...
        size(y);


    initialMean = ...
        mean(y,1);


    baseline_ext = [ ...
        repmat(initialMean,p,1); ...
        zeros(T,N)];


    for t = 1:T

        thisValue = ...
            phi(1,:);


        for lag = 1:p

            rows = ...
                2 + (lag-1)*N : ...
                1 + lag*N;


            thisValue = ...
                thisValue ...
                + baseline_ext(p+t-lag,:) ...
                * phi(rows,:);

        end


        baseline_ext(p+t,:) = ...
            thisValue;

    end


    baseline = ...
        baseline_ext(p+1:end,:);

end


function [h95,h70,hPoint] = ...
    plotCredibleBands( ...
    x, ...
    point, ...
    ci70, ...
    ci95)

% Article-style grayscale posterior credible regions.


    x = ...
        x(:);


    point = ...
        point(:);


    grey95 = ...
        [0.88 0.88 0.88];


    grey70 = ...
        [0.68 0.68 0.68];


    h95 = fill( ...
        [x;flipud(x)], ...
        [ci95(:,1);flipud(ci95(:,2))], ...
        grey95, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.75);


    hold on;


    h70 = fill( ...
        [x;flipud(x)], ...
        [ci70(:,1);flipud(ci70(:,2))], ...
        grey70, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.85);


    hPoint = plot( ...
        x, ...
        point, ...
        '-k', ...
        'LineWidth',2);


    grid on;
    box off;

end