%% ================================================================
%  AUSTRALIAN DOLLAR DRIVERS
%  SOE-BVAR SUBSTANTIVE LAMBDA ROBUSTNESS
%
%  Purpose:
%
%    Check whether substantive FEVD and historical-decomposition
%    conclusions depend materially on Minnesota tightness.
%
%  Lambda:
%
%       0.10
%       0.20  <-- final baseline, reused from existing results
%       0.30
%
%  Everything else is held fixed:
%
%       sample
%       p = 2
%       exact SOE restriction
%       prior means
%       lag decay
%       Cholesky ordering
%       stability restriction
%
%% ================================================================

clear;
clc;
close all;


%% 1. PATHS

folder = ...
    fileparts(mfilename('fullpath'));

addpath(fullfile(folder,'_func'));


resultDir = ...
    fullfile(folder,'results');

figDir = ...
    fullfile(folder,'figures');


if ~exist(figDir,'dir')
    mkdir(figDir);
end


dataFile = ...
    fullfile( ...
        folder, ...
        'data', ...
        'data_collected.xlsx');


baselineFile = ...
    fullfile( ...
        resultDir, ...
        'bvar_soe_baseline_lambda020_stable.mat');


articleFile = ...
    fullfile( ...
        resultDir, ...
        'bvar_fevd_hd_results.mat');


assert(isfile(baselineFile));
assert(isfile(articleFile));

assert(exist('bvar_soe','file') == 2, ...
    'bvar_soe.m not found.');

assert(exist('calculate_IRF_FEVD','file') == 2);

assert(exist('historical_decomposition','file') == 2);


%% 2. LOAD BASELINE MODEL

S = ...
    load(baselineFile);


BVAR_baseline = ...
    S.BVAR;


clear S


A = ...
    load(articleFile);


baselineArticle = ...
    A.bvar_article;


clear A


y = ...
    BVAR_baseline.y;


[T,N] = ...
    size(y);


p = ...
    BVAR_baseline.p;


n_foreign = ...
    BVAR_baseline.n_foreign;


assert(N == 7);
assert(p == 2);
assert(n_foreign == 3);


%% 3. LOAD DATES

data = readtable( ...
    dataFile, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


if ~isdatetime(data.quarter_start)

    if isnumeric(data.quarter_start)

        data.quarter_start = ...
            datetime( ...
                data.quarter_start, ...
                'ConvertFrom','excel');

    else

        data.quarter_start = ...
            datetime(data.quarter_start);

    end

end


sample = ...
    data.quarter_start >= datetime(1995,1,1) ...
    & data.quarter_start <= datetime(2026,4,1);


D = ...
    data(sample,:);


assert(height(D) == T);


%% 4. VARIABLE / SHOCK POSITIONS

shock_us = 1;

shock_comm = 2;

shock_vix = 3;

shock_augdp = 4;

shock_inf = 5;

shock_spread = 6;

shock_er = 7;


%% 5. ROBUSTNESS SETTINGS

lambdaGrid = ...
    [0.10 0.20 0.30];


nLambda = ...
    length(lambdaGrid);


horFEVD = ...
    20;


selectedHorizons = ...
    [1 4 8 12 20];


CI70 = ...
    [0.15 0.85];


CI95 = ...
    [0.025 0.975];


% Light robustness runs for alternative lambdas

robust_ndraws = ...
    3000;


robust_burnin = ...
    2000;


%% 6. HISTORICAL EPISODES
%
% Identical to final baseline HD script.

episodeNames = { ...
    'GFC', ...
    'Commodity-boom appreciation', ...
    'Post-boom depreciation', ...
    'COVID shock', ...
    'COVID rebound', ...
    'Recent period'};


episodeStart = [ ...
    datetime(2008,7,1); ...
    datetime(2009,7,1); ...
    datetime(2013,1,1); ...
    datetime(2020,1,1); ...
    datetime(2020,4,1); ...
    datetime(2022,1,1)];


episodeEnd = [ ...
    datetime(2009,4,1); ...
    datetime(2011,4,1); ...
    datetime(2015,7,1); ...
    datetime(2020,1,1); ...
    datetime(2021,4,1); ...
    datetime(2026,4,1)];


nEpisodes = ...
    length(episodeNames);


episode_i0 = ...
    nan(nEpisodes,1);


episode_i1 = ...
    nan(nEpisodes,1);


episodeActual = ...
    nan(nEpisodes,1);


for ee = 1:nEpisodes

    episode_i0(ee) = ...
        find( ...
            D.quarter_start < episodeStart(ee), ...
            1, ...
            'last');


    episode_i1(ee) = ...
        find( ...
            D.quarter_start <= episodeEnd(ee), ...
            1, ...
            'last');


    episodeActual(ee) = ...
        y(episode_i1(ee),shock_er) ...
        - y(episode_i0(ee),shock_er);

end


%% 7. STORAGE FOR MEDIAN FIGURES

FEVD_median_all = ...
    nan( ...
        nLambda, ...
        N, ...
        horFEVD);


% Grouped historical contributions:
%
% lambda x episode x group
%
% group 1 = commodity + VIX
% group 2 = relative yield + other FX

HD_group_median_all = ...
    nan( ...
        nLambda, ...
        nEpisodes, ...
        2);


%% 8. LONG-FORM OUTPUT TABLES

FEVD_Robustness = ...
    table();


HD_Robustness = ...
    table();


LambdaDiagnostics = ...
    table();


%% 9. MAIN LAMBDA LOOP

for ll = 1:nLambda

    lambda = ...
        lambdaGrid(ll);


    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('SUBSTANTIVE ROBUSTNESS: LAMBDA = %.2f\n',lambda);
    fprintf('============================================================\n');


    %% ------------------------------------------------------------
    % BASELINE LAMBDA = 0.20
    %
    % Reuse existing 10,000-draw results rather than recomputing.
    %% ------------------------------------------------------------

    if abs(lambda-0.20) < 1e-12

        fprintf('Using existing 10,000-draw baseline results.\n');


        B = ...
            BVAR_baseline;


        FEVD_draws = ...
            baselineArticle.FEVD_rtwi_draws;


        % Existing Episode_draws has:
        %
        % 1 baseline
        % 2 global activity
        % 3 commodity
        % 4 VIX
        % 5 domestic macro
        % 6 spread
        % 7 other FX
        %
        % Strip out baseline dynamics because this robustness
        % exercise concerns identified shocks.

        EpisodeShock_draws = ...
            baselineArticle.Episode_draws(:,2:7,:);


    %% ------------------------------------------------------------
    % ALTERNATIVE LAMBDA
    %% ------------------------------------------------------------

    else

        options = struct();


        options.ndraws = ...
            robust_ndraws;


        options.burnin = ...
            robust_burnin;


        options.thin = ...
            1;


        options.lambda = ...
            lambda;


        options.decay = ...
            1;


        options.own_lag_prior_mean = [ ...
            0
            1
            0
            0
            0
            0
            1];


        options.intercept_var = ...
            1e6;


        options.sigma_df = ...
            N + 2;


        options.sigma_scale_mult = ...
            1;


        options.stable_only = ...
            true;


        options.max_root = ...
            0.9999;


        options.max_stability_tries = ...
            5000;


        options.store_residuals = ...
            true;


        options.seed = ...
            25000 + ll;


        options.verbose = ...
            false;


        tic;


        B = ...
            bvar_soe( ...
                y, ...
                p, ...
                n_foreign, ...
                options);


        fprintf('BVAR estimation: %.1f seconds\n',toc);


        tic;


        [FEVD_draws,EpisodeShock_draws] = ...
            computePosteriorObjects( ...
                B, ...
                horFEVD, ...
                episode_i0, ...
                episode_i1);


        fprintf('FEVD + HD calculations: %.1f seconds\n',toc);

    end


    nThisDraws = ...
        size(FEVD_draws,3);


    %% ------------------------------------------------------------
    % DIAGNOSTICS
    %% ------------------------------------------------------------

    newDiag = table( ...
        lambda, ...
        nThisDraws, ...
        B.root_mean_phi, ...
        median(B.root_draws), ...
        quantile(B.root_draws,0.95), ...
        100*B.info.stability_rejection_rate, ...
        'VariableNames', ...
        { ...
        'Lambda', ...
        'PosteriorDraws', ...
        'PosteriorMeanRoot', ...
        'MedianDrawRoot', ...
        'P95DrawRoot', ...
        'StabilityRejectionPercent'});


    LambdaDiagnostics = ...
        [LambdaDiagnostics;newDiag];


    %% ------------------------------------------------------------
    % FEVD MEDIANS
    %% ------------------------------------------------------------

    FEVD_median_all(ll,:,:) = ...
        median( ...
            FEVD_draws, ...
            3);


    %% FEVD LONG TABLE

    shockIdx = [ ...
        shock_comm ...
        shock_vix ...
        shock_spread ...
        shock_er];


    shockNames = { ...
        'Commodity prices', ...
        'VIX', ...
        'Relative yields', ...
        'Other exchange-rate shocks'};


    for jj = 1:length(shockIdx)

        shock = ...
            shockIdx(jj);


        for hh = selectedHorizons

            vals = ...
                squeeze( ...
                    FEVD_draws( ...
                        shock, ...
                        hh, ...
                        :));


            q70 = ...
                quantile(vals,CI70);


            q95 = ...
                quantile(vals,CI95);


            newRow = table( ...
                lambda, ...
                string(shockNames{jj}), ...
                hh, ...
                median(vals), ...
                q70(1), ...
                q70(2), ...
                q95(1), ...
                q95(2), ...
                'VariableNames', ...
                { ...
                'Lambda', ...
                'Shock', ...
                'Horizon', ...
                'Median', ...
                'Lower70', ...
                'Upper70', ...
                'Lower95', ...
                'Upper95'});


            FEVD_Robustness = ...
                [FEVD_Robustness;newRow];

        end

    end


    %% ------------------------------------------------------------
    % HISTORICAL EPISODE COMPONENTS
    %
    % EpisodeShock_draws columns:
    %
    % 1 global activity
    % 2 commodity
    % 3 VIX
    % 4 domestic macro
    % 5 spread
    % 6 other FX
    %% ------------------------------------------------------------

    componentNames = { ...
        'Global activity', ...
        'Commodity prices', ...
        'VIX', ...
        'Domestic macro', ...
        'Relative yields', ...
        'Other exchange-rate shocks'};


    for ee = 1:nEpisodes

        for cc = 1:6

            vals = ...
                squeeze( ...
                    EpisodeShock_draws( ...
                        ee, ...
                        cc, ...
                        :));


            q70 = ...
                quantile(vals,CI70);


            q95 = ...
                quantile(vals,CI95);


            newRow = table( ...
                lambda, ...
                string(episodeNames{ee}), ...
                string(componentNames{cc}), ...
                episodeActual(ee), ...
                median(vals), ...
                q70(1), ...
                q70(2), ...
                q95(1), ...
                q95(2), ...
                'VariableNames', ...
                { ...
                'Lambda', ...
                'Episode', ...
                'Component', ...
                'ObservedChange', ...
                'Median', ...
                'Lower70', ...
                'Upper70', ...
                'Lower95', ...
                'Upper95'});


            HD_Robustness = ...
                [HD_Robustness;newRow];

        end

    end


    %% ------------------------------------------------------------
    % ORDERING-ROBUST GROUPED CHANNELS
    %% ------------------------------------------------------------

    commRisk_draws = ...
        EpisodeShock_draws(:,2,:) ...
        + EpisodeShock_draws(:,3,:);


    yieldFX_draws = ...
        EpisodeShock_draws(:,5,:) ...
        + EpisodeShock_draws(:,6,:);


    HD_group_median_all(ll,:,1) = ...
        squeeze( ...
            median( ...
                commRisk_draws, ...
                3));


    HD_group_median_all(ll,:,2) = ...
        squeeze( ...
            median( ...
                yieldFX_draws, ...
                3));


    for ee = 1:nEpisodes

        %% Commodity + risk

        vals = ...
            squeeze( ...
                commRisk_draws(ee,1,:));


        q70 = ...
            quantile(vals,CI70);


        q95 = ...
            quantile(vals,CI95);


        newRow = table( ...
            lambda, ...
            string(episodeNames{ee}), ...
            "Commodity + global risk", ...
            episodeActual(ee), ...
            median(vals), ...
            q70(1), ...
            q70(2), ...
            q95(1), ...
            q95(2), ...
            'VariableNames', ...
            { ...
            'Lambda', ...
            'Episode', ...
            'Component', ...
            'ObservedChange', ...
            'Median', ...
            'Lower70', ...
            'Upper70', ...
            'Lower95', ...
            'Upper95'});


        HD_Robustness = ...
            [HD_Robustness;newRow];


        %% Yield + other FX

        vals = ...
            squeeze( ...
                yieldFX_draws(ee,1,:));


        q70 = ...
            quantile(vals,CI70);


        q95 = ...
            quantile(vals,CI95);


        newRow = table( ...
            lambda, ...
            string(episodeNames{ee}), ...
            "Relative yield + other FX", ...
            episodeActual(ee), ...
            median(vals), ...
            q70(1), ...
            q70(2), ...
            q95(1), ...
            q95(2), ...
            'VariableNames', ...
            { ...
            'Lambda', ...
            'Episode', ...
            'Component', ...
            'ObservedChange', ...
            'Median', ...
            'Lower70', ...
            'Upper70', ...
            'Lower95', ...
            'Upper95'});


        HD_Robustness = ...
            [HD_Robustness;newRow];

    end


    %% Release large alternative model draws from memory

    if abs(lambda-0.20) > 1e-12

        clear B

    end

    clear FEVD_draws
    clear EpisodeShock_draws
    clear commRisk_draws
    clear yieldFX_draws

end


%% ================================================================
% FIGURES
%% ================================================================

%% 10. FEVD ROBUSTNESS FIGURE

h = ...
    (1:horFEVD)';


shockIdx = [ ...
    shock_comm ...
    shock_vix ...
    shock_spread ...
    shock_er];


shockTitles = { ...
    'Commodity-price shocks', ...
    'Global-risk / VIX shocks', ...
    'Relative-yield shocks', ...
    'Other exchange-rate shocks'};


figure( ...
    'Color','w', ...
    'Position',[90 60 1100 760]);


tiledlayout( ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


for jj = 1:4

    nexttile;

    hold on;


    shock = ...
        shockIdx(jj);


    for ll = 1:nLambda

        plot( ...
            h, ...
            squeeze( ...
                FEVD_median_all( ...
                    ll, ...
                    shock, ...
                    :)), ...
            'LineWidth',1.8);

    end


    grid on;
    box off;


    xlabel('Forecast horizon');

    ylabel('Share of RTWI variance (%)');

    title(shockTitles{jj});


    if jj == 1

        legend( ...
            '\lambda = 0.10', ...
            '\lambda = 0.20', ...
            '\lambda = 0.30', ...
            'Location','best');

    end

end


sgtitle( ...
    'BVAR FEVD Robustness to Minnesota Prior Tightness');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '35_bvar_lambda_fevd_robustness.png'), ...
    'Resolution',300);


%% 11. HISTORICAL-DECOMPOSITION ROBUSTNESS FIGURE

x = ...
    1:nEpisodes;


figure( ...
    'Color','w', ...
    'Position',[80 100 1250 650]);


tiledlayout( ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% Commodity + risk

nexttile;


bar( ...
    x, ...
    squeeze( ...
        HD_group_median_all(:,:,1))');


hold on;


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(x);

xticklabels(episodeNames);

xtickangle(15);


ylabel('Contribution, log points');

title('Commodity + global-risk channel');


legend( ...
    '\lambda = 0.10', ...
    '\lambda = 0.20', ...
    '\lambda = 0.30', ...
    'Location','eastoutside');


%% Yield + other FX

nexttile;


bar( ...
    x, ...
    squeeze( ...
        HD_group_median_all(:,:,2))');


hold on;


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(x);

xticklabels(episodeNames);

xtickangle(15);


ylabel('Contribution, log points');

title('Relative-yield + other exchange-rate channel');


sgtitle( ...
    'BVAR Historical-Decomposition Robustness to Prior Tightness');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '36_bvar_lambda_hd_robustness.png'), ...
    'Resolution',300);


%% ================================================================
% KEY PRINTED SUMMARIES
%% ================================================================

%% 12. H20 FEVD ONLY

H20_Table = ...
    FEVD_Robustness( ...
        FEVD_Robustness.Horizon == 20, ...
        :);


fprintf('\n============================================================\n');
fprintf('LAMBDA ROBUSTNESS: H20 RTWI FEVD\n');
fprintf('============================================================\n');

disp(H20_Table);


%% 13. GROUPED HD ONLY

groupMask = ...
    HD_Robustness.Component == "Commodity + global risk" ...
    | HD_Robustness.Component == "Relative yield + other FX";


GroupedHD_Table = ...
    HD_Robustness(groupMask,:);


fprintf('\n============================================================\n');
fprintf('LAMBDA ROBUSTNESS: GROUPED HISTORICAL CONTRIBUTIONS\n');
fprintf('============================================================\n');

disp(GroupedHD_Table);


%% 14. DIAGNOSTICS

fprintf('\n============================================================\n');
fprintf('LAMBDA ROBUSTNESS DIAGNOSTICS\n');
fprintf('============================================================\n');

disp(LambdaDiagnostics);


%% ================================================================
% EXPORT
%% ================================================================

outputFile = ...
    fullfile( ...
        resultDir, ...
        'bvar_lambda_substantive_robustness.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    LambdaDiagnostics, ...
    outputFile, ...
    'Sheet','diagnostics');


writetable( ...
    FEVD_Robustness, ...
    outputFile, ...
    'Sheet','FEVD');


writetable( ...
    HD_Robustness, ...
    outputFile, ...
    'Sheet','HD');


writetable( ...
    H20_Table, ...
    outputFile, ...
    'Sheet','H20');


writetable( ...
    GroupedHD_Table, ...
    outputFile, ...
    'Sheet','HD_grouped');


lambda_robustness = struct();


lambda_robustness.lambdaGrid = ...
    lambdaGrid;


lambda_robustness.FEVD_median_all = ...
    FEVD_median_all;


lambda_robustness.HD_group_median_all = ...
    HD_group_median_all;


lambda_robustness.FEVD_Robustness = ...
    FEVD_Robustness;


lambda_robustness.HD_Robustness = ...
    HD_Robustness;


lambda_robustness.LambdaDiagnostics = ...
    LambdaDiagnostics;


save( ...
    fullfile( ...
        resultDir, ...
        'bvar_lambda_substantive_robustness.mat'), ...
    'lambda_robustness', ...
    '-v7.3');


fprintf('\nLambda substantive robustness complete.\n');


%% ================================================================
% LOCAL FUNCTION
%% ================================================================

function [FEVD_draws,EpisodeShock_draws] = ...
    computePosteriorObjects( ...
    BVAR, ...
    horFEVD, ...
    episode_i0, ...
    episode_i1)

% ================================================================
% Compute only the quantities needed for the light lambda robustness
% exercise.
%
% FEVD_draws:
%       N x horizon x posterior draw
%
% EpisodeShock_draws:
%       episode x 6 components x posterior draw
%
% Components:
%
%       1 global activity
%       2 commodity
%       3 VIX
%       4 domestic macro = AU GDP + inflation
%       5 relative yield
%       6 other FX
%% ================================================================


    [T,N] = ...
        size(BVAR.y);


    nDraws = ...
        size(BVAR.phi_draws,3);


    nEpisodes = ...
        length(episode_i0);


    assert(~isempty(BVAR.e_draws));


    FEVD_draws = ...
        nan( ...
            N, ...
            horFEVD, ...
            nDraws);


    EpisodeShock_draws = ...
        nan( ...
            nEpisodes, ...
            6, ...
            nDraws);


    for ss = 1:nDraws

        phi_s = ...
            BVAR.phi_draws(:,:,ss);


        Sigma_s = ...
            BVAR.SIGMA_draws(:,:,ss);


        e_s = ...
            BVAR.e_draws(:,:,ss);


        [B_s,flag] = ...
            chol( ...
                Sigma_s, ...
                'lower');


        assert(flag == 0);


        %% FEVD

        [~,FEVD_s] = ...
            calculate_IRF_FEVD( ...
                phi_s, ...
                B_s, ...
                horFEVD, ...
                'FEVD');


        FEVD_draws(:,:,ss) = ...
            squeeze( ...
                FEVD_s( ...
                    7, ...
                    :, ...
                    1:horFEVD));


        %% HISTORICAL DECOMPOSITION

        HD_s = ...
            historical_decomposition( ...
                phi_s, ...
                e_s, ...
                B_s);


        HDrtwi = ...
            HD_s{7};


        components = [ ...
            HDrtwi(:,1) ...
            HDrtwi(:,2) ...
            HDrtwi(:,3) ...
            HDrtwi(:,4) + HDrtwi(:,5) ...
            HDrtwi(:,6) ...
            HDrtwi(:,7)];


        for ee = 1:nEpisodes

            i0 = ...
                episode_i0(ee);


            i1 = ...
                episode_i1(ee);


            EpisodeShock_draws(ee,:,ss) = ...
                components(i1,:) ...
                - components(i0,:);

        end

    end

end