%% ================================================================
%  AUSTRALIAN DOLLAR DRIVERS
%  SOE-BVAR IRF CONSISTENCY CHECK
%
%  Purpose:
%
%    Verify that the final stable SOE-BVAR produces economically
%    sensible RTWI responses to the same normalized shocks used in
%    the classical SVAR:
%
%       +10 log-point commodity-price shock
%       +10 log-point VIX shock
%       +100 bp AU-US 2-year spread shock
%
%    Report:
%
%       posterior median
%       central 70% credible interval
%       central 95% credible interval
%       classical SVAR(2) point estimate
%
%    Also verify exact SOE implication:
%
%       a domestic spread shock cannot move the first three
%       foreign variables.
%% ================================================================

clear;
clc;
close all;


%% 1. PATHS

folder = ...
    fileparts(mfilename('fullpath'));

addpath(fullfile(folder,'_func'));


resultDir = ...
    fullfile(folder,'results');

figDir = ...
    fullfile(folder,'figures');


if ~exist(figDir,'dir')
    mkdir(figDir);
end


BVARfile = ...
    fullfile( ...
        resultDir, ...
        'bvar_soe_baseline_lambda020_stable.mat');


assert(isfile(BVARfile), ...
    'Final BVAR file not found.');

assert(exist('calculate_IRF_FEVD','file') == 2, ...
    'calculate_IRF_FEVD.m not found.');


%% 2. LOAD FINAL BVAR

S = ...
    load(BVARfile);


BVAR = ...
    S.BVAR;


clear S


[T,N] = ...
    size(BVAR.y);


p = ...
    BVAR.p;


n_foreign = ...
    BVAR.n_foreign;


nDraws = ...
    size(BVAR.phi_draws,3);


assert(N == 7);
assert(p == 2);
assert(n_foreign == 3);


%% 3. VARIABLE POSITIONS

shock_us = 1;

shock_comm = 2;

shock_vix = 3;

shock_augdp = 4;

shock_inf = 5;

shock_spread = 6;

shock_er = 7;


%% 4. IRF SETTINGS

hor = 24;

plot_hor = 16;


% Same economically-sized shocks as classical SVAR

size_comm_shock = 10;

size_vix_shock = 10;

size_spread_shock = 1;


CI70 = ...
    [0.15 0.85];

CI95 = ...
    [0.025 0.975];


%% 5. STORAGE

rtwi_comm_draws = ...
    nan(hor+1,nDraws);

rtwi_vix_draws = ...
    nan(hor+1,nDraws);

rtwi_spread_draws = ...
    nan(hor+1,nDraws);


% Exact SOE diagnostic

maxForeignResponseSpread = ...
    0;


fprintf('\n============================================================\n');
fprintf('BVAR IRF CONSISTENCY CHECK\n');
fprintf('============================================================\n');

fprintf('Posterior draws: %d\n',nDraws);


%% 6. IRF FOR EVERY POSTERIOR DRAW

tic;


for ss = 1:nDraws

    phi_s = ...
        BVAR.phi_draws(:,:,ss);


    Sigma_s = ...
        BVAR.SIGMA_draws(:,:,ss);


    [B_s,flag] = ...
        chol( ...
            Sigma_s, ...
            'lower');


    assert(flag == 0);


    %% COMMODITY

    resp = ...
        normalizedShockResponse( ...
            phi_s, ...
            B_s, ...
            shock_comm, ...
            size_comm_shock, ...
            hor);


    rtwi_comm_draws(:,ss) = ...
        resp(shock_er,:)';


    %% VIX

    resp = ...
        normalizedShockResponse( ...
            phi_s, ...
            B_s, ...
            shock_vix, ...
            size_vix_shock, ...
            hor);


    rtwi_vix_draws(:,ss) = ...
        resp(shock_er,:)';


    %% SPREAD

    respSpread = ...
        normalizedShockResponse( ...
            phi_s, ...
            B_s, ...
            shock_spread, ...
            size_spread_shock, ...
            hor);


    rtwi_spread_draws(:,ss) = ...
        respSpread(shock_er,:)';


    %% EXACT SOE CHECK

    thisForeignResponse = ...
        max( ...
            abs( ...
                respSpread( ...
                    1:n_foreign, ...
                    :)), ...
            [], ...
            'all');


    maxForeignResponseSpread = ...
        max( ...
            maxForeignResponseSpread, ...
            thisForeignResponse);


    if mod(ss,1000) == 0

        fprintf('  IRF draw %d of %d\n', ...
            ss,nDraws);

    end

end


fprintf('IRF calculations completed in %.1f seconds.\n',toc);


fprintf('\nMaximum foreign response to spread shock = %.3e\n', ...
    maxForeignResponseSpread);


assert( ...
    maxForeignResponseSpread < 1e-10, ...
    'SOE restriction failed in posterior IRFs.');


%% 7. POSTERIOR SUMMARIES

comm_med = ...
    median(rtwi_comm_draws,2);

vix_med = ...
    median(rtwi_vix_draws,2);

spread_med = ...
    median(rtwi_spread_draws,2);


comm_CI70 = ...
    quantile( ...
        rtwi_comm_draws, ...
        CI70, ...
        2);

comm_CI95 = ...
    quantile( ...
        rtwi_comm_draws, ...
        CI95, ...
        2);


vix_CI70 = ...
    quantile( ...
        rtwi_vix_draws, ...
        CI70, ...
        2);

vix_CI95 = ...
    quantile( ...
        rtwi_vix_draws, ...
        CI95, ...
        2);


spread_CI70 = ...
    quantile( ...
        rtwi_spread_draws, ...
        CI70, ...
        2);

spread_CI95 = ...
    quantile( ...
        rtwi_spread_draws, ...
        CI95, ...
        2);


%% 8. CLASSICAL SVAR COMPARATOR

classicalFile = ...
    fullfile( ...
        resultDir, ...
        'classical_svar2_baseline_locked.mat');


haveClassical = ...
    isfile(classicalFile);


if haveClassical

    C = ...
        load(classicalFile);


    phi_classical = ...
        C.classical_baseline.results.phi;


    B_classical = ...
        C.classical_baseline.results.B;


    classical_comm = ...
        normalizedShockResponse( ...
            phi_classical, ...
            B_classical, ...
            shock_comm, ...
            size_comm_shock, ...
            hor);


    classical_vix = ...
        normalizedShockResponse( ...
            phi_classical, ...
            B_classical, ...
            shock_vix, ...
            size_vix_shock, ...
            hor);


    classical_spread = ...
        normalizedShockResponse( ...
            phi_classical, ...
            B_classical, ...
            shock_spread, ...
            size_spread_shock, ...
            hor);


    classical_comm = ...
        classical_comm(shock_er,:)';


    classical_vix = ...
        classical_vix(shock_er,:)';


    classical_spread = ...
        classical_spread(shock_er,:)';


    clear C

else

    classical_comm = ...
        nan(hor+1,1);

    classical_vix = ...
        nan(hor+1,1);

    classical_spread = ...
        nan(hor+1,1);

end


%% 9. ARTICLE-STYLE IRF FIGURE

h = ...
    (0:plot_hor)';


figure( ...
    'Color','w', ...
    'Position',[80 100 1250 400]);


tiledlayout( ...
    1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% COMMODITY

nexttile;


[h95,h70,hPoint] = ...
    plotBands( ...
        h, ...
        comm_med(1:plot_hor+1), ...
        comm_CI70(1:plot_hor+1,:), ...
        comm_CI95(1:plot_hor+1,:));


if haveClassical

    hClassical = plot( ...
        h, ...
        classical_comm(1:plot_hor+1), ...
        '--k', ...
        'LineWidth',1.3);

end


title('+10% commodity-price shock');

xlabel('Quarters');

ylabel('Real TWI response (%)');

xlim([0 plot_hor]);


if haveClassical

    legend( ...
        [hPoint h70 h95 hClassical], ...
        { ...
        'BVAR posterior median', ...
        '70% credible interval', ...
        '95% credible interval', ...
        'Classical SVAR(2)'}, ...
        'Location','best', ...
        'FontSize',8);

end


%% VIX

nexttile;


plotBands( ...
    h, ...
    vix_med(1:plot_hor+1), ...
    vix_CI70(1:plot_hor+1,:), ...
    vix_CI95(1:plot_hor+1,:));


if haveClassical

    plot( ...
        h, ...
        classical_vix(1:plot_hor+1), ...
        '--k', ...
        'LineWidth',1.3);

end


title('+10% VIX shock');

xlabel('Quarters');

ylabel('Real TWI response (%)');

xlim([0 plot_hor]);


%% SPREAD

nexttile;


plotBands( ...
    h, ...
    spread_med(1:plot_hor+1), ...
    spread_CI70(1:plot_hor+1,:), ...
    spread_CI95(1:plot_hor+1,:));


if haveClassical

    plot( ...
        h, ...
        classical_spread(1:plot_hor+1), ...
        '--k', ...
        'LineWidth',1.3);

end


title('+100 bp AU-US 2yr spread shock');

xlabel('Quarters');

ylabel('Real TWI response (%)');

xlim([0 plot_hor]);


sgtitle( ...
    'BVAR Real TWI Responses: Consistency with the Classical SVAR');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '34_bvar_irf_consistency.png'), ...
    'Resolution',300);


%% 10. SELECTED-HORIZON TABLE

selectedH = ...
    [0 1 4 8 12 16];


IRF_Table = table();


shockNames = { ...
    'Commodity prices', ...
    'VIX', ...
    'Relative yields'};


drawCells = { ...
    rtwi_comm_draws, ...
    rtwi_vix_draws, ...
    rtwi_spread_draws};


medCells = { ...
    comm_med, ...
    vix_med, ...
    spread_med};


classicalCells = { ...
    classical_comm, ...
    classical_vix, ...
    classical_spread};


expectedSign = [ ...
    1 ...
   -1 ...
    1];


for jj = 1:3

    Ddraw = ...
        drawCells{jj};


    med = ...
        medCells{jj};


    classical = ...
        classicalCells{jj};


    for hh = selectedH

        ii = ...
            hh + 1;


        vals = ...
            Ddraw(ii,:)';


        q70 = ...
            quantile(vals,CI70);


        q95 = ...
            quantile(vals,CI95);


        if expectedSign(jj) > 0

            probExpected = ...
                100*mean(vals > 0);

        else

            probExpected = ...
                100*mean(vals < 0);

        end


        newRow = table( ...
            string(shockNames{jj}), ...
            hh, ...
            med(ii), ...
            q70(1), ...
            q70(2), ...
            q95(1), ...
            q95(2), ...
            classical(ii), ...
            probExpected, ...
            'VariableNames', ...
            { ...
            'Shock', ...
            'Horizon', ...
            'BVAR_Median', ...
            'Lower70', ...
            'Upper70', ...
            'Lower95', ...
            'Upper95', ...
            'Classical_SVAR', ...
            'ProbabilityExpectedSign'});


        IRF_Table = ...
            [IRF_Table;newRow];

    end

end


fprintf('\n============================================================\n');
fprintf('BVAR IRF SELECTED-HORIZON RESULTS\n');
fprintf('============================================================\n');

disp(IRF_Table);


%% 11. 95% CREDIBLE INTERVALS EXCLUDE ZERO

sig_comm = ...
    (comm_CI95(:,1) > 0) | ...
    (comm_CI95(:,2) < 0);


sig_vix = ...
    (vix_CI95(:,1) > 0) | ...
    (vix_CI95(:,2) < 0);


sig_spread = ...
    (spread_CI95(:,1) > 0) | ...
    (spread_CI95(:,2) < 0);


fprintf('\n95%% credible intervals exclude zero:\n');

fprintf('Commodity: %s\n', ...
    mat2str(find(sig_comm)'-1));

fprintf('VIX:       %s\n', ...
    mat2str(find(sig_vix)'-1));

fprintf('Spread:    %s\n', ...
    mat2str(find(sig_spread)'-1));


%% 12. EXPORT

outputFile = ...
    fullfile( ...
        resultDir, ...
        'bvar_irf_consistency.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    IRF_Table, ...
    outputFile, ...
    'Sheet','IRFs');


IRF_Diagnostics = table( ...
    maxForeignResponseSpread, ...
    BVAR.root_mean_phi, ...
    median(BVAR.root_draws), ...
    'VariableNames', ...
    { ...
    'MaxForeignResponseToSpreadShock', ...
    'PosteriorMeanRoot', ...
    'MedianDrawRoot'});


writetable( ...
    IRF_Diagnostics, ...
    outputFile, ...
    'Sheet','diagnostics');


bvar_irf = struct();

bvar_irf.rtwi_comm_draws = ...
    rtwi_comm_draws;

bvar_irf.rtwi_vix_draws = ...
    rtwi_vix_draws;

bvar_irf.rtwi_spread_draws = ...
    rtwi_spread_draws;

bvar_irf.comm_median = ...
    comm_med;

bvar_irf.vix_median = ...
    vix_med;

bvar_irf.spread_median = ...
    spread_med;

bvar_irf.comm_CI70 = ...
    comm_CI70;

bvar_irf.comm_CI95 = ...
    comm_CI95;

bvar_irf.vix_CI70 = ...
    vix_CI70;

bvar_irf.vix_CI95 = ...
    vix_CI95;

bvar_irf.spread_CI70 = ...
    spread_CI70;

bvar_irf.spread_CI95 = ...
    spread_CI95;

bvar_irf.IRF_Table = ...
    IRF_Table;


save( ...
    fullfile( ...
        resultDir, ...
        'bvar_irf_consistency.mat'), ...
    'bvar_irf', ...
    '-v7.3');


fprintf('\nBVAR IRF consistency check complete.\n');


%% ================================================================
% LOCAL FUNCTIONS
%% ================================================================

function response = normalizedShockResponse( ...
    phi, ...
    B, ...
    shockIndex, ...
    shockSize, ...
    hor)

    N = ...
        size(B,1);


    Bn = ...
        B;


    ownImpact = ...
        B(shockIndex,shockIndex);


    if abs(ownImpact) < 1e-12

        error( ...
            'Shock own-impact is effectively zero.');

    end


    Bn(:,shockIndex) = ...
        shockSize ...
        * B(:,shockIndex) ...
        / ownImpact;


    IRF = ...
        calculate_IRF_FEVD( ...
            phi, ...
            Bn, ...
            hor);


    IRF3 = ...
        reshape( ...
            IRF, ...
            N,N,hor+1);


    response = ...
        squeeze( ...
            IRF3(:,shockIndex,:));


    assert( ...
        abs( ...
            response(shockIndex,1) ...
            - shockSize) ...
        < 1e-8);

end


function [h95,h70,hPoint] = plotBands( ...
    x, ...
    point, ...
    ci70, ...
    ci95)

    x = ...
        x(:);

    point = ...
        point(:);


    grey95 = ...
        [0.88 0.88 0.88];

    grey70 = ...
        [0.68 0.68 0.68];


    h95 = fill( ...
        [x;flipud(x)], ...
        [ci95(:,1);flipud(ci95(:,2))], ...
        grey95, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.75);


    hold on;


    h70 = fill( ...
        [x;flipud(x)], ...
        [ci70(:,1);flipud(ci70(:,2))], ...
        grey70, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.85);


    hPoint = plot( ...
        x, ...
        point, ...
        '-k', ...
        'LineWidth',2);


    yline( ...
        0, ...
        'k:', ...
        'HandleVisibility','off');


    grid on;
    box off;

end