%% ================================================================
%  RECENT AUSTRALIAN DOLLAR APPRECIATION
%  SOE-BVAR HISTORICAL DECOMPOSITION
%
%  Episode:
%
%       2025Q4 to 2026Q2
%
%  Change is measured from:
%
%       2025Q3 to 2026Q2
%
%  so the episode contains:
%
%       2025Q4
%       2026Q1
%       2026Q2
%
%  Outputs:
%
%   1. Posterior-mean-model point decomposition
%   2. Posterior median contributions
%   3. 70% credible intervals
%   4. 95% credible intervals
%   5. Ordering-robust grouped channels
%
%  Uses final locked SOE-BVAR:
%
%       lambda = 0.20
%       p = 2
%       stable-only posterior
%       10,000 retained draws
%% ================================================================

clear;
clc;
close all;


%% ================================================================
% 1. PATHS
%% ================================================================

folder = ...
    fileparts(mfilename('fullpath'));


addpath(fullfile(folder,'_func'));


resultDir = ...
    fullfile(folder,'results');


figDir = ...
    fullfile(folder,'figures');


if ~exist(figDir,'dir')
    mkdir(figDir);
end


dataFile = ...
    fullfile( ...
        folder, ...
        'data', ...
        'data_collected.xlsx');


BVARfile = ...
    fullfile( ...
        resultDir, ...
        'bvar_soe_baseline_lambda020_stable.mat');


assert( ...
    isfile(BVARfile), ...
    'Final BVAR file not found.');


assert( ...
    exist('historical_decomposition','file') == 2, ...
    'historical_decomposition.m not found.');


%% ================================================================
% 2. LOAD FINAL BVAR
%% ================================================================

S = ...
    load(BVARfile);


BVAR = ...
    S.BVAR;


clear S


y = ...
    BVAR.y;


[T,N] = ...
    size(y);


p = ...
    BVAR.p;


nDraws = ...
    size(BVAR.phi_draws,3);


assert(N == 7);

assert(p == 2);


assert( ...
    ~isempty(BVAR.e_draws), ...
    'BVAR residual draws were not stored.');


fprintf('\n');
fprintf('============================================================\n');
fprintf('BVAR: RECENT APPRECIATION HISTORICAL DECOMPOSITION\n');
fprintf('============================================================\n');

fprintf('Posterior draws: %d\n',nDraws);


%% ================================================================
% 3. VARIABLE / SHOCK POSITIONS
%% ================================================================

shock_us = 1;

shock_comm = 2;

shock_vix = 3;

shock_augdp = 4;

shock_inf = 5;

shock_spread = 6;

shock_er = 7;


%% ================================================================
% 4. IMPORT DATES
%% ================================================================

data = readtable( ...
    dataFile, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


if ~isdatetime(data.quarter_start)

    if isnumeric(data.quarter_start)

        data.quarter_start = ...
            datetime( ...
                data.quarter_start, ...
                'ConvertFrom','excel');

    else

        data.quarter_start = ...
            datetime(data.quarter_start);

    end

end


%% ================================================================
% 5. MATCH BVAR SAMPLE
%% ================================================================

sample = ...
    data.quarter_start >= datetime(1995,1,1) ...
    & data.quarter_start <= datetime(2026,4,1);


D = ...
    data(sample,:);


assert( ...
    height(D) == T, ...
    'Data dates do not match BVAR sample.');


%% ================================================================
% 6. DEFINE RECENT APPRECIATION EPISODE
%% ================================================================

episodeName = ...
    '2025Q4-2026Q2';


episodeStart = ...
    datetime(2025,10,1);


episodeEnd = ...
    datetime(2026,4,1);


% Quarter immediately BEFORE episode starts:
%
% 2025Q3

i0 = ...
    find( ...
        D.quarter_start < episodeStart, ...
        1, ...
        'last');


% Final quarter:
%
% 2026Q2

i1 = ...
    find( ...
        D.quarter_start <= episodeEnd, ...
        1, ...
        'last');


assert( ...
    ~isempty(i0) && ~isempty(i1));


fprintf('\nEpisode: %s\n',episodeName);

fprintf( ...
    'Change measured from %s to %s\n', ...
    string(D.quarter_start(i0)), ...
    string(D.quarter_start(i1)));


%% ================================================================
% 7. OBSERVED RTWI CHANGE
%% ================================================================

ActualChange = ...
    y(i1,shock_er) ...
    - y(i0,shock_er);


fprintf( ...
    'Observed RTWI change: %.4f log points\n', ...
    ActualChange);


%% ================================================================
% 8. CREDIBLE INTERVAL SETTINGS
%% ================================================================

CI70 = ...
    [0.15 0.85];


CI95 = ...
    [0.025 0.975];


%% ================================================================
% PART A
% POSTERIOR-MEAN-MODEL POINT DECOMPOSITION
%% ================================================================

%% 9. POSTERIOR-MEAN PARAMETERS

phi_point = ...
    BVAR.phi_mean;


Sigma_point = ...
    BVAR.SIGMA_mean;


e_point = ...
    BVAR.e_mean;


[B_point,flag] = ...
    chol( ...
        Sigma_point, ...
        'lower');


assert( ...
    flag == 0, ...
    'Posterior-mean covariance matrix is not positive definite.');


%% ================================================================
% 10. POSTERIOR-MEAN HISTORICAL DECOMPOSITION
%% ================================================================

HD_point = ...
    historical_decomposition( ...
        phi_point, ...
        e_point, ...
        B_point);


HDrtwi_point = ...
    HD_point{shock_er};


%% ================================================================
% 11. POSTERIOR-MEAN NO-SHOCK BASELINE
%% ================================================================

baseline_point = ...
    constructVARBaseline( ...
        phi_point, ...
        y, ...
        p);


%% ================================================================
% 12. GROUP STRUCTURAL CONTRIBUTIONS
%
% Columns:
%
% 1 Global activity
% 2 Commodity prices
% 3 VIX / global risk
% 4 Domestic macro = AU GDP + inflation
% 5 Relative yields
% 6 Other exchange-rate shock
%% ================================================================

HD_grouped_point = [ ...
    HDrtwi_point(:,shock_us) ...
    HDrtwi_point(:,shock_comm) ...
    HDrtwi_point(:,shock_vix) ...
    HDrtwi_point(:,shock_augdp) ...
        + HDrtwi_point(:,shock_inf) ...
    HDrtwi_point(:,shock_spread) ...
    HDrtwi_point(:,shock_er)];


%% ================================================================
% 13. POINT CONTRIBUTIONS OVER 2025Q4-2026Q2
%
% PointContrib columns:
%
% 1 Baseline dynamics
% 2 Global activity
% 3 Commodity prices
% 4 VIX
% 5 Domestic macro
% 6 Relative yields
% 7 Other FX
%% ================================================================

PointContrib = ...
    nan(1,7);


%% Baseline

PointContrib(1) = ...
    baseline_point(i1,shock_er) ...
    - baseline_point(i0,shock_er);


%% Structural shocks

PointContrib(2:7) = ...
    HD_grouped_point(i1,:) ...
    - HD_grouped_point(i0,:);


%% Accounting

PointError = ...
    ActualChange ...
    - sum(PointContrib);


fprintf('\n');
fprintf('Posterior-mean-model accounting error: %.3e\n', ...
    PointError);


assert( ...
    abs(PointError) < 1e-8, ...
    'Posterior-mean point decomposition does not reconstruct RTWI change.');


%% ================================================================
% PART B
% FULL POSTERIOR UNCERTAINTY
%% ================================================================

%% 14. STORAGE
%
% 1 x 7 x posterior draw

EpisodeDraws = ...
    nan( ...
        1, ...
        7, ...
        nDraws);


maxAccountingError = ...
    0;


%% ================================================================
% 15. LOOP THROUGH POSTERIOR DRAWS
%% ================================================================

fprintf('\n');
fprintf('Calculating posterior historical decompositions...\n');


tic;


for ss = 1:nDraws

    %% Parameters

    phi_s = ...
        BVAR.phi_draws(:,:,ss);


    Sigma_s = ...
        BVAR.SIGMA_draws(:,:,ss);


    e_s = ...
        BVAR.e_draws(:,:,ss);


    %% Cholesky impact matrix

    [B_s,flag] = ...
        chol( ...
            Sigma_s, ...
            'lower');


    assert(flag == 0);


    %% Historical decomposition

    HD_s = ...
        historical_decomposition( ...
            phi_s, ...
            e_s, ...
            B_s);


    HDrtwi_s = ...
        HD_s{shock_er};


    %% No-shock baseline for this draw

    baseline_s = ...
        constructVARBaseline( ...
            phi_s, ...
            y, ...
            p);


    %% Group shocks

    grouped_s = [ ...
        HDrtwi_s(:,shock_us) ...
        HDrtwi_s(:,shock_comm) ...
        HDrtwi_s(:,shock_vix) ...
        HDrtwi_s(:,shock_augdp) ...
            + HDrtwi_s(:,shock_inf) ...
        HDrtwi_s(:,shock_spread) ...
        HDrtwi_s(:,shock_er)];


    %% Full-history accounting check

    accounting_s = ...
        y(:,shock_er) ...
        - baseline_s(:,shock_er) ...
        - sum(HDrtwi_s,2);


    maxAccountingError = ...
        max( ...
            maxAccountingError, ...
            max(abs(accounting_s)));


    %% Episode contribution:
    %
    % 2026Q2 minus 2025Q3

    EpisodeDraws(1,1,ss) = ...
        baseline_s(i1,shock_er) ...
        - baseline_s(i0,shock_er);


    EpisodeDraws(1,2:7,ss) = ...
        grouped_s(i1,:) ...
        - grouped_s(i0,:);


    %% Progress

    if mod(ss,1000) == 0

        fprintf( ...
            '  Draw %d of %d\n', ...
            ss, ...
            nDraws);

    end

end


elapsed = ...
    toc;


fprintf( ...
    'Posterior HD calculations completed in %.1f seconds.\n', ...
    elapsed);


fprintf( ...
    'Maximum posterior accounting error: %.3e\n', ...
    maxAccountingError);


assert( ...
    maxAccountingError < 1e-8, ...
    'Posterior HD accounting failed.');


%% ================================================================
% 16. POSTERIOR SUMMARIES
%% ================================================================

componentNames = { ...
    'Baseline dynamics', ...
    'Global activity', ...
    'Commodity prices', ...
    'Global risk (VIX)', ...
    'Domestic macro', ...
    'Relative yields', ...
    'Other exchange-rate shocks'};


PosteriorMedian = ...
    nan(1,7);


Lower70 = ...
    nan(1,7);


Upper70 = ...
    nan(1,7);


Lower95 = ...
    nan(1,7);


Upper95 = ...
    nan(1,7);


for cc = 1:7

    vals = ...
        squeeze( ...
            EpisodeDraws(1,cc,:));


    PosteriorMedian(cc) = ...
        median(vals);


    q70 = ...
        quantile( ...
            vals, ...
            CI70);


    q95 = ...
        quantile( ...
            vals, ...
            CI95);


    Lower70(cc) = ...
        q70(1);


    Upper70(cc) = ...
        q70(2);


    Lower95(cc) = ...
        q95(1);


    Upper95(cc) = ...
        q95(2);

end


%% ================================================================
% 17. INDIVIDUAL-COMPONENT RESULTS TABLE
%% ================================================================

RecentBVAR = table( ...
    string(componentNames(:)), ...
    PointContrib(:), ...
    PosteriorMedian(:), ...
    Lower70(:), ...
    Upper70(:), ...
    Lower95(:), ...
    Upper95(:), ...
    'VariableNames', ...
    { ...
    'Component', ...
    'PosteriorMeanModel_Point', ...
    'PosteriorMedian', ...
    'Lower70', ...
    'Upper70', ...
    'Lower95', ...
    'Upper95'});


fprintf('\n');
fprintf('============================================================\n');
fprintf('INDIVIDUAL BVAR CONTRIBUTIONS: 2025Q4-2026Q2\n');
fprintf('============================================================\n');

disp(RecentBVAR);


%% ================================================================
% PART C
% ORDERING-ROBUST GROUPED CHANNELS
%% ================================================================

%% 18. CREATE GROUP DRAWS

CommodityRiskDraws = ...
    squeeze( ...
        EpisodeDraws(1,3,:) ...
        + EpisodeDraws(1,4,:));


YieldFXDraws = ...
    squeeze( ...
        EpisodeDraws(1,6,:) ...
        + EpisodeDraws(1,7,:));


%% ================================================================
% 19. GROUP POSTERIOR SUMMARIES
%% ================================================================

CommodityRiskMedian = ...
    median(CommodityRiskDraws);


q = ...
    quantile( ...
        CommodityRiskDraws, ...
        CI70);


CommodityRisk70 = ...
    q;


q = ...
    quantile( ...
        CommodityRiskDraws, ...
        CI95);


CommodityRisk95 = ...
    q;


YieldFXMedian = ...
    median(YieldFXDraws);


q = ...
    quantile( ...
        YieldFXDraws, ...
        CI70);


YieldFX70 = ...
    q;


q = ...
    quantile( ...
        YieldFXDraws, ...
        CI95);


YieldFX95 = ...
    q;


%% ================================================================
% 20. GROUPED RESULTS TABLE
%% ================================================================

RecentBVAR_Grouped = table( ...
    [ ...
        "Commodity + global risk"
        "Relative yield + other FX"], ...
    [ ...
        PointContrib(3)+PointContrib(4)
        PointContrib(6)+PointContrib(7)], ...
    [ ...
        CommodityRiskMedian
        YieldFXMedian], ...
    [ ...
        CommodityRisk70(1)
        YieldFX70(1)], ...
    [ ...
        CommodityRisk70(2)
        YieldFX70(2)], ...
    [ ...
        CommodityRisk95(1)
        YieldFX95(1)], ...
    [ ...
        CommodityRisk95(2)
        YieldFX95(2)], ...
    'VariableNames', ...
    { ...
    'Channel', ...
    'PosteriorMeanModel_Point', ...
    'PosteriorMedian', ...
    'Lower70', ...
    'Upper70', ...
    'Lower95', ...
    'Upper95'});


fprintf('\n');
fprintf('============================================================\n');
fprintf('ORDERING-ROBUST GROUPED CHANNELS\n');
fprintf('============================================================\n');

disp(RecentBVAR_Grouped);


%% ================================================================
% 21. PRINT COMPACT ECONOMIC SUMMARY
%% ================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('BVAR SUMMARY: LATE-2025 TO MID-2026 APPRECIATION\n');
fprintf('============================================================\n');


fprintf( ...
    'Observed RTWI change:                 %8.3f\n', ...
    ActualChange);


fprintf('\nPosterior-median individual contributions:\n');


for cc = 1:7

    fprintf( ...
        '%-34s %8.3f\n', ...
        componentNames{cc}, ...
        PosteriorMedian(cc));

end


fprintf('\nGrouped channels:\n');


fprintf( ...
    'Commodity + global risk:             %8.3f\n', ...
    CommodityRiskMedian);


fprintf( ...
    '   70%% credible interval: [%7.3f, %7.3f]\n', ...
    CommodityRisk70(1), ...
    CommodityRisk70(2));


fprintf( ...
    '   95%% credible interval: [%7.3f, %7.3f]\n', ...
    CommodityRisk95(1), ...
    CommodityRisk95(2));


fprintf('\n');


fprintf( ...
    'Relative yield + other FX:           %8.3f\n', ...
    YieldFXMedian);


fprintf( ...
    '   70%% credible interval: [%7.3f, %7.3f]\n', ...
    YieldFX70(1), ...
    YieldFX70(2));


fprintf( ...
    '   95%% credible interval: [%7.3f, %7.3f]\n', ...
    YieldFX95(1), ...
    YieldFX95(2));


%% ================================================================
% PART D
% FIGURE 1
% POSTERIOR-MEAN-MODEL STACKED DECOMPOSITION
%% ================================================================

figure( ...
    'Color','w', ...
    'Position',[180 140 900 520]);


b = bar( ...
    1, ...
    PointContrib, ...
    'stacked');


hold on;


hActual = plot( ...
    1, ...
    ActualChange, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',9);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


xlim([0.4 1.6]);


xticks(1);


xticklabels( ...
    {'2025Q4-2026Q2'});


ylabel( ...
    'Contribution to RTWI change, log points');


title( ...
    'BVAR: What Drove the Late-2025 to Mid-2026 Appreciation?');


grid on;
box off;


set( ...
    gca, ...
    'FontSize',11);


legend( ...
    [b(:);hActual], ...
    [componentNames {'Observed change'}], ...
    'Location','eastoutside');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '40_bvar_recent_episode_hd.png'), ...
    'Resolution',300);


%% ================================================================
% PART E
% FIGURE 2
% GROUPED POSTERIOR UNCERTAINTY
%% ================================================================

figure( ...
    'Color','w', ...
    'Position',[220 160 850 500]);


xgroup = ...
    [1 2];


groupMedian = [ ...
    CommodityRiskMedian ...
    YieldFXMedian];


lower70 = [ ...
    CommodityRisk70(1) ...
    YieldFX70(1)];


upper70 = [ ...
    CommodityRisk70(2) ...
    YieldFX70(2)];


lower95 = [ ...
    CommodityRisk95(1) ...
    YieldFX95(1)];


upper95 = [ ...
    CommodityRisk95(2) ...
    YieldFX95(2)];


%% 95% intervals first

errorbar( ...
    xgroup, ...
    groupMedian, ...
    groupMedian-lower95, ...
    upper95-groupMedian, ...
    'k', ...
    'LineStyle','none', ...
    'LineWidth',1.1, ...
    'CapSize',10);


hold on;


%% 70% intervals

errorbar( ...
    xgroup, ...
    groupMedian, ...
    groupMedian-lower70, ...
    upper70-groupMedian, ...
    'k', ...
    'LineStyle','none', ...
    'LineWidth',2.8, ...
    'CapSize',7);


%% Posterior medians

plot( ...
    xgroup, ...
    groupMedian, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',8);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


xlim([0.5 2.5]);


xticks(xgroup);


xticklabels( ...
    { ...
    'Commodity + risk', ...
    'Relative yield + other FX'} );


ylabel( ...
    'Contribution, log points');


title( ...
    'BVAR: Channels Behind the 2025Q4-2026Q2 Appreciation');


grid on;
box off;


set( ...
    gca, ...
    'FontSize',11);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '41_bvar_recent_episode_hd_uncertainty.png'), ...
    'Resolution',300);


%% ================================================================
% PART F
% EXPORT RESULTS
%% ================================================================

outputFile = ...
    fullfile( ...
        resultDir, ...
        'bvar_recent_episode_hd.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


%% Episode summary

EpisodeSummary = table( ...
    string(episodeName), ...
    D.quarter_start(i0), ...
    D.quarter_start(i1), ...
    ActualChange, ...
    PointError, ...
    maxAccountingError, ...
    'VariableNames', ...
    { ...
    'Episode', ...
    'PreviousQuarter', ...
    'EndQuarter', ...
    'Observed_RTWI_Change', ...
    'PointAccountingError', ...
    'MaximumPosteriorAccountingError'});


writetable( ...
    EpisodeSummary, ...
    outputFile, ...
    'Sheet','episode');


writetable( ...
    RecentBVAR, ...
    outputFile, ...
    'Sheet','individual');


writetable( ...
    RecentBVAR_Grouped, ...
    outputFile, ...
    'Sheet','grouped');


%% Save MATLAB results too

recent_bvar_hd = struct();


recent_bvar_hd.episodeName = ...
    episodeName;


recent_bvar_hd.i0 = ...
    i0;


recent_bvar_hd.i1 = ...
    i1;


recent_bvar_hd.ActualChange = ...
    ActualChange;


recent_bvar_hd.PointContrib = ...
    PointContrib;


recent_bvar_hd.EpisodeDraws = ...
    EpisodeDraws;


recent_bvar_hd.PosteriorMedian = ...
    PosteriorMedian;


recent_bvar_hd.Lower70 = ...
    Lower70;


recent_bvar_hd.Upper70 = ...
    Upper70;


recent_bvar_hd.Lower95 = ...
    Lower95;


recent_bvar_hd.Upper95 = ...
    Upper95;


recent_bvar_hd.RecentBVAR = ...
    RecentBVAR;


recent_bvar_hd.RecentBVAR_Grouped = ...
    RecentBVAR_Grouped;


save( ...
    fullfile( ...
        resultDir, ...
        'bvar_recent_episode_hd.mat'), ...
    'recent_bvar_hd', ...
    '-v7.3');


fprintf('\n');
fprintf('============================================================\n');
fprintf('BVAR RECENT-EPISODE HD COMPLETE\n');
fprintf('============================================================\n');

fprintf('Results saved to:\n%s\n',outputFile);


%% ================================================================
% LOCAL FUNCTION
%% ================================================================

function baseline = ...
    constructVARBaseline( ...
    phi, ...
    y, ...
    p)

% ================================================================
% Construct no-shock VAR baseline.
%
% Uses the same mean-backcasting convention used in our BVAR work.
%% ================================================================

    [T,N] = ...
        size(y);


    initialMean = ...
        mean(y,1);


    baseline_ext = [ ...
        repmat(initialMean,p,1); ...
        zeros(T,N)];


    for t = 1:T

        thisValue = ...
            phi(1,:);


        for lag = 1:p

            rows = ...
                2 + (lag-1)*N : ...
                1 + lag*N;


            thisValue = ...
                thisValue ...
                + baseline_ext(p+t-lag,:) ...
                * phi(rows,:);

        end


        baseline_ext(p+t,:) = ...
            thisValue;

    end


    baseline = ...
        baseline_ext(p+1:end,:);

end