%% ================================================================
%  AUSTRALIAN DOLLAR DRIVERS - HISTORICAL DECOMPOSITION
%
%  Baseline classical SVAR:
%
%    1. US real GDP gap
%    2. RBA commodity price index
%    3. VIX
%    4. Australian real GDP gap
%    5. Trimmed mean inflation
%    6. AU-US 2-year yield spread
%    7. Real TWI
%
%  Sample: 1995Q1-2026Q2
%  VAR lags: 2
%  Foreign block: first 3 variables
%
%  Identification:
%    Recursive Cholesky
%
%  Historical decomposition:
%    Uses Ben Wong's historical_decomposition.m
%
%  IMPORTANT:
%    Ben's function gives structural-shock contributions.
%    We separately construct the constant/initial-condition baseline
%    so that the historical decomposition exactly reconstructs y.
%
%% ================================================================

clear;
clc;
close all;


%% 1. PRELIMINARY

folder = fileparts(mfilename('fullpath'));

addpath(fullfile(folder,'_func'));


filePath = ...
    fullfile(folder,'data','data_collected.xlsx');


figDir = ...
    fullfile(folder,'figures');

if ~exist(figDir,'dir')
    mkdir(figDir);
end


resultDir = ...
    fullfile(folder,'results');

if ~exist(resultDir,'dir')
    mkdir(resultDir);
end


assert(exist('olsvar_soe','file') == 2, ...
    'olsvar_soe.m not found.');

assert(exist('historical_decomposition','file') == 2, ...
    'historical_decomposition.m not found.');


%% 2. IMPORT DATA

data = readtable( ...
    filePath, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


%% 3. DATE VARIABLES

dateVars = { ...
    'quarter_start', ...
    'quarter_end'};


for ii = 1:length(dateVars)

    v = dateVars{ii};

    if ~isdatetime(data.(v))

        if isnumeric(data.(v))

            data.(v) = datetime( ...
                data.(v), ...
                'ConvertFrom','excel');

        else

            data.(v) = datetime(data.(v));

        end

    end

end


%% 4. MAKE OTHER VARIABLES NUMERIC

varNames = ...
    data.Properties.VariableNames;


for jj = 3:width(data)

    v = varNames{jj};

    if ~isnumeric(data.(v))

        data.(v) = ...
            str2double(string(data.(v)));

    end

end


%% 5. YEAR / QUARTER LABELS

yr = ...
    year(data.quarter_start);

qtr = ...
    ceil(month(data.quarter_start)/3);


yearlab = ...
    yr + (qtr-1)/4;


quarterlab = ...
    string(yr) + "Q" + string(qtr);


%% 6. SAMPLE

sampleStart = ...
    datetime(1995,1,1);

sampleEnd = ...
    datetime(2026,4,1);


sample = ...
    data.quarter_start >= sampleStart & ...
    data.quarter_start <= sampleEnd;


D = ...
    data(sample,:);


yearlab_svar = ...
    yearlab(sample);

quarterlab_svar = ...
    quarterlab(sample);


T = ...
    height(D);


assert(T == 126, ...
    'Unexpected sample length.');


fprintf('\n============================================================\n');
fprintf('SVAR HISTORICAL DECOMPOSITION\n');
fprintf('============================================================\n');

fprintf('Sample: %s to %s\n', ...
    char(quarterlab_svar(1)), ...
    char(quarterlab_svar(end)));

fprintf('T = %d\n',T);


%% 7. CHECK REQUIRED VARIABLES

requiredVars = { ...
    'us_rgdp', ...
    'comm_price', ...
    'vix', ...
    'au_rgdp', ...
    'au_inf_trim', ...
    'au_us_2yr', ...
    'rtwi'};


for ii = 1:length(requiredVars)

    v = requiredVars{ii};

    assert( ...
        ismember(v,D.Properties.VariableNames), ...
        'Missing variable: %s',v);

    assert( ...
        all(isfinite(D.(v))), ...
        'Variable %s has missing observations.',v);

end


%% 8. TRANSFORM VARIABLES
%
% Identical to baseline SVAR.


log_us_gdp = ...
    100*log(D.us_rgdp);

log_comm = ...
    100*log(D.comm_price);

log_vix = ...
    100*log(D.vix);

log_au_gdp = ...
    100*log(D.au_rgdp);

trim_inf = ...
    D.au_inf_trim;

spread_2yr = ...
    D.au_us_2yr;

log_rtwi = ...
    100*log(D.rtwi);


%% 9. QUADRATIC GDP DETRENDING

tt = ...
    (1:T)';


Xtrend = [ ...
    ones(T,1) ...
    tt ...
    tt.^2];


% US GDP

b_us = ...
    Xtrend \ log_us_gdp;

trend_us = ...
    Xtrend*b_us;

us_gdp_gap = ...
    log_us_gdp - trend_us;


% Australian GDP

b_au = ...
    Xtrend \ log_au_gdp;

trend_au = ...
    Xtrend*b_au;

au_gdp_gap = ...
    log_au_gdp - trend_au;


%% 10. BASELINE VAR DATASET

y = [ ...
    us_gdp_gap ...
    log_comm ...
    log_vix ...
    au_gdp_gap ...
    trim_inf ...
    spread_2yr ...
    log_rtwi];


Variables = { ...
    'US Real GDP', ...
    'Commodity Prices', ...
    'VIX', ...
    'Australian Real GDP', ...
    'Trimmed Mean Inflation', ...
    'AU-US 2yr Spread', ...
    'Real TWI'};


N = ...
    size(y,2);


assert(N == 7);


%% 11. MODEL SETTINGS

p = 2;

n_foreign = 3;


shock_us = 1;
shock_comm = 2;
shock_vix = 3;
shock_augdp = 4;
shock_inf = 5;
shock_spread = 6;
shock_er = 7;


% No deterministic controls
d = ...
    zeros(T,0);


%% 12. ESTIMATE BASELINE SOE VAR

[phi,gamma,SIGMA,X,e] = ...
    olsvar_soe( ...
        y, ...
        p, ...
        d, ...
        n_foreign);


%% 13. STABILITY

Companion = [ ...
    phi(2:end,:)'; ...
    eye(N*(p-1)) zeros(N*(p-1),N)];


rootsVAR = ...
    eig(Companion);


maxRoot = ...
    max(abs(rootsVAR));


fprintf('\nMaximum VAR root: %.4f\n', ...
    maxRoot);


%% 14. CHOLESKY IDENTIFICATION

[B,cholFlag] = ...
    chol(SIGMA,'lower');


assert(cholFlag == 0, ...
    'SIGMA is not positive definite.');


%% 15. STRUCTURAL SHOCKS
%
% Reduced-form:
%
%     e_t = B * epsilon_t
%
% Therefore:
%
%     epsilon_t = B^{-1} e_t
%
% Use left division rather than inv(B).


structural_shocks = ...
    (B \ e')';


StructuralShockTable = ...
    array2table( ...
        structural_shocks, ...
        'VariableNames', ...
        matlab.lang.makeValidName(Variables));


StructuralShockTable = ...
    addvars( ...
        StructuralShockTable, ...
        D.quarter_start, ...
        quarterlab_svar, ...
        'Before',1, ...
        'NewVariableNames', ...
        {'Date','Quarter'});


%% 16. BEN'S HISTORICAL DECOMPOSITION
%
% HD is an N x 1 cell array.
%
% HD{ii}:
%
%     T x N
%
% Rows:
%     time
%
% Columns:
%     contribution of each structural shock
%
% Example:
%
% HD{7}(:,2)
%
% = commodity shock contribution to Real TWI.


HD = ...
    historical_decomposition( ...
        phi, ...
        e, ...
        B);


%% 17. CONSTRUCT BASELINE COMPONENT
%
% Ben's HD only contains structural-shock contributions.
%
% We reconstruct the path generated by:
%
%   - VAR constant
%   - deterministic variables, if any
%   - initial conditions
%
% with ALL structural shocks set equal to zero.
%
% Critically, this helper uses the same mean-backcasting convention
% as olsvar_soe.m.


baseline = ...
    constructVARBaseline( ...
        phi, ...
        gamma, ...
        d, ...
        y, ...
        p);


%% 18. EXACT ACCOUNTING CHECK - ALL VARIABLES

reconstructed = ...
    baseline;


for ii = 1:N

    reconstructed(:,ii) = ...
        baseline(:,ii) ...
        + sum(HD{ii},2);

end


accountingError = ...
    y - reconstructed;


maxAccountingError = ...
    max(abs(accountingError),[], 'all');


fprintf('\n============================================================\n');
fprintf('HISTORICAL DECOMPOSITION ACCOUNTING CHECK\n');
fprintf('============================================================\n');

fprintf('Maximum absolute reconstruction error: %.12g\n', ...
    maxAccountingError);


assert( ...
    maxAccountingError < 1e-8, ...
    'Historical decomposition does not reconstruct y exactly.');


fprintf('PASS: baseline + structural shocks reconstruct the data.\n');


%% 19. REAL TWI HISTORICAL DECOMPOSITION
%
% T x N:
%
% contribution of every identified structural shock
% to the level of the Real TWI.


HD_rtwi = ...
    HD{shock_er};


rtwi_baseline_log = ...
    baseline(:,shock_er);


rtwi_actual_log = ...
    y(:,shock_er);


rtwi_reconstructed_log = ...
    reconstructed(:,shock_er);


rtwi_total_shock_component = ...
    sum(HD_rtwi,2);


%% 20. RTWI ACCOUNTING CHECK

rtwiError = ...
    rtwi_actual_log ...
    - rtwi_baseline_log ...
    - rtwi_total_shock_component;


fprintf('\nMaximum Real TWI accounting error: %.12g\n', ...
    max(abs(rtwiError)));


%% 21. ARTICLE-ORIENTED SHOCK GROUPS
%
% Keep the three factors of interest separate:
%
%   Commodity prices
%   Global risk / VIX
%   Relative yields
%
% Group slower macro shocks for readability.
%
% The residual exchange-rate shock remains separate.


HD_global_activity = ...
    HD_rtwi(:,shock_us);


HD_commodity = ...
    HD_rtwi(:,shock_comm);


HD_vix = ...
    HD_rtwi(:,shock_vix);


HD_domestic_macro = ...
    HD_rtwi(:,shock_augdp) ...
    + HD_rtwi(:,shock_inf);


HD_spread = ...
    HD_rtwi(:,shock_spread);


HD_residual_fx = ...
    HD_rtwi(:,shock_er);


HD_grouped = [ ...
    HD_global_activity ...
    HD_commodity ...
    HD_vix ...
    HD_domestic_macro ...
    HD_spread ...
    HD_residual_fx];


groupLabels = { ...
    'Global activity', ...
    'Commodity prices', ...
    'Global risk (VIX)', ...
    'Domestic macro', ...
    'Relative yields', ...
    'Residual FX'};


%% 22. GROUPING ACCOUNTING CHECK

groupingError = ...
    rtwi_total_shock_component ...
    - sum(HD_grouped,2);


assert( ...
    max(abs(groupingError)) < 1e-10);


%% 23. ORDERING-ROBUST PAIR GROUPS
%
% Earlier robustness work showed that swapping recursive order within
% these pairs mainly reallocates their contributions internally.
%
% These grouped series may therefore be useful in the article as
% robustness summaries.


HD_commodity_risk = ...
    HD_commodity ...
    + HD_vix;


HD_yield_fx = ...
    HD_spread ...
    + HD_residual_fx;


%% 24. CONVERT BASELINE / RECONSTRUCTION BACK TO RTWI INDEX
%
% Additivity is exact in 100*log units.
%
% The index versions below are useful only for displaying the implied
% no-shock baseline and checking reconstruction.


rtwi_actual_index = ...
    D.rtwi;


rtwi_baseline_index = ...
    exp(rtwi_baseline_log/100);


rtwi_reconstructed_index = ...
    exp(rtwi_reconstructed_log/100);


maxIndexError = ...
    max(abs( ...
        rtwi_actual_index ...
        - rtwi_reconstructed_index));


fprintf('Maximum reconstructed RTWI-index error: %.12g\n', ...
    maxIndexError);


%% 25. FIGURE 1 - ACTUAL RTWI AND NO-SHOCK BASELINE
%
% This gives an intuitive interpretation of what the decomposition is
% measuring.
%
% The gap between the two lines is exactly the sum of structural
% shock contributions.


figure( ...
    'Color','w', ...
    'Position',[100 120 1100 500]);


plot( ...
    yearlab_svar, ...
    rtwi_actual_index, ...
    '-k', ...
    'LineWidth',2);

hold on;


plot( ...
    yearlab_svar, ...
    rtwi_baseline_index, ...
    '--k', ...
    'LineWidth',1.5);


grid on;
box off;


xlabel('Year');

ylabel('Real TWI');


title( ...
    'Australian Dollar Real TWI: Actual and No-Shock Baseline');


legend( ...
    'Actual Real TWI', ...
    'Baseline: constant and initial conditions', ...
    'Location','best');


xlim([yearlab_svar(1) yearlab_svar(end)]);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '22_svar_hd_actual_vs_baseline.png'), ...
    'Resolution',300);


%% 26. FIGURE 2 - FULL-SAMPLE HISTORICAL DECOMPOSITION
%
% Contributions are in log points.
%
% Positive contribution:
%     pushes the Real TWI above the model baseline
%
% Negative contribution:
%     pushes the Real TWI below the model baseline


figure( ...
    'Color','w', ...
    'Position',[70 100 1400 650]);


b = bar( ...
    yearlab_svar, ...
    HD_grouped, ...
    'stacked', ...
    'BarWidth',1);


hold on;


hTotal = plot( ...
    yearlab_svar, ...
    rtwi_total_shock_component, ...
    '-k', ...
    'LineWidth',2);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xlabel('Year');

ylabel('Contribution to Real TWI, log points');


title( ...
    'What Has Driven the Australian Dollar?');


legend( ...
    [b(:); hTotal], ...
    [groupLabels {'Actual minus baseline'}], ...
    'Location','eastoutside');


xlim([yearlab_svar(1) yearlab_svar(end)]);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '23_svar_hd_rtwi_full_sample.png'), ...
    'Resolution',300);


%% 27. FIGURE 3 - POST-2007 HISTORICAL DECOMPOSITION
%
% A more article-friendly view of the GFC, commodity boom,
% post-boom depreciation, COVID and recent period.


focusStart = ...
    datetime(2007,1,1);


focus = ...
    D.quarter_start >= focusStart;


figure( ...
    'Color','w', ...
    'Position',[70 100 1400 650]);


b = bar( ...
    yearlab_svar(focus), ...
    HD_grouped(focus,:), ...
    'stacked', ...
    'BarWidth',1);


hold on;


hTotal = plot( ...
    yearlab_svar(focus), ...
    rtwi_total_shock_component(focus), ...
    '-k', ...
    'LineWidth',2);

yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xlabel('Year');

ylabel('Contribution to Real TWI, log points');


title( ...
    'Drivers of the Australian Dollar Since 2007');


legend( ...
    [b(:); hTotal], ...
    [groupLabels {'Actual minus baseline'}], ...
    'Location','eastoutside');


xlim([ ...
    yearlab_svar(find(focus,1,'first')) ...
    yearlab_svar(end)]);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '24_svar_hd_rtwi_since_2007.png'), ...
    'Resolution',300);


%% 28. SELECTED HISTORICAL EPISODES
%
% The historical decomposition at a point in time reflects the
% accumulated effect of past shocks.
%
% For article discussion of an episode, it is often more intuitive to
% ask:
%
%     "Which shocks contributed to the CHANGE in the TWI over this
%      episode?"
%
% We therefore calculate the change in each historical-decomposition
% component from the quarter immediately before the episode to the
% episode end.
%
% These dates are deliberately easy to edit.


episodeNames = { ...
    'GFC', ...
    'Commodity-boom appreciation', ...
    'Post-boom depreciation', ...
    'COVID shock', ...
    'COVID rebound', ...
    'Recent period'};


episodeStart = [ ...
    datetime(2008,7,1); ...
    datetime(2009,7,1); ...
    datetime(2013,1,1); ...
    datetime(2020,1,1); ...
    datetime(2020,4,1); ...
    datetime(2022,1,1)];


episodeEnd = [ ...
    datetime(2009,4,1); ...
    datetime(2011,4,1); ...
    datetime(2015,7,1); ...
    datetime(2020,1,1); ...
    datetime(2021,4,1); ...
    datetime(2026,4,1)];


nEpisodes = ...
    length(episodeNames);


episodeActualChange = ...
    nan(nEpisodes,1);


episodeBaselineChange = ...
    nan(nEpisodes,1);


episodeShockChanges = ...
    nan(nEpisodes,size(HD_grouped,2));


for ee = 1:nEpisodes

    % Quarter immediately BEFORE episode start
    i0 = find( ...
        D.quarter_start < episodeStart(ee), ...
        1, ...
        'last');


    % Episode end
    i1 = find( ...
        D.quarter_start <= episodeEnd(ee), ...
        1, ...
        'last');


    if isempty(i0) || isempty(i1)

        error( ...
            'Episode %s lies outside the model sample.', ...
            episodeNames{ee});

    end


    episodeActualChange(ee) = ...
        rtwi_actual_log(i1) ...
        - rtwi_actual_log(i0);


    episodeBaselineChange(ee) = ...
        rtwi_baseline_log(i1) ...
        - rtwi_baseline_log(i0);


    episodeShockChanges(ee,:) = ...
        HD_grouped(i1,:) ...
        - HD_grouped(i0,:);

end


%% 29. EPISODE ACCOUNTING CHECK

episodeReconstructedChange = ...
    episodeBaselineChange ...
    + sum(episodeShockChanges,2);


episodeError = ...
    episodeActualChange ...
    - episodeReconstructedChange;


assert( ...
    max(abs(episodeError)) < 1e-8);


%% 30. EPISODE TABLE

EpisodeTable = table( ...
    string(episodeNames(:)), ...
    episodeStart, ...
    episodeEnd, ...
    episodeActualChange, ...
    episodeBaselineChange, ...
    episodeShockChanges(:,1), ...
    episodeShockChanges(:,2), ...
    episodeShockChanges(:,3), ...
    episodeShockChanges(:,4), ...
    episodeShockChanges(:,5), ...
    episodeShockChanges(:,6), ...
    episodeError, ...
    'VariableNames', ...
    { ...
    'Episode', ...
    'Start', ...
    'End', ...
    'Actual_RTWI_Change', ...
    'Baseline_Dynamics', ...
    'Global_Activity', ...
    'Commodity_Prices', ...
    'VIX', ...
    'Domestic_Macro', ...
    'Relative_Yields', ...
    'Residual_FX', ...
    'Accounting_Error'});


fprintf('\n');
fprintf('============================================================\n');
fprintf('SELECTED EPISODE CONTRIBUTIONS\n');
fprintf('============================================================\n');

disp(EpisodeTable);


%% 31. FIGURE 4 - WHAT DROVE EACH EPISODE?
%
% Includes baseline dynamics because we want the bars to reconstruct
% the observed RTWI change exactly.


episodeComponents = [ ...
    episodeBaselineChange ...
    episodeShockChanges];


episodeComponentLabels = [ ...
    {'Baseline dynamics'} ...
    groupLabels];


figure( ...
    'Color','w', ...
    'Position',[90 100 1200 600]);


b = bar( ...
    1:nEpisodes, ...
    episodeComponents, ...
    'stacked');


hold on;


hObserved = plot( ...
    1:nEpisodes, ...
    episodeActualChange, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',7);

yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(1:nEpisodes);

xticklabels(episodeNames);

xtickangle(20);


ylabel('Contribution to RTWI change, log points');


title( ...
    'What Drove Major Australian Dollar Episodes?');


legend( ...
    [b(:); hObserved], ...
    [episodeComponentLabels {'Observed change'}], ...
    'Location','eastoutside');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '25_svar_hd_selected_episodes.png'), ...
    'Resolution',300);


%% 32. COUNTERFACTUAL RTWI PATHS
%
% Remove one shock at a time from the historical path.
%
% These are useful later if we want statements such as:
%
% "What would the Real TWI have looked like without commodity shocks?"


log_rtwi_no_commodity = ...
    rtwi_actual_log ...
    - HD_commodity;


log_rtwi_no_vix = ...
    rtwi_actual_log ...
    - HD_vix;


log_rtwi_no_spread = ...
    rtwi_actual_log ...
    - HD_spread;


log_rtwi_no_residual_fx = ...
    rtwi_actual_log ...
    - HD_residual_fx;


rtwi_no_commodity = ...
    exp(log_rtwi_no_commodity/100);


rtwi_no_vix = ...
    exp(log_rtwi_no_vix/100);


rtwi_no_spread = ...
    exp(log_rtwi_no_spread/100);


rtwi_no_residual_fx = ...
    exp(log_rtwi_no_residual_fx/100);


%% 33. FULL HISTORICAL-DECOMPOSITION TABLE

HD_Table = table( ...
    D.quarter_start, ...
    quarterlab_svar, ...
    rtwi_actual_index, ...
    rtwi_actual_log, ...
    rtwi_baseline_index, ...
    rtwi_baseline_log, ...
    rtwi_total_shock_component, ...
    HD_global_activity, ...
    HD_commodity, ...
    HD_vix, ...
    HD_domestic_macro, ...
    HD_spread, ...
    HD_residual_fx, ...
    HD_commodity_risk, ...
    HD_yield_fx, ...
    rtwi_reconstructed_log, ...
    rtwiError, ...
    'VariableNames', ...
    { ...
    'Date', ...
    'Quarter', ...
    'Actual_RTWI_Index', ...
    'Actual_RTWI_Log', ...
    'Baseline_RTWI_Index', ...
    'Baseline_RTWI_Log', ...
    'Total_Shock_Component', ...
    'Global_Activity', ...
    'Commodity_Prices', ...
    'VIX', ...
    'Domestic_Macro', ...
    'Relative_Yields', ...
    'Residual_FX', ...
    'CommodityPlusVIX', ...
    'YieldPlusResidualFX', ...
    'Reconstructed_RTWI_Log', ...
    'Accounting_Error'});


%% 34. COUNTERFACTUAL TABLE

CounterfactualTable = table( ...
    D.quarter_start, ...
    quarterlab_svar, ...
    rtwi_actual_index, ...
    rtwi_no_commodity, ...
    rtwi_no_vix, ...
    rtwi_no_spread, ...
    rtwi_no_residual_fx, ...
    'VariableNames', ...
    { ...
    'Date', ...
    'Quarter', ...
    'Actual_RTWI', ...
    'Without_Commodity_Shocks', ...
    'Without_VIX_Shocks', ...
    'Without_RelativeYield_Shocks', ...
    'Without_ResidualFX_Shocks'});


%% 35. ACCOUNTING SUMMARY

AccountingSummary = table( ...
    maxAccountingError, ...
    max(abs(rtwiError)), ...
    maxIndexError, ...
    maxRoot, ...
    'VariableNames', ...
    { ...
    'Max_AllVariable_Error', ...
    'Max_RTWI_Log_Error', ...
    'Max_RTWI_Index_Error', ...
    'Maximum_VAR_Root'});


disp(' ');
disp(AccountingSummary);


%% 36. EXPORT TO EXCEL

outputFile = ...
    fullfile( ...
        resultDir, ...
        'svar_historical_decomposition.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    HD_Table, ...
    outputFile, ...
    'Sheet','RTWI_HD');


writetable( ...
    EpisodeTable, ...
    outputFile, ...
    'Sheet','episodes');


writetable( ...
    CounterfactualTable, ...
    outputFile, ...
    'Sheet','counterfactuals');


writetable( ...
    StructuralShockTable, ...
    outputFile, ...
    'Sheet','structural_shocks');


writetable( ...
    AccountingSummary, ...
    outputFile, ...
    'Sheet','accounting_check');


%% 37. SAVE MATLAB RESULTS

hd_results = struct();


hd_results.Variables = ...
    Variables;


hd_results.phi = ...
    phi;

hd_results.gamma = ...
    gamma;

hd_results.SIGMA = ...
    SIGMA;

hd_results.B = ...
    B;

hd_results.e = ...
    e;

hd_results.structural_shocks = ...
    structural_shocks;


hd_results.HD = ...
    HD;

hd_results.baseline = ...
    baseline;

hd_results.reconstructed = ...
    reconstructed;


hd_results.HD_rtwi = ...
    HD_rtwi;

hd_results.HD_grouped = ...
    HD_grouped;

hd_results.groupLabels = ...
    groupLabels;


hd_results.rtwi_actual_log = ...
    rtwi_actual_log;

hd_results.rtwi_baseline_log = ...
    rtwi_baseline_log;

hd_results.rtwi_total_shock_component = ...
    rtwi_total_shock_component;


hd_results.EpisodeTable = ...
    EpisodeTable;

hd_results.CounterfactualTable = ...
    CounterfactualTable;

hd_results.AccountingSummary = ...
    AccountingSummary;


save( ...
    fullfile( ...
        resultDir, ...
        'svar_historical_decomposition.mat'), ...
    'hd_results', ...
    '-v7.3');


%% 38. FINAL SUMMARY

fprintf('\n============================================================\n');
fprintf('HISTORICAL DECOMPOSITION COMPLETE\n');
fprintf('============================================================\n');


fprintf('Maximum accounting error: %.12g\n', ...
    maxAccountingError);


fprintf('Maximum VAR root: %.4f\n', ...
    maxRoot);


fprintf('\nResults workbook:\n%s\n', ...
    outputFile);


fprintf('\nMATLAB results:\n%s\n', ...
    fullfile( ...
        resultDir, ...
        'svar_historical_decomposition.mat'));


%% ================================================================
% LOCAL FUNCTION
%% ================================================================

function baseline = constructVARBaseline( ...
    phi, ...
    gamma, ...
    D, ...
    y, ...
    p)

% ================================================================
% CONSTRUCTVARBASELINE
%
% Reconstructs the VAR path generated by:
%
%   - intercept
%   - deterministic/exogenous controls
%   - initial conditions
%
% with all reduced-form / structural shocks set to zero.
%
% This function deliberately mirrors the mean-backcasting convention
% used in olsvar_soe.m:
%
%   the p pre-sample observations are set equal to mean(y).
%
% INPUTS
%
% phi:
%   (1+p*N) x N
%
% gamma:
%   q x N
%
% D:
%   T x q
%
% y:
%   T x N actual VAR dataset
%
% p:
%   lag order
%
% OUTPUT
%
% baseline:
%   T x N
%
% ================================================================


    [T,N] = ...
        size(y);


    if isempty(D)

        D = ...
            zeros(T,0);

    end


    if isempty(gamma)

        gamma = ...
            zeros(size(D,2),N);

    end


    %% SAME BACKCAST AS olsvar_soe.m

    initialMean = ...
        mean(y,1);


    baseline_ext = [ ...
        repmat(initialMean,p,1); ...
        zeros(T,N)];


    %% RECURSION

    for t = 1:T


        % Intercept

        thisValue = ...
            phi(1,:);


        % Deterministic controls

        if size(D,2) > 0

            thisValue = ...
                thisValue ...
                + D(t,:)*gamma;

        end


        % VAR lags

        for lag = 1:p

            rows = ...
                2 + (lag-1)*N : ...
                1 + lag*N;


            thisValue = ...
                thisValue ...
                + baseline_ext(p+t-lag,:) ...
                * phi(rows,:);

        end


        baseline_ext(p+t,:) = ...
            thisValue;

    end


    baseline = ...
        baseline_ext(p+1:end,:);

end