%% ================================================================
%  AUSTRALIAN DOLLAR DRIVERS - SVAR BOOTSTRAP FOR ESSA ARTICLE
%
%  BASELINE MODEL A
%
%  FOREIGN BLOCK
%    1. US real GDP gap
%    2. RBA commodity price index (SDR)
%    3. VIX
%
%  DOMESTIC BLOCK
%    4. Australian real GDP gap
%    5. Australian trimmed mean inflation
%    6. AU-US 2-year yield spread
%    7. Australian real TWI
%
%  Sample: 1995Q1-2026Q2
%  VAR lags: 2
%
%  Identification:
%    Recursive Cholesky
%
%  Bootstrap:
%    Kilian (1998) bootstrap-after-bootstrap
%
%  ARTICLE PRESENTATION:
%    - 70% central interval
%    - 95% central interval
%    - shaded confidence regions
%
%  UNCERTAINTY DIAGNOSTICS:
%    - bootstrap root distribution
%    - comfortably stable / near-unit / unstable draw groups
%    - all-draw vs stable-only confidence intervals
%    - band-width diagnostics by horizon
%
%  IMPORTANT:
%    All bootstrap draws remain in the BASELINE intervals.
%    Stable-only results are diagnostics, not the preferred inference.
%% ================================================================

clear;
clc;
close all;


%% 1. PRELIMINARY

folder = fileparts(mfilename('fullpath'));

addpath(fullfile(folder,'_func'));


filePath = ...
    fullfile(folder,'data','data_collected.xlsx');


figDir = ...
    fullfile(folder,'figures');

if ~exist(figDir,'dir')
    mkdir(figDir);
end


resultDir = ...
    fullfile(folder,'results');

if ~exist(resultDir,'dir')
    mkdir(resultDir);
end


assert(exist('olsvar_soe','file') == 2, ...
    'olsvar_soe.m not found.');

assert(exist('calculate_IRF_FEVD','file') == 2, ...
    'calculate_IRF_FEVD.m not found.');

assert(exist('bootstrap_after_bootstrap_soe','file') == 2, ...
    'bootstrap_after_bootstrap_soe.m not found.');


%% 2. BOOTSTRAP REUSE OPTION
%
% You have already run the 1000 x 1000 bootstrap.
%
% TRUE:
%   load the bootstrap draws saved by the previous svar_bootstrap.m
%
% FALSE:
%   rerun the Kilian bootstrap from scratch

reuse_previous_bootstrap = true;


previousBootstrapFile = ...
    fullfile( ...
        resultDir, ...
        'svar_bootstrap.mat');


%% 3. IMPORT DATA

data = readtable( ...
    filePath, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


%% 4. DATE VARIABLES

dateVars = { ...
    'quarter_start', ...
    'quarter_end'};


for ii = 1:length(dateVars)

    v = dateVars{ii};

    if ~isdatetime(data.(v))

        if isnumeric(data.(v))

            data.(v) = datetime( ...
                data.(v), ...
                'ConvertFrom','excel');

        else

            data.(v) = ...
                datetime(data.(v));

        end

    end

end


%% 5. MAKE OTHER VARIABLES NUMERIC

varNames = ...
    data.Properties.VariableNames;


for jj = 3:width(data)

    v = varNames{jj};

    if ~isnumeric(data.(v))

        data.(v) = ...
            str2double(string(data.(v)));

    end

end


%% 6. YEARLAB

yr = ...
    year(data.quarter_start);

qtr = ...
    ceil(month(data.quarter_start)/3);


yearlab = ...
    yr + (qtr-1)/4;


quarterlab = ...
    string(yr) + "Q" + string(qtr);


%% 7. SAMPLE

sampleStart = ...
    datetime(1995,1,1);

sampleEnd = ...
    datetime(2026,4,1);


sample = ...
    data.quarter_start >= sampleStart & ...
    data.quarter_start <= sampleEnd;


D = ...
    data(sample,:);


yearlab_svar = ...
    yearlab(sample);

quarterlab_svar = ...
    quarterlab(sample);


T = ...
    height(D);


assert(T == 126, ...
    'Unexpected sample size.');


fprintf('\n============================================================\n');
fprintf('SVAR BOOTSTRAP - ESSA ARTICLE VERSION\n');
fprintf('============================================================\n');

fprintf('Sample: %s to %s\n', ...
    char(quarterlab_svar(1)), ...
    char(quarterlab_svar(end)));

fprintf('Observations: %d\n',T);


%% 8. REQUIRED VARIABLES

requiredVars = { ...
    'us_rgdp', ...
    'comm_price', ...
    'vix', ...
    'au_rgdp', ...
    'au_inf_trim', ...
    'au_us_2yr', ...
    'rtwi'};


for ii = 1:length(requiredVars)

    v = requiredVars{ii};

    assert( ...
        ismember(v,D.Properties.VariableNames), ...
        'Missing variable: %s',v);

    assert( ...
        all(isfinite(D.(v))), ...
        'Variable %s contains missing observations.',v);

end


%% 9. TRANSFORM VARIABLES

log_us_gdp = ...
    100*log(D.us_rgdp);

log_comm = ...
    100*log(D.comm_price);

log_vix = ...
    100*log(D.vix);

log_au_gdp = ...
    100*log(D.au_rgdp);

trim_inf = ...
    D.au_inf_trim;

spread_2yr = ...
    D.au_us_2yr;

log_rtwi = ...
    100*log(D.rtwi);


%% 10. QUADRATIC GDP DETRENDING

tt = ...
    (1:T)';


Xtrend = [ ...
    ones(T,1) ...
    tt ...
    tt.^2];


% US GDP

b_us = ...
    Xtrend \ log_us_gdp;

trend_us = ...
    Xtrend*b_us;

us_gdp_gap = ...
    log_us_gdp - trend_us;


% Australian GDP

b_au = ...
    Xtrend \ log_au_gdp;

trend_au = ...
    Xtrend*b_au;

au_gdp_gap = ...
    log_au_gdp - trend_au;


%% 11. BASELINE DATASET

y = [ ...
    us_gdp_gap ...
    log_comm ...
    log_vix ...
    au_gdp_gap ...
    trim_inf ...
    spread_2yr ...
    log_rtwi];


Variables = { ...
    'US Real GDP', ...
    'Commodity Prices', ...
    'VIX', ...
    'Australian Real GDP', ...
    'Trimmed Mean Inflation', ...
    'AU-US 2yr Spread', ...
    'Real TWI'};


N = ...
    size(y,2);


assert(N == 7);
assert(~any(isnan(y(:))));
assert(~any(isinf(y(:))));


%% 12. MODEL SETTINGS

p = 2;

n_foreign = 3;


shock_us = 1;
shock_comm = 2;
shock_vix = 3;
shock_augdp = 4;
shock_inf = 5;
shock_spread = 6;
shock_er = 7;


% Estimation horizons
hor = 24;
hor_fevd = 40;


% Article plotting horizons
%
% Keep estimation longer than what we emphasise visually.

plot_hor_irf = 16;

plot_hor_fevd = 20;


% Normalised presentation shocks

size_comm_shock = 10;       % +10 log points
size_vix_shock = 10;        % +10 log points
size_spread_shock = 1;      % +1 ppt = 100 bp


%% 13. CONFIDENCE INTERVAL SETTINGS
%
% Central 70%:
%   15th to 85th percentile
%
% Central 95%:
%   2.5th to 97.5th percentile

CI70_quantiles = ...
    [0.15 0.85];

CI95_quantiles = ...
    [0.025 0.975];


%% 14. BOOTSTRAP SETTINGS

nboot1 = 1000;

nboot2 = 1000;

rng_seed = 12345;


%% 15. NO DETERMINISTIC CONTROLS

d = ...
    zeros(T,0);


%% 16. ESTIMATE POINT VAR

[phi,gamma,SIGMA,X,e] = ...
    olsvar_soe( ...
        y, ...
        p, ...
        d, ...
        n_foreign);


%% 17. POINT VAR STABILITY

Companion_original = [ ...
    phi(2:end,:)'; ...
    eye(N*(p-1)) zeros(N*(p-1),N)];


root_original = ...
    max(abs(eig(Companion_original)));


fprintf('\nOriginal VAR maximum root: %.4f\n', ...
    root_original);


%% 18. CHOLESKY IDENTIFICATION

[~,cholFlag] = ...
    chol(SIGMA);


assert(cholFlag == 0, ...
    'Point-estimate SIGMA is not positive definite.');


B = ...
    chol(SIGMA,'lower');


%% 19. POINT-ESTIMATE HEADLINE IRFs

resp_comm = ...
    normalizedShockResponse( ...
        phi, ...
        B, ...
        shock_comm, ...
        size_comm_shock, ...
        hor);


resp_vix = ...
    normalizedShockResponse( ...
        phi, ...
        B, ...
        shock_vix, ...
        size_vix_shock, ...
        hor);


resp_spread = ...
    normalizedShockResponse( ...
        phi, ...
        B, ...
        shock_spread, ...
        size_spread_shock, ...
        hor);


rtwi_comm = ...
    resp_comm(shock_er,:)';

rtwi_vix = ...
    resp_vix(shock_er,:)';

rtwi_spread = ...
    resp_spread(shock_er,:)';


%% 20. POINT-ESTIMATE FEVD

[~,FEVD_point] = ...
    calculate_IRF_FEVD( ...
        phi, ...
        B, ...
        hor_fevd, ...
        'FEVD');


rtwi_FEVD_point = ...
    squeeze( ...
        FEVD_point( ...
            shock_er, ...
            :, ...
            :));


%% 21. LOAD EXISTING BOOTSTRAP OR RERUN

if reuse_previous_bootstrap && isfile(previousBootstrapFile)

    fprintf('\n============================================================\n');
    fprintf('LOADING PREVIOUS BOOTSTRAP DRAWS\n');
    fprintf('============================================================\n');


    S = ...
        load( ...
            previousBootstrapFile, ...
            'results_bootstrap');


    R = ...
        S.results_bootstrap;


    % Basic compatibility checks

    assert(R.p == p, ...
        'Saved bootstrap uses a different lag order.');

    assert(R.n_foreign == n_foreign, ...
        'Saved bootstrap uses a different foreign block.');


    nboot1 = ...
        R.nboot1;

    nboot2 = ...
        R.nboot2;

    rng_seed = ...
        R.rng_seed;


    phi_bias_corrected = ...
        R.phi_bias_corrected;

    bias = ...
        R.bias;


    rtwi_comm_boot = ...
        R.rtwi_comm_boot;

    rtwi_vix_boot = ...
        R.rtwi_vix_boot;

    rtwi_spread_boot = ...
        R.rtwi_spread_boot;


    rtwi_FEVD_boot = ...
        R.rtwi_FEVD_boot;


    max_root_boot = ...
        R.max_root_boot;


    unstable_boot = ...
        R.unstable_boot;


    clear S R


    fprintf('Loaded %d second-stage bootstrap draws.\n', ...
        nboot2);


else

    %% ------------------------------------------------------------
    % RUN KILIAN BOOTSTRAP
    %% ------------------------------------------------------------

    fprintf('\n============================================================\n');
    fprintf('RUNNING KILIAN BOOTSTRAP-AFTER-BOOTSTRAP\n');
    fprintf('============================================================\n');


    rng(rng_seed);


    [phi_boot, ...
     SIGMA_boot, ...
     phi_bias_corrected, ...
     bias] = ...
        bootstrap_after_bootstrap_soe( ...
            phi, ...
            gamma, ...
            X, ...
            e, ...
            d, ...
            p, ...
            n_foreign, ...
            nboot1, ...
            nboot2);


    %% STORAGE

    rtwi_comm_boot = ...
        NaN(hor+1,nboot2);

    rtwi_vix_boot = ...
        NaN(hor+1,nboot2);

    rtwi_spread_boot = ...
        NaN(hor+1,nboot2);


    rtwi_FEVD_boot = ...
        NaN(N,hor_fevd+1,nboot2);


    max_root_boot = ...
        NaN(nboot2,1);

    unstable_boot = ...
        false(nboot2,1);


    %% BOOTSTRAP RESPONSES

    for jj = 1:nboot2

        Companion_boot = [ ...
            phi_boot(2:end,:,jj)'; ...
            eye(N*(p-1)) zeros(N*(p-1),N)];


        max_root_boot(jj) = ...
            max(abs(eig(Companion_boot)));


        unstable_boot(jj) = ...
            max_root_boot(jj) >= 1;


        [B_boot,cholFlag] = ...
            chol( ...
                SIGMA_boot(:,:,jj), ...
                'lower');


        if cholFlag ~= 0

            error( ...
                'Bootstrap SIGMA not positive definite at draw %d.', ...
                jj);

        end


        % Commodity

        resp = ...
            normalizedShockResponse( ...
                phi_boot(:,:,jj), ...
                B_boot, ...
                shock_comm, ...
                size_comm_shock, ...
                hor);


        rtwi_comm_boot(:,jj) = ...
            resp(shock_er,:)';


        % VIX

        resp = ...
            normalizedShockResponse( ...
                phi_boot(:,:,jj), ...
                B_boot, ...
                shock_vix, ...
                size_vix_shock, ...
                hor);


        rtwi_vix_boot(:,jj) = ...
            resp(shock_er,:)';


        % Spread

        resp = ...
            normalizedShockResponse( ...
                phi_boot(:,:,jj), ...
                B_boot, ...
                shock_spread, ...
                size_spread_shock, ...
                hor);


        rtwi_spread_boot(:,jj) = ...
            resp(shock_er,:)';


        % FEVD

        [~,FEVD_j] = ...
            calculate_IRF_FEVD( ...
                phi_boot(:,:,jj), ...
                B_boot, ...
                hor_fevd, ...
                'FEVD');


        rtwi_FEVD_boot(:,:,jj) = ...
            squeeze( ...
                FEVD_j( ...
                    shock_er, ...
                    :, ...
                    :));


        if mod(jj,100) == 0

            fprintf('Completed draw %d of %d\n', ...
                jj,nboot2);

        end

    end

end


%% 22. BIAS-CORRECTED ROOT

Companion_bc = [ ...
    phi_bias_corrected(2:end,:)'; ...
    eye(N*(p-1)) zeros(N*(p-1),N)];


root_bc = ...
    max(abs(eig(Companion_bc)));


%% 23. EFFECTIVE BIAS-CORRECTION SHRINKAGE
%
% bootstrap_after_bootstrap_soe internally uses:
%
% phi_bc = phi + delta*bias
%
% We can infer delta from the returned matrices.

validBias = ...
    abs(bias) > 1e-10;


delta_values = ...
    ( ...
    phi_bias_corrected(validBias) ...
    - phi(validBias) ...
    ) ./ ...
    bias(validBias);


delta_values = ...
    delta_values(isfinite(delta_values));


delta_effective = ...
    median(delta_values);


fprintf('\n============================================================\n');
fprintf('BIAS-CORRECTION DIAGNOSTICS\n');
fprintf('============================================================\n');

fprintf('Original VAR root:          %.4f\n', ...
    root_original);

fprintf('Bias-corrected VAR root:    %.4f\n', ...
    root_bc);

fprintf('Effective shrinkage delta:  %.4f\n', ...
    delta_effective);

fprintf('Maximum absolute raw bias:  %.4f\n', ...
    max(abs(bias(:))));


%% 24. CLASSIFY BOOTSTRAP ROOTS
%
% These groups are diagnostic only.
%
% Comfortable:
%   root < 0.99
%
% Near-unit but stable:
%   0.99 <= root < 1
%
% Unstable:
%   root >= 1

comfortableMask = ...
    max_root_boot < 0.99;


nearUnitMask = ...
    max_root_boot >= 0.99 & ...
    max_root_boot < 1;


unstableMask = ...
    max_root_boot >= 1;


stableMask = ...
    max_root_boot < 1;


nComfortable = ...
    sum(comfortableMask);

nNearUnit = ...
    sum(nearUnitMask);

nUnstable = ...
    sum(unstableMask);

nStable = ...
    sum(stableMask);


fprintf('\n============================================================\n');
fprintf('BOOTSTRAP ROOT GROUPS\n');
fprintf('============================================================\n');

fprintf('Comfortably stable (<0.99):     %d (%.1f%%)\n', ...
    nComfortable, ...
    100*nComfortable/nboot2);

fprintf('Near-unit stable [0.99,1):      %d (%.1f%%)\n', ...
    nNearUnit, ...
    100*nNearUnit/nboot2);

fprintf('Unstable (>=1):                 %d (%.1f%%)\n', ...
    nUnstable, ...
    100*nUnstable/nboot2);


%% 25. ROOT QUANTILES

rootProbs = ...
    [0.50 0.75 0.90 0.95 0.975 0.99];


rootQuantiles = ...
    quantile( ...
        max_root_boot, ...
        rootProbs);


RootQuantileTable = table( ...
    rootProbs(:), ...
    rootQuantiles(:), ...
    'VariableNames', ...
    {'Probability','MaxRoot'});


disp(' ');
disp(RootQuantileTable);


%% 26. BASELINE 70% AND 95% IRF INTERVALS
%
% IMPORTANT:
% These use ALL bootstrap draws.

comm_CI70 = ...
    quantile( ...
        rtwi_comm_boot, ...
        CI70_quantiles, ...
        2);


comm_CI95 = ...
    quantile( ...
        rtwi_comm_boot, ...
        CI95_quantiles, ...
        2);


vix_CI70 = ...
    quantile( ...
        rtwi_vix_boot, ...
        CI70_quantiles, ...
        2);


vix_CI95 = ...
    quantile( ...
        rtwi_vix_boot, ...
        CI95_quantiles, ...
        2);


spread_CI70 = ...
    quantile( ...
        rtwi_spread_boot, ...
        CI70_quantiles, ...
        2);


spread_CI95 = ...
    quantile( ...
        rtwi_spread_boot, ...
        CI95_quantiles, ...
        2);


%% 27. STABLE-ONLY DIAGNOSTIC IRF INTERVALS
%
% NOT the baseline inference.
%
% This tells us whether unstable draws are driving the wide bands.

comm_CI95_stable = ...
    quantile( ...
        rtwi_comm_boot(:,stableMask), ...
        CI95_quantiles, ...
        2);


vix_CI95_stable = ...
    quantile( ...
        rtwi_vix_boot(:,stableMask), ...
        CI95_quantiles, ...
        2);


spread_CI95_stable = ...
    quantile( ...
        rtwi_spread_boot(:,stableMask), ...
        CI95_quantiles, ...
        2);


%% 28. ARTICLE IRF FIGURE - SHADED 70% AND 95%

h = ...
    (0:hor)';


hPlot = ...
    h(1:plot_hor_irf+1);


figure( ...
    'Color','w', ...
    'Position',[70 100 1250 390]);


tiledlayout( ...
    1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% COMMODITY

nexttile;

[h95,h70,hpoint] = ...
    plotArticleBands( ...
        hPlot, ...
        rtwi_comm(1:plot_hor_irf+1), ...
        comm_CI70(1:plot_hor_irf+1,:), ...
        comm_CI95(1:plot_hor_irf+1,:));


title('+10% commodity-price shock');

xlabel('Quarters');
ylabel('Real TWI response (%)');

xlim([0 plot_hor_irf]);

legend( ...
    [hpoint h70 h95], ...
    {'Point estimate','70% interval','95% interval'}, ...
    'Location','best', ...
    'FontSize',8);


%% VIX

nexttile;

plotArticleBands( ...
    hPlot, ...
    rtwi_vix(1:plot_hor_irf+1), ...
    vix_CI70(1:plot_hor_irf+1,:), ...
    vix_CI95(1:plot_hor_irf+1,:));


title('+10% VIX shock');

xlabel('Quarters');
ylabel('Real TWI response (%)');

xlim([0 plot_hor_irf]);


%% SPREAD

nexttile;

plotArticleBands( ...
    hPlot, ...
    rtwi_spread(1:plot_hor_irf+1), ...
    spread_CI70(1:plot_hor_irf+1,:), ...
    spread_CI95(1:plot_hor_irf+1,:));


title('+100 bp AU-US 2yr spread shock');

xlabel('Quarters');
ylabel('Real TWI response (%)');

xlim([0 plot_hor_irf]);


sgtitle( ...
    'Real TWI Responses to Commodity Prices, Global Risk and Relative Yields');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '15_svar_article_irfs_70_95.png'), ...
    'Resolution',300);


%% 29. 95% SIGNIFICANCE HORIZONS
%
% Keep 95% as the conventional inference check.
%
% We deliberately do NOT describe the 70% region as
% "statistical significance".

sig95_comm = ...
    (comm_CI95(:,1) > 0) | ...
    (comm_CI95(:,2) < 0);


sig95_vix = ...
    (vix_CI95(:,1) > 0) | ...
    (vix_CI95(:,2) < 0);


sig95_spread = ...
    (spread_CI95(:,1) > 0) | ...
    (spread_CI95(:,2) < 0);


fprintf('\n============================================================\n');
fprintf('95%% IRF INTERVALS EXCLUDE ZERO\n');
fprintf('============================================================\n');

fprintf('Commodity: %s\n', ...
    mat2str(find(sig95_comm)'-1));

fprintf('VIX:       %s\n', ...
    mat2str(find(sig95_vix)'-1));

fprintf('Spread:    %s\n', ...
    mat2str(find(sig95_spread)'-1));


%% 30. FEVD 70% AND 95% INTERVALS - ALL DRAWS

FEVD_CI70 = ...
    quantile( ...
        rtwi_FEVD_boot, ...
        CI70_quantiles, ...
        3);


FEVD_CI95 = ...
    quantile( ...
        rtwi_FEVD_boot, ...
        CI95_quantiles, ...
        3);


%% 31. FEVD 95% INTERVALS - STABLE DRAWS ONLY

FEVD_CI95_stable = ...
    quantile( ...
        rtwi_FEVD_boot(:,:,stableMask), ...
        CI95_quantiles, ...
        3);


%% 32. ARTICLE FEVD FIGURE
%
% For the short supply article, emphasise H1-H20 rather than H40.
%
% H40 results remain saved in the tables.

fevd_h = ...
    (1:plot_hor_fevd)';


fevdShockIdx = [ ...
    shock_comm ...
    shock_vix ...
    shock_spread ...
    shock_er];


fevdTitles = { ...
    'Commodity-price shock', ...
    'VIX shock', ...
    'AU-US 2yr spread shock', ...
    'Residual exchange-rate shock'};


figure( ...
    'Color','w', ...
    'Position',[100 60 1050 760]);


tiledlayout( ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


for pp = 1:length(fevdShockIdx)

    shock = ...
        fevdShockIdx(pp);


    pointSeries = ...
        rtwi_FEVD_point( ...
            shock, ...
            1:plot_hor_fevd)';


    ci70Series = ...
        squeeze( ...
            FEVD_CI70( ...
                shock, ...
                1:plot_hor_fevd, ...
                :));


    ci95Series = ...
        squeeze( ...
            FEVD_CI95( ...
                shock, ...
                1:plot_hor_fevd, ...
                :));


    nexttile;


    [h95,h70,hpoint] = ...
        plotArticleBands( ...
            fevd_h, ...
            pointSeries, ...
            ci70Series, ...
            ci95Series);


    title(fevdTitles{pp});

    xlabel('Forecast horizon');
    ylabel('Share of RTWI variance (%)');

    xlim([1 plot_hor_fevd]);


    if pp == 1

        legend( ...
            [hpoint h70 h95], ...
            {'Point estimate','70% interval','95% interval'}, ...
            'Location','best', ...
            'FontSize',8);

    end

end


sgtitle( ...
    'What Explains Forecast Errors in the Real TWI?');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '16_svar_article_fevd_70_95.png'), ...
    'Resolution',300);


%% 33. ROOT DISTRIBUTION FIGURE

figure( ...
    'Color','w', ...
    'Position',[150 150 800 450]);


histogram( ...
    max_root_boot, ...
    35);


hold on;


xline( ...
    0.99, ...
    '--k', ...
    '0.99', ...
    'LabelVerticalAlignment','bottom');


xline( ...
    1, ...
    '-k', ...
    'Unit root', ...
    'LineWidth',1.5, ...
    'LabelVerticalAlignment','bottom');


grid on;
box off;


xlabel('Maximum companion root');

ylabel('Number of bootstrap draws');

title('Persistence Across Second-Stage Bootstrap VARs');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '17_bootstrap_root_distribution.png'), ...
    'Resolution',300);


%% 34. IRF BAND-WIDTH DIAGNOSTIC
%
% Compare 95% interval width using:
%
%   all bootstrap draws
% versus
%   stable draws only
%
% If the stable-only width is much smaller, unstable draws are
% materially contributing to sampling uncertainty.


commWidthAll = ...
    comm_CI95(:,2) - ...
    comm_CI95(:,1);


commWidthStable = ...
    comm_CI95_stable(:,2) - ...
    comm_CI95_stable(:,1);


vixWidthAll = ...
    vix_CI95(:,2) - ...
    vix_CI95(:,1);


vixWidthStable = ...
    vix_CI95_stable(:,2) - ...
    vix_CI95_stable(:,1);


spreadWidthAll = ...
    spread_CI95(:,2) - ...
    spread_CI95(:,1);


spreadWidthStable = ...
    spread_CI95_stable(:,2) - ...
    spread_CI95_stable(:,1);


figure( ...
    'Color','w', ...
    'Position',[80 100 1200 370]);


tiledlayout( ...
    1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% Commodity

nexttile;

plot( ...
    h, ...
    commWidthAll, ...
    '-k', ...
    'LineWidth',2);

hold on;

plot( ...
    h, ...
    commWidthStable, ...
    '--k', ...
    'LineWidth',1.5);

grid on;
box off;

title('Commodity shock');

xlabel('Quarters');
ylabel('Width of 95% RTWI interval');

xlim([0 hor]);

legend( ...
    'All draws', ...
    'Stable draws only', ...
    'Location','best');


%% VIX

nexttile;

plot( ...
    h, ...
    vixWidthAll, ...
    '-k', ...
    'LineWidth',2);

hold on;

plot( ...
    h, ...
    vixWidthStable, ...
    '--k', ...
    'LineWidth',1.5);

grid on;
box off;

title('VIX shock');

xlabel('Quarters');

xlim([0 hor]);


%% Spread

nexttile;

plot( ...
    h, ...
    spreadWidthAll, ...
    '-k', ...
    'LineWidth',2);

hold on;

plot( ...
    h, ...
    spreadWidthStable, ...
    '--k', ...
    'LineWidth',1.5);

grid on;
box off;

title('Relative-yield shock');

xlabel('Quarters');

xlim([0 hor]);


sgtitle( ...
    'Are Unstable Bootstrap Draws Driving the Wide IRF Bands?');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '18_bootstrap_irf_bandwidth_diagnostic.png'), ...
    'Resolution',300);


%% 35. SELECTED-HORIZON IRF BAND-WIDTH TABLE

irfDiagHorizons = ...
    [0 1 4 8 12 16 20 24];


IRF_BandWidth_Diagnostic = table();


shockNames = { ...
    'Commodity', ...
    'VIX', ...
    'Spread'};


widthAll = { ...
    commWidthAll, ...
    vixWidthAll, ...
    spreadWidthAll};


widthStable = { ...
    commWidthStable, ...
    vixWidthStable, ...
    spreadWidthStable};


for ss = 1:3

    for hh = irfDiagHorizons

        row = ...
            hh + 1;


        WA = ...
            widthAll{ss}(row);


        WS = ...
            widthStable{ss}(row);


        newRow = table( ...
            string(shockNames{ss}), ...
            hh, ...
            WA, ...
            WS, ...
            WS/WA, ...
            100*(1-WS/WA), ...
            'VariableNames', ...
            { ...
            'Shock', ...
            'Horizon', ...
            'Width_AllDraws', ...
            'Width_StableOnly', ...
            'StableToAllRatio', ...
            'WidthReductionPercent'});


        IRF_BandWidth_Diagnostic = ...
            [IRF_BandWidth_Diagnostic;newRow];

    end

end


fprintf('\n============================================================\n');
fprintf('IRF BAND-WIDTH DIAGNOSTIC\n');
fprintf('============================================================\n');

disp(IRF_BandWidth_Diagnostic);


%% 36. FEVD BAND-WIDTH DIAGNOSTIC

fevdDiagHorizons = ...
    [1 4 8 12 20 40];


FEVD_BandWidth_Diagnostic = table();


headlineShockIdx = [ ...
    shock_comm ...
    shock_vix ...
    shock_spread ...
    shock_er];


headlineShockNames = { ...
    'Commodity', ...
    'VIX', ...
    'Spread', ...
    'Residual FX'};


for ss = 1:length(headlineShockIdx)

    shock = ...
        headlineShockIdx(ss);


    for H = fevdDiagHorizons


        allCI = ...
            squeeze( ...
                FEVD_CI95( ...
                    shock, ...
                    H, ...
                    :));


        stableCI = ...
            squeeze( ...
                FEVD_CI95_stable( ...
                    shock, ...
                    H, ...
                    :));


        WA = ...
            allCI(2) - allCI(1);


        WS = ...
            stableCI(2) - stableCI(1);


        newRow = table( ...
            string(headlineShockNames{ss}), ...
            H, ...
            WA, ...
            WS, ...
            WS/WA, ...
            100*(1-WS/WA), ...
            'VariableNames', ...
            { ...
            'Shock', ...
            'Horizon', ...
            'Width_AllDraws', ...
            'Width_StableOnly', ...
            'StableToAllRatio', ...
            'WidthReductionPercent'});


        FEVD_BandWidth_Diagnostic = ...
            [FEVD_BandWidth_Diagnostic;newRow];

    end

end


fprintf('\n============================================================\n');
fprintf('FEVD BAND-WIDTH DIAGNOSTIC\n');
fprintf('============================================================\n');

disp(FEVD_BandWidth_Diagnostic);


%% 37. ROOT-GROUP OUTCOME DIAGNOSTICS
%
% Compare median long-horizon results across:
%
%   Comfortable root < 0.99
%   Near-unit 0.99 <= root < 1
%   Unstable root >= 1
%
% If the near-unit / unstable groups have much larger long-horizon
% responses, we know persistence is generating the fat tails.


RootGroupDiagnostics = table();


groupNames = { ...
    'Root < 0.99', ...
    '0.99 <= Root < 1', ...
    'Root >= 1'};


groupMasks = { ...
    comfortableMask, ...
    nearUnitMask, ...
    unstableMask};


for gg = 1:3

    mask = ...
        groupMasks{gg};


    nGroup = ...
        sum(mask);


    if nGroup == 0
        continue
    end


    % IRFs:
    % H12 = row 13
    % H20 = row 21

    medComm12 = ...
        median( ...
            abs(rtwi_comm_boot(13,mask)));

    medComm20 = ...
        median( ...
            abs(rtwi_comm_boot(21,mask)));


    medVIX12 = ...
        median( ...
            abs(rtwi_vix_boot(13,mask)));

    medVIX20 = ...
        median( ...
            abs(rtwi_vix_boot(21,mask)));


    medSpread12 = ...
        median( ...
            abs(rtwi_spread_boot(13,mask)));

    medSpread20 = ...
        median( ...
            abs(rtwi_spread_boot(21,mask)));


    % FEVD medians

    medCommFEVD20 = ...
        median( ...
            squeeze( ...
                rtwi_FEVD_boot( ...
                    shock_comm, ...
                    20, ...
                    mask)));


    medCommFEVD40 = ...
        median( ...
            squeeze( ...
                rtwi_FEVD_boot( ...
                    shock_comm, ...
                    40, ...
                    mask)));


    medFXFEVD20 = ...
        median( ...
            squeeze( ...
                rtwi_FEVD_boot( ...
                    shock_er, ...
                    20, ...
                    mask)));


    medFXFEVD40 = ...
        median( ...
            squeeze( ...
                rtwi_FEVD_boot( ...
                    shock_er, ...
                    40, ...
                    mask)));


    newRow = table( ...
        string(groupNames{gg}), ...
        nGroup, ...
        median(max_root_boot(mask)), ...
        medComm12, ...
        medComm20, ...
        medVIX12, ...
        medVIX20, ...
        medSpread12, ...
        medSpread20, ...
        medCommFEVD20, ...
        medCommFEVD40, ...
        medFXFEVD20, ...
        medFXFEVD40, ...
        'VariableNames', ...
        { ...
        'RootGroup', ...
        'N', ...
        'MedianRoot', ...
        'MedianAbsCommIRF_H12', ...
        'MedianAbsCommIRF_H20', ...
        'MedianAbsVIXIRF_H12', ...
        'MedianAbsVIXIRF_H20', ...
        'MedianAbsSpreadIRF_H12', ...
        'MedianAbsSpreadIRF_H20', ...
        'MedianCommFEVD_H20', ...
        'MedianCommFEVD_H40', ...
        'MedianFXFEVD_H20', ...
        'MedianFXFEVD_H40'});


    RootGroupDiagnostics = ...
        [RootGroupDiagnostics;newRow];

end


fprintf('\n============================================================\n');
fprintf('ROOT-GROUP OUTCOME DIAGNOSTICS\n');
fprintf('============================================================\n');

disp(RootGroupDiagnostics);


%% 38. BOOTSTRAP ROOT SUMMARY TABLE

RootDiagnostics = table( ...
    nboot1, ...
    nboot2, ...
    root_original, ...
    root_bc, ...
    delta_effective, ...
    nComfortable, ...
    nNearUnit, ...
    nUnstable, ...
    100*nUnstable/nboot2, ...
    median(max_root_boot), ...
    quantile(max_root_boot,0.95), ...
    quantile(max_root_boot,0.99), ...
    max(max_root_boot), ...
    'VariableNames', ...
    { ...
    'Nboot1', ...
    'Nboot2', ...
    'OriginalRoot', ...
    'BiasCorrectedRoot', ...
    'EffectiveDelta', ...
    'ComfortablyStableDraws', ...
    'NearUnitStableDraws', ...
    'UnstableDraws', ...
    'UnstablePercent', ...
    'MedianBootstrapRoot', ...
    'P95BootstrapRoot', ...
    'P99BootstrapRoot', ...
    'MaximumBootstrapRoot'});


disp(' ');
disp(RootDiagnostics);


%% 39. ARTICLE IRF TABLES

IRF_Comm_Table = ...
    makeArticleIRFTable( ...
        h, ...
        rtwi_comm, ...
        comm_CI70, ...
        comm_CI95);


IRF_VIX_Table = ...
    makeArticleIRFTable( ...
        h, ...
        rtwi_vix, ...
        vix_CI70, ...
        vix_CI95);


IRF_Spread_Table = ...
    makeArticleIRFTable( ...
        h, ...
        rtwi_spread, ...
        spread_CI70, ...
        spread_CI95);


%% 40. SELECTED FEVD ARTICLE TABLE

fevdHorizons = ...
    [1 4 8 12 20 40];


FEVD_Article_Table = table();


for ss = 1:length(headlineShockIdx)

    shock = ...
        headlineShockIdx(ss);


    for H = fevdHorizons


        ci70 = ...
            squeeze( ...
                FEVD_CI70( ...
                    shock, ...
                    H, ...
                    :));


        ci95 = ...
            squeeze( ...
                FEVD_CI95( ...
                    shock, ...
                    H, ...
                    :));


        newRow = table( ...
            string(headlineShockNames{ss}), ...
            H, ...
            rtwi_FEVD_point(shock,H), ...
            ci95(1), ...
            ci70(1), ...
            ci70(2), ...
            ci95(2), ...
            'VariableNames', ...
            { ...
            'Shock', ...
            'Horizon', ...
            'Point', ...
            'Lower95', ...
            'Lower70', ...
            'Upper70', ...
            'Upper95'});


        FEVD_Article_Table = ...
            [FEVD_Article_Table;newRow];

    end

end


%% 41. EXPORT RESULTS

outputFile = ...
    fullfile( ...
        resultDir, ...
        'svar_bootstrap_article_results.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    IRF_Comm_Table, ...
    outputFile, ...
    'Sheet','IRF_commodity');


writetable( ...
    IRF_VIX_Table, ...
    outputFile, ...
    'Sheet','IRF_VIX');


writetable( ...
    IRF_Spread_Table, ...
    outputFile, ...
    'Sheet','IRF_spread');


writetable( ...
    FEVD_Article_Table, ...
    outputFile, ...
    'Sheet','FEVD_article');


writetable( ...
    RootDiagnostics, ...
    outputFile, ...
    'Sheet','root_diagnostics');


writetable( ...
    RootQuantileTable, ...
    outputFile, ...
    'Sheet','root_quantiles');


writetable( ...
    RootGroupDiagnostics, ...
    outputFile, ...
    'Sheet','root_groups');


writetable( ...
    IRF_BandWidth_Diagnostic, ...
    outputFile, ...
    'Sheet','IRF_bandwidth');


writetable( ...
    FEVD_BandWidth_Diagnostic, ...
    outputFile, ...
    'Sheet','FEVD_bandwidth');


%% 42. SAVE ARTICLE RESULTS

results_article = struct();


results_article.sample_start = 1995;
results_article.sample_end = 2026 + 1/4;

results_article.p = p;
results_article.n_foreign = n_foreign;

results_article.Variables = Variables;


% Point estimates

results_article.phi = phi;
results_article.SIGMA = SIGMA;
results_article.B = B;


% IRFs

results_article.rtwi_comm = rtwi_comm;
results_article.rtwi_vix = rtwi_vix;
results_article.rtwi_spread = rtwi_spread;


% Article intervals

results_article.comm_CI70 = comm_CI70;
results_article.comm_CI95 = comm_CI95;

results_article.vix_CI70 = vix_CI70;
results_article.vix_CI95 = vix_CI95;

results_article.spread_CI70 = spread_CI70;
results_article.spread_CI95 = spread_CI95;


% Stable-only diagnostic intervals

results_article.comm_CI95_stable = ...
    comm_CI95_stable;

results_article.vix_CI95_stable = ...
    vix_CI95_stable;

results_article.spread_CI95_stable = ...
    spread_CI95_stable;


% FEVD

results_article.rtwi_FEVD_point = ...
    rtwi_FEVD_point;

results_article.FEVD_CI70 = ...
    FEVD_CI70;

results_article.FEVD_CI95 = ...
    FEVD_CI95;

results_article.FEVD_CI95_stable = ...
    FEVD_CI95_stable;


% Root diagnostics

results_article.root_original = ...
    root_original;

results_article.root_bc = ...
    root_bc;

results_article.delta_effective = ...
    delta_effective;

results_article.max_root_boot = ...
    max_root_boot;

results_article.stableMask = ...
    stableMask;

results_article.nearUnitMask = ...
    nearUnitMask;

results_article.unstableMask = ...
    unstableMask;


save( ...
    fullfile( ...
        resultDir, ...
        'svar_bootstrap_article.mat'), ...
    'results_article', ...
    '-v7.3');


%% 43. FINAL SUMMARY

fprintf('\n============================================================\n');
fprintf('ARTICLE BOOTSTRAP ANALYSIS COMPLETE\n');
fprintf('============================================================\n');


fprintf('Original root:          %.4f\n', ...
    root_original);

fprintf('Bias-corrected root:    %.4f\n', ...
    root_bc);

fprintf('Effective delta:        %.4f\n', ...
    delta_effective);

fprintf('Comfortably stable:     %d / %d\n', ...
    nComfortable,nboot2);

fprintf('Near-unit stable:       %d / %d\n', ...
    nNearUnit,nboot2);

fprintf('Unstable:               %d / %d\n', ...
    nUnstable,nboot2);


fprintf('\n95%% intervals exclude zero:\n');

fprintf('Commodity: %s\n', ...
    mat2str(find(sig95_comm)'-1));

fprintf('VIX:       %s\n', ...
    mat2str(find(sig95_vix)'-1));

fprintf('Spread:    %s\n', ...
    mat2str(find(sig95_spread)'-1));


fprintf('\nResults workbook:\n%s\n', ...
    outputFile);


%% ================================================================
% LOCAL FUNCTIONS
%% ================================================================

function response = normalizedShockResponse( ...
    phi, ...
    B, ...
    shockIndex, ...
    shockSize, ...
    hor)

    N = ...
        size(B,1);


    Bn = ...
        B;


    ownImpact = ...
        B(shockIndex,shockIndex);


    if abs(ownImpact) < 1e-12

        error( ...
            'Shock own-impact is effectively zero.');

    end


    Bn(:,shockIndex) = ...
        shockSize * ...
        B(:,shockIndex) ./ ...
        ownImpact;


    IRF = ...
        calculate_IRF_FEVD( ...
            phi, ...
            Bn, ...
            hor);


    IRF3 = ...
        reshape( ...
            IRF, ...
            N,N,hor+1);


    response = ...
        squeeze( ...
            IRF3(:,shockIndex,:));


    assert( ...
        abs(response(shockIndex,1)-shockSize) < 1e-8);

end


function [h95,h70,hpoint] = ...
    plotArticleBands( ...
    x, ...
    point, ...
    ci70, ...
    ci95)

% ARTICLE-STYLE SHADED CONFIDENCE BANDS
%
% Light grey = 95%
% Darker grey = 70%
% Black line = point estimate


    x = x(:);
    point = point(:);


    grey95 = ...
        [0.88 0.88 0.88];

    grey70 = ...
        [0.68 0.68 0.68];


    h95 = fill( ...
        [x;flipud(x)], ...
        [ci95(:,1);flipud(ci95(:,2))], ...
        grey95, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.75);


    hold on;


    h70 = fill( ...
        [x;flipud(x)], ...
        [ci70(:,1);flipud(ci70(:,2))], ...
        grey70, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.85);


    hpoint = plot( ...
        x, ...
        point, ...
        '-k', ...
        'LineWidth',2);


    yline( ...
        0, ...
        'k:', ...
        'HandleVisibility','off');


    grid on;
    box off;

end


function T = ...
    makeArticleIRFTable( ...
    h, ...
    point, ...
    CI70, ...
    CI95)

    T = table( ...
        h(:), ...
        point(:), ...
        CI95(:,1), ...
        CI70(:,1), ...
        CI70(:,2), ...
        CI95(:,2), ...
        'VariableNames', ...
        { ...
        'Horizon', ...
        'Point', ...
        'Lower95', ...
        'Lower70', ...
        'Upper70', ...
        'Upper95'});

end