%% ================================================================
%  AUSTRALIAN DOLLAR DRIVERS
%  HISTORICAL-DECOMPOSITION ORDERING ROBUSTNESS
%
%  Purpose:
%
%  Repeat the RTWI historical decomposition under the four recursive
%  orderings already used in svar_ordering_robustness.m.
%
%  Model A - baseline:
%    US GDP -> Commodity -> VIX
%    AU GDP -> Inflation -> Spread -> RTWI
%
%  Model B:
%    US GDP -> VIX -> Commodity
%    AU GDP -> Inflation -> Spread -> RTWI
%
%  Model C:
%    US GDP -> Commodity -> VIX
%    AU GDP -> Inflation -> RTWI -> Spread
%
%  Model D:
%    US GDP -> VIX -> Commodity
%    AU GDP -> Inflation -> RTWI -> Spread
%
%  Sample: 1995Q1-2026Q2
%  VAR lags: 2
%  Foreign block: first 3 variables
%
%  Main outputs:
%
%    1. Exact HD accounting check for all four models
%    2. Selected-episode decompositions
%    3. Ordering sensitivity of individual shocks
%    4. Commodity+VIX and Spread+ResidualFX grouped contributions
%    5. Explicit invariance diagnostics
%
%  Model A remains the locked classical SVAR(2) benchmark.
%% ================================================================

clear;
clc;
close all;


%% 1. PRELIMINARY

folder = fileparts(mfilename('fullpath'));

addpath(fullfile(folder,'_func'));


filePath = ...
    fullfile(folder,'data','data_collected.xlsx');


figDir = ...
    fullfile(folder,'figures');

if ~exist(figDir,'dir')
    mkdir(figDir);
end


resultDir = ...
    fullfile(folder,'results');

if ~exist(resultDir,'dir')
    mkdir(resultDir);
end


assert(exist('olsvar_soe','file') == 2, ...
    'olsvar_soe.m not found.');

assert(exist('historical_decomposition','file') == 2, ...
    'historical_decomposition.m not found.');


%% 2. IMPORT DATA

data = readtable( ...
    filePath, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


%% 3. DATE VARIABLES

dateVars = { ...
    'quarter_start', ...
    'quarter_end'};


for ii = 1:length(dateVars)

    v = dateVars{ii};

    if ~isdatetime(data.(v))

        if isnumeric(data.(v))

            data.(v) = datetime( ...
                data.(v), ...
                'ConvertFrom','excel');

        else

            data.(v) = datetime(data.(v));

        end

    end

end


%% 4. MAKE OTHER VARIABLES NUMERIC

varNames = ...
    data.Properties.VariableNames;


for jj = 3:width(data)

    v = varNames{jj};

    if ~isnumeric(data.(v))

        data.(v) = ...
            str2double(string(data.(v)));

    end

end


%% 5. YEAR / QUARTER LABELS

yr = ...
    year(data.quarter_start);

qtr = ...
    ceil(month(data.quarter_start)/3);


yearlab = ...
    yr + (qtr-1)/4;


quarterlab = ...
    string(yr) + "Q" + string(qtr);


%% 6. SAMPLE

sampleStart = ...
    datetime(1995,1,1);

sampleEnd = ...
    datetime(2026,4,1);


sample = ...
    data.quarter_start >= sampleStart & ...
    data.quarter_start <= sampleEnd;


D = ...
    data(sample,:);


yearlab_svar = ...
    yearlab(sample);

quarterlab_svar = ...
    quarterlab(sample);


T = ...
    height(D);


assert(T == 126, ...
    'Unexpected sample length.');


fprintf('\n============================================================\n');
fprintf('HD ORDERING ROBUSTNESS\n');
fprintf('============================================================\n');

fprintf('Sample: %s to %s\n', ...
    char(quarterlab_svar(1)), ...
    char(quarterlab_svar(end)));

fprintf('T = %d\n',T);


%% 7. TRANSFORM VARIABLES
%
% Identical to baseline SVAR(2).


log_us_gdp = ...
    100*log(D.us_rgdp);

log_comm = ...
    100*log(D.comm_price);

log_vix = ...
    100*log(D.vix);

log_au_gdp = ...
    100*log(D.au_rgdp);

trim_inf = ...
    D.au_inf_trim;

spread_2yr = ...
    D.au_us_2yr;

log_rtwi = ...
    100*log(D.rtwi);


%% 8. QUADRATIC GDP DETRENDING

tt = ...
    (1:T)';


Xtrend = [ ...
    ones(T,1) ...
    tt ...
    tt.^2];


% US GDP

b_us = ...
    Xtrend \ log_us_gdp;

us_gdp_gap = ...
    log_us_gdp - Xtrend*b_us;


% Australian GDP

b_au = ...
    Xtrend \ log_au_gdp;

au_gdp_gap = ...
    log_au_gdp - Xtrend*b_au;


%% 9. CANONICAL DATASET
%
% This is our base ordering only for convenient indexing.
%
% Each robustness model reorders these columns before estimation.


Ybase = [ ...
    us_gdp_gap ...
    log_comm ...
    log_vix ...
    au_gdp_gap ...
    trim_inf ...
    spread_2yr ...
    log_rtwi];


baseKeys = { ...
    'USGDP', ...
    'Commodity', ...
    'VIX', ...
    'AUGDP', ...
    'Inflation', ...
    'Spread', ...
    'RTWI'};


baseLabels = { ...
    'US Real GDP', ...
    'Commodity Prices', ...
    'VIX', ...
    'Australian Real GDP', ...
    'Trimmed Mean Inflation', ...
    'AU-US 2yr Spread', ...
    'Real TWI'};


N = ...
    size(Ybase,2);


assert(N == 7);


%% 10. MODEL SETTINGS

p = 2;

n_foreign = 3;


% No deterministic controls
d = ...
    zeros(T,0);


%% 11. FOUR ORDERINGS

modelNames = { ...
    'A_Baseline', ...
    'B_VIX_before_Commodity', ...
    'C_RTWI_before_Spread', ...
    'D_Swap_Both'};


modelShort = { ...
    'A: C -> VIX; Spread -> RTWI', ...
    'B: VIX -> C; Spread -> RTWI', ...
    'C: C -> VIX; RTWI -> Spread', ...
    'D: VIX -> C; RTWI -> Spread'};


orderIdx = cell(4,1);


% Model A
orderIdx{1} = ...
    [1 2 3 4 5 6 7];


% Model B
orderIdx{2} = ...
    [1 3 2 4 5 6 7];


% Model C
orderIdx{3} = ...
    [1 2 3 4 5 7 6];


% Model D
orderIdx{4} = ...
    [1 3 2 4 5 7 6];


M = ...
    length(modelNames);


%% 12. CORRECTED HISTORICAL EPISODES
%
% IMPORTANT:
%
% Episode contributions are calculated from the quarter immediately
% BEFORE episodeStart to episodeEnd.
%
% Therefore:
%
% COVID shock:
%   episodeStart = 2020Q1
%   episodeEnd   = 2020Q1
%
% measures:
%   2019Q4 -> 2020Q1


episodeNames = { ...
    'GFC', ...
    'Commodity-boom appreciation', ...
    'Post-boom depreciation', ...
    'COVID shock', ...
    'COVID rebound', ...
    'Recent period'};


episodeStart = [ ...
    datetime(2008,7,1); ...
    datetime(2009,7,1); ...
    datetime(2013,1,1); ...
    datetime(2020,1,1); ...
    datetime(2020,4,1); ...
    datetime(2022,1,1)];


episodeEnd = [ ...
    datetime(2009,4,1); ...
    datetime(2011,4,1); ...
    datetime(2015,7,1); ...
    datetime(2020,1,1); ...
    datetime(2021,4,1); ...
    datetime(2026,4,1)];


nEpisodes = ...
    length(episodeNames);


%% 13. STORAGE
%
% Time-series HD contributions for each model.
%
% Dimensions:
% T x M

HD_global = ...
    nan(T,M);

HD_commodity = ...
    nan(T,M);

HD_vix = ...
    nan(T,M);

HD_domestic = ...
    nan(T,M);

HD_spread = ...
    nan(T,M);

HD_fx = ...
    nan(T,M);


HD_commodityRisk = ...
    nan(T,M);

HD_yieldFX = ...
    nan(T,M);


baselineRTWI = ...
    nan(T,M);

totalShockRTWI = ...
    nan(T,M);


actualRTWIlog = ...
    nan(T,M);


maxAccountingError = ...
    nan(M,1);

maxRoot = ...
    nan(M,1);


% Episode-level arrays:
%
% episode x model

episodeActual = ...
    nan(nEpisodes,M);

episodeBaseline = ...
    nan(nEpisodes,M);

episodeGlobal = ...
    nan(nEpisodes,M);

episodeCommodity = ...
    nan(nEpisodes,M);

episodeVIX = ...
    nan(nEpisodes,M);

episodeDomestic = ...
    nan(nEpisodes,M);

episodeSpread = ...
    nan(nEpisodes,M);

episodeFX = ...
    nan(nEpisodes,M);

episodeCommodityRisk = ...
    nan(nEpisodes,M);

episodeYieldFX = ...
    nan(nEpisodes,M);


results_ordering_HD = ...
    struct([]);


%% 14. ESTIMATE FOUR MODELS

for mm = 1:M

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('MODEL %s\n',modelNames{mm});
    fprintf('============================================================\n');


    %% ------------------------------------------------------------
    % REORDER VARIABLES
    %% ------------------------------------------------------------

    idx = ...
        orderIdx{mm};


    y = ...
        Ybase(:,idx);


    keys = ...
        baseKeys(idx);


    labels = ...
        baseLabels(idx);


    %% LOCATE ECONOMIC VARIABLES IN THIS MODEL

    posUS = ...
        find(strcmp(keys,'USGDP'));

    posComm = ...
        find(strcmp(keys,'Commodity'));

    posVIX = ...
        find(strcmp(keys,'VIX'));

    posAUGDP = ...
        find(strcmp(keys,'AUGDP'));

    posInf = ...
        find(strcmp(keys,'Inflation'));

    posSpread = ...
        find(strcmp(keys,'Spread'));

    posRTWI = ...
        find(strcmp(keys,'RTWI'));


    %% ------------------------------------------------------------
    % ESTIMATE SOE VAR
    %% ------------------------------------------------------------

    [phi,gamma,SIGMA,X,e] = ...
        olsvar_soe( ...
            y, ...
            p, ...
            d, ...
            n_foreign);


    %% ------------------------------------------------------------
    % STABILITY
    %% ------------------------------------------------------------

    Companion = [ ...
        phi(2:end,:)'; ...
        eye(N*(p-1)) zeros(N*(p-1),N)];


    rootsVAR = ...
        eig(Companion);


    maxRoot(mm) = ...
        max(abs(rootsVAR));


    fprintf('Maximum root: %.4f\n', ...
        maxRoot(mm));


    %% ------------------------------------------------------------
    % CHOLESKY IDENTIFICATION
    %% ------------------------------------------------------------

    [B,cholFlag] = ...
        chol(SIGMA,'lower');


    assert(cholFlag == 0, ...
        'SIGMA not positive definite for model %s.', ...
        modelNames{mm});


    %% ------------------------------------------------------------
    % HISTORICAL DECOMPOSITION
    %% ------------------------------------------------------------

    HD = ...
        historical_decomposition( ...
            phi, ...
            e, ...
            B);


    %% ------------------------------------------------------------
    % NO-SHOCK BASELINE
    %% ------------------------------------------------------------

    baseline = ...
        constructVARBaseline( ...
            phi, ...
            gamma, ...
            d, ...
            y, ...
            p);


    %% ------------------------------------------------------------
    % ACCOUNTING CHECK FOR ALL VARIABLES
    %% ------------------------------------------------------------

    reconstructed = ...
        baseline;


    for ii = 1:N

        reconstructed(:,ii) = ...
            baseline(:,ii) ...
            + sum(HD{ii},2);

    end


    accountingError = ...
        y - reconstructed;


    maxAccountingError(mm) = ...
        max(abs(accountingError),[], 'all');


    assert( ...
        maxAccountingError(mm) < 1e-8, ...
        'HD accounting failed for model %s.', ...
        modelNames{mm});


    fprintf('Maximum HD accounting error: %.3e\n', ...
        maxAccountingError(mm));


    %% ------------------------------------------------------------
    % RTWI DECOMPOSITION
    %% ------------------------------------------------------------

    HDrtwi = ...
        HD{posRTWI};


    % Columns of HDrtwi correspond to structural shocks in this
    % model's recursive ordering.
    %
    % Map them back to economic labels.

    HD_global(:,mm) = ...
        HDrtwi(:,posUS);


    HD_commodity(:,mm) = ...
        HDrtwi(:,posComm);


    HD_vix(:,mm) = ...
        HDrtwi(:,posVIX);


    HD_domestic(:,mm) = ...
        HDrtwi(:,posAUGDP) ...
        + HDrtwi(:,posInf);


    HD_spread(:,mm) = ...
        HDrtwi(:,posSpread);


    HD_fx(:,mm) = ...
        HDrtwi(:,posRTWI);


    %% GROUPED PAIRS

    HD_commodityRisk(:,mm) = ...
        HD_commodity(:,mm) ...
        + HD_vix(:,mm);


    HD_yieldFX(:,mm) = ...
        HD_spread(:,mm) ...
        + HD_fx(:,mm);


    %% BASELINE / TOTAL SHOCK COMPONENT

    baselineRTWI(:,mm) = ...
        baseline(:,posRTWI);


    totalShockRTWI(:,mm) = ...
        sum(HDrtwi,2);


    actualRTWIlog(:,mm) = ...
        y(:,posRTWI);


    %% RTWI ACCOUNTING CHECK

    rtwiError = ...
        actualRTWIlog(:,mm) ...
        - baselineRTWI(:,mm) ...
        - totalShockRTWI(:,mm);


    assert( ...
        max(abs(rtwiError)) < 1e-8);


    %% ------------------------------------------------------------
    % SELECTED EPISODES
    %% ------------------------------------------------------------

    for ee = 1:nEpisodes

        % Quarter immediately BEFORE start

        i0 = ...
            find( ...
                D.quarter_start < episodeStart(ee), ...
                1, ...
                'last');


        % Episode end

        i1 = ...
            find( ...
                D.quarter_start <= episodeEnd(ee), ...
                1, ...
                'last');


        if isempty(i0) || isempty(i1)

            error( ...
                'Episode %s outside model sample.', ...
                episodeNames{ee});

        end


        %% ACTUAL AND BASELINE CHANGE

        episodeActual(ee,mm) = ...
            actualRTWIlog(i1,mm) ...
            - actualRTWIlog(i0,mm);


        episodeBaseline(ee,mm) = ...
            baselineRTWI(i1,mm) ...
            - baselineRTWI(i0,mm);


        %% SHOCK CONTRIBUTIONS

        episodeGlobal(ee,mm) = ...
            HD_global(i1,mm) ...
            - HD_global(i0,mm);


        episodeCommodity(ee,mm) = ...
            HD_commodity(i1,mm) ...
            - HD_commodity(i0,mm);


        episodeVIX(ee,mm) = ...
            HD_vix(i1,mm) ...
            - HD_vix(i0,mm);


        episodeDomestic(ee,mm) = ...
            HD_domestic(i1,mm) ...
            - HD_domestic(i0,mm);


        episodeSpread(ee,mm) = ...
            HD_spread(i1,mm) ...
            - HD_spread(i0,mm);


        episodeFX(ee,mm) = ...
            HD_fx(i1,mm) ...
            - HD_fx(i0,mm);


        episodeCommodityRisk(ee,mm) = ...
            episodeCommodity(ee,mm) ...
            + episodeVIX(ee,mm);


        episodeYieldFX(ee,mm) = ...
            episodeSpread(ee,mm) ...
            + episodeFX(ee,mm);


        %% EPISODE ACCOUNTING

        episodeRecon = ...
            episodeBaseline(ee,mm) ...
            + episodeGlobal(ee,mm) ...
            + episodeCommodity(ee,mm) ...
            + episodeVIX(ee,mm) ...
            + episodeDomestic(ee,mm) ...
            + episodeSpread(ee,mm) ...
            + episodeFX(ee,mm);


        assert( ...
            abs( ...
                episodeActual(ee,mm) ...
                - episodeRecon) ...
            < 1e-8);

    end


    %% ------------------------------------------------------------
    % SAVE FULL MODEL RESULTS
    %% ------------------------------------------------------------

    results_ordering_HD(mm).name = ...
        modelNames{mm};


    results_ordering_HD(mm).ordering = ...
        labels;


    results_ordering_HD(mm).phi = ...
        phi;


    results_ordering_HD(mm).SIGMA = ...
        SIGMA;


    results_ordering_HD(mm).B = ...
        B;


    results_ordering_HD(mm).HD = ...
        HD;


    results_ordering_HD(mm).baseline = ...
        baseline;


    results_ordering_HD(mm).maxRoot = ...
        maxRoot(mm);

end


%% 15. CHECK REDUCED-FORM / BASELINE INVARIANCE
%
% Changing only Cholesky ordering should not materially alter:
%
%   actual RTWI
%   no-shock RTWI baseline
%   total shock component
%
% after mapping variables back to their economic identities.


maxActualDifference = ...
    max( ...
        abs( ...
            actualRTWIlog ...
            - actualRTWIlog(:,1)), ...
        [], ...
        'all');


maxBaselineDifference = ...
    max( ...
        abs( ...
            baselineRTWI ...
            - baselineRTWI(:,1)), ...
        [], ...
        'all');


maxTotalShockDifference = ...
    max( ...
        abs( ...
            totalShockRTWI ...
            - totalShockRTWI(:,1)), ...
        [], ...
        'all');


fprintf('\n============================================================\n');
fprintf('REDUCED-FORM INVARIANCE CHECK\n');
fprintf('============================================================\n');

fprintf('Maximum actual RTWI difference:      %.12g\n', ...
    maxActualDifference);

fprintf('Maximum baseline difference:         %.12g\n', ...
    maxBaselineDifference);

fprintf('Maximum total-shock difference:      %.12g\n', ...
    maxTotalShockDifference);


%% 16. CHECK PAIR-GROUP INVARIANCE THROUGH TIME
%
% Earlier FEVD exercise suggested these pairs are much more robust
% to recursive ordering:
%
%   Commodity + VIX
%
%   Relative yield + residual FX
%
% Test that explicitly for historical decomposition.


maxDiffCommodityRisk = ...
    max( ...
        abs( ...
            HD_commodityRisk ...
            - HD_commodityRisk(:,1)), ...
        [], ...
        'all');


maxDiffYieldFX = ...
    max( ...
        abs( ...
            HD_yieldFX ...
            - HD_yieldFX(:,1)), ...
        [], ...
        'all');


fprintf('\n============================================================\n');
fprintf('PAIR-GROUP HD INVARIANCE CHECK\n');
fprintf('============================================================\n');

fprintf('Max difference Commodity + VIX:      %.12g\n', ...
    maxDiffCommodityRisk);

fprintf('Max difference Spread + Residual FX: %.12g\n', ...
    maxDiffYieldFX);


%% 17. BUILD LONG-FORM EPISODE TABLE

EpisodeOrderingTable = table();


for mm = 1:M

    for ee = 1:nEpisodes

        newRow = table( ...
            string(modelNames{mm}), ...
            string(modelShort{mm}), ...
            string(episodeNames{ee}), ...
            episodeStart(ee), ...
            episodeEnd(ee), ...
            episodeActual(ee,mm), ...
            episodeBaseline(ee,mm), ...
            episodeGlobal(ee,mm), ...
            episodeCommodity(ee,mm), ...
            episodeVIX(ee,mm), ...
            episodeDomestic(ee,mm), ...
            episodeSpread(ee,mm), ...
            episodeFX(ee,mm), ...
            episodeCommodityRisk(ee,mm), ...
            episodeYieldFX(ee,mm), ...
            'VariableNames', ...
            { ...
            'Model', ...
            'Ordering', ...
            'Episode', ...
            'Start', ...
            'End', ...
            'ActualChange', ...
            'BaselineDynamics', ...
            'GlobalActivity', ...
            'CommodityPrices', ...
            'VIX', ...
            'DomesticMacro', ...
            'RelativeYields', ...
            'ResidualFX', ...
            'CommodityPlusVIX', ...
            'YieldPlusResidualFX'});


        EpisodeOrderingTable = ...
            [EpisodeOrderingTable;newRow];

    end

end


fprintf('\n============================================================\n');
fprintf('EPISODE HD ACROSS ORDERINGS\n');
fprintf('============================================================\n');

disp(EpisodeOrderingTable);


%% 18. EPISODE SENSITIVITY SUMMARY
%
% For each historical episode, report the range across A-D.
%
% Large ranges for Commodity and VIX but tiny range for their sum
% would confirm that identification mainly reallocates contributions
% inside the pair.


EpisodeSensitivity = table();


for ee = 1:nEpisodes

    newRow = table( ...
        string(episodeNames{ee}), ...
        min(episodeCommodity(ee,:)), ...
        max(episodeCommodity(ee,:)), ...
        max(episodeCommodity(ee,:)) ...
            - min(episodeCommodity(ee,:)), ...
        min(episodeVIX(ee,:)), ...
        max(episodeVIX(ee,:)), ...
        max(episodeVIX(ee,:)) ...
            - min(episodeVIX(ee,:)), ...
        min(episodeCommodityRisk(ee,:)), ...
        max(episodeCommodityRisk(ee,:)), ...
        max(episodeCommodityRisk(ee,:)) ...
            - min(episodeCommodityRisk(ee,:)), ...
        min(episodeSpread(ee,:)), ...
        max(episodeSpread(ee,:)), ...
        max(episodeSpread(ee,:)) ...
            - min(episodeSpread(ee,:)), ...
        min(episodeFX(ee,:)), ...
        max(episodeFX(ee,:)), ...
        max(episodeFX(ee,:)) ...
            - min(episodeFX(ee,:)), ...
        min(episodeYieldFX(ee,:)), ...
        max(episodeYieldFX(ee,:)), ...
        max(episodeYieldFX(ee,:)) ...
            - min(episodeYieldFX(ee,:)), ...
        'VariableNames', ...
        { ...
        'Episode', ...
        'Commodity_Min', ...
        'Commodity_Max', ...
        'Commodity_Range', ...
        'VIX_Min', ...
        'VIX_Max', ...
        'VIX_Range', ...
        'CommodityVIX_Min', ...
        'CommodityVIX_Max', ...
        'CommodityVIX_Range', ...
        'Spread_Min', ...
        'Spread_Max', ...
        'Spread_Range', ...
        'ResidualFX_Min', ...
        'ResidualFX_Max', ...
        'ResidualFX_Range', ...
        'YieldFX_Min', ...
        'YieldFX_Max', ...
        'YieldFX_Range'});


    EpisodeSensitivity = ...
        [EpisodeSensitivity;newRow];

end


fprintf('\n============================================================\n');
fprintf('EPISODE IDENTIFICATION SENSITIVITY\n');
fprintf('============================================================\n');

disp(EpisodeSensitivity);


%% 19. FIGURE 1 - ORDERING-ROBUST PAIR CONTRIBUTIONS
%
% If the grouped bars are essentially identical across A-D, we can
% make stronger statements about these broader channels even when the
% exact split inside each pair is identification-sensitive.


x = ...
    1:nEpisodes;


figure( ...
    'Color','w', ...
    'Position',[80 100 1250 600]);


tiledlayout( ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% Commodity + VIX

nexttile;


bar( ...
    x, ...
    episodeCommodityRisk, ...
    'grouped');


hold on;


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(x);

xticklabels(episodeNames);

xtickangle(15);


ylabel('Contribution to RTWI change');

title('Commodity + global-risk contribution');


legend( ...
    modelShort, ...
    'Location','eastoutside', ...
    'FontSize',8);


%% Relative yield + FX residual

nexttile;


bar( ...
    x, ...
    episodeYieldFX, ...
    'grouped');


hold on;


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(x);

xticklabels(episodeNames);

xtickangle(15);


ylabel('Contribution to RTWI change');

title('Relative-yield + other exchange-rate contribution');


sgtitle( ...
    'Historical-Decomposition Robustness Across Recursive Orderings');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '26_hd_ordering_grouped_pairs.png'), ...
    'Resolution',300);


%% 20. FIGURE 2 - INDIVIDUAL-SHOCK ORDERING SENSITIVITY

figure( ...
    'Color','w', ...
    'Position',[80 60 1250 800]);


tiledlayout( ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% Commodity

nexttile;


bar( ...
    x, ...
    episodeCommodity, ...
    'grouped');


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


title('Commodity-price shocks');

ylabel('Contribution to RTWI change');

xticks(x);

xticklabels(episodeNames);

xtickangle(20);


legend( ...
    modelShort, ...
    'Location','best', ...
    'FontSize',7);


%% VIX

nexttile;


bar( ...
    x, ...
    episodeVIX, ...
    'grouped');


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


title('Global-risk / VIX shocks');

ylabel('Contribution to RTWI change');

xticks(x);

xticklabels(episodeNames);

xtickangle(20);


%% Spread

nexttile;


bar( ...
    x, ...
    episodeSpread, ...
    'grouped');


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


title('Relative-yield shocks');

ylabel('Contribution to RTWI change');

xticks(x);

xticklabels(episodeNames);

xtickangle(20);


%% Residual FX

nexttile;


bar( ...
    x, ...
    episodeFX, ...
    'grouped');


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


title('Other exchange-rate shocks');

ylabel('Contribution to RTWI change');

xticks(x);

xticklabels(episodeNames);

xtickangle(20);


sgtitle( ...
    'How Much Does Recursive Ordering Change the Historical Narrative?');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '27_hd_ordering_individual_shocks.png'), ...
    'Resolution',300);


%% 21. CORRECTED BASELINE EPISODE FIGURE
%
% Recreate Model A with the corrected COVID crash definition.
%
% This is the classical SVAR(2) decomposition we will retain as the
% transparent benchmark.


baselineEpisodeComponents = [ ...
    episodeBaseline(:,1) ...
    episodeGlobal(:,1) ...
    episodeCommodity(:,1) ...
    episodeVIX(:,1) ...
    episodeDomestic(:,1) ...
    episodeSpread(:,1) ...
    episodeFX(:,1)];


baselineComponentLabels = { ...
    'Baseline dynamics', ...
    'Global activity', ...
    'Commodity prices', ...
    'Global risk (VIX)', ...
    'Domestic macro', ...
    'Relative yields', ...
    'Other exchange-rate shocks'};


figure( ...
    'Color','w', ...
    'Position',[90 100 1250 600]);


b = bar( ...
    x, ...
    baselineEpisodeComponents, ...
    'stacked');


hold on;


hObserved = plot( ...
    x, ...
    episodeActual(:,1), ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',7);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


grid on;
box off;


xticks(x);

xticklabels(episodeNames);

xtickangle(20);


ylabel('Contribution to RTWI change, log points');


title( ...
    'What Drove Major Australian Dollar Episodes?');


legend( ...
    [b(:); hObserved], ...
    [baselineComponentLabels {'Observed change'}], ...
    'Location','eastoutside');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '28_hd_baseline_episodes_corrected.png'), ...
    'Resolution',300);


%% 22. FULL TIME-SERIES TABLE ACROSS ORDERINGS

HD_Long = table();


for mm = 1:M

    temp = table( ...
        repmat(string(modelNames{mm}),T,1), ...
        D.quarter_start, ...
        quarterlab_svar, ...
        actualRTWIlog(:,mm), ...
        baselineRTWI(:,mm), ...
        totalShockRTWI(:,mm), ...
        HD_global(:,mm), ...
        HD_commodity(:,mm), ...
        HD_vix(:,mm), ...
        HD_domestic(:,mm), ...
        HD_spread(:,mm), ...
        HD_fx(:,mm), ...
        HD_commodityRisk(:,mm), ...
        HD_yieldFX(:,mm), ...
        'VariableNames', ...
        { ...
        'Model', ...
        'Date', ...
        'Quarter', ...
        'Actual_RTWI_Log', ...
        'Baseline_RTWI_Log', ...
        'Total_Shock_Component', ...
        'Global_Activity', ...
        'Commodity_Prices', ...
        'VIX', ...
        'Domestic_Macro', ...
        'Relative_Yields', ...
        'Residual_FX', ...
        'CommodityPlusVIX', ...
        'YieldPlusResidualFX'});


    HD_Long = ...
        [HD_Long;temp];

end


%% 23. DIAGNOSTIC SUMMARY TABLE

OrderingDiagnostics = table( ...
    string(modelNames(:)), ...
    maxRoot, ...
    maxAccountingError, ...
    'VariableNames', ...
    { ...
    'Model', ...
    'MaximumRoot', ...
    'MaximumAccountingError'});


PairInvarianceDiagnostics = table( ...
    maxActualDifference, ...
    maxBaselineDifference, ...
    maxTotalShockDifference, ...
    maxDiffCommodityRisk, ...
    maxDiffYieldFX, ...
    'VariableNames', ...
    { ...
    'MaxActualRTWIDifference', ...
    'MaxBaselineDifference', ...
    'MaxTotalShockDifference', ...
    'MaxCommodityVIXDifference', ...
    'MaxYieldFXDifference'});


disp(' ');
disp(OrderingDiagnostics);

disp(' ');
disp(PairInvarianceDiagnostics);


%% 24. EXPORT TO EXCEL

outputFile = ...
    fullfile( ...
        resultDir, ...
        'svar_hd_ordering_robustness.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    EpisodeOrderingTable, ...
    outputFile, ...
    'Sheet','episodes_all_orderings');


writetable( ...
    EpisodeSensitivity, ...
    outputFile, ...
    'Sheet','episode_sensitivity');


writetable( ...
    HD_Long, ...
    outputFile, ...
    'Sheet','HD_all_orderings');


writetable( ...
    OrderingDiagnostics, ...
    outputFile, ...
    'Sheet','model_diagnostics');


writetable( ...
    PairInvarianceDiagnostics, ...
    outputFile, ...
    'Sheet','pair_invariance');


% Explicit baseline-only episode sheet

baselineRows = ...
    EpisodeOrderingTable.Model == "A_Baseline";


BaselineEpisodeTable = ...
    EpisodeOrderingTable(baselineRows,:);


writetable( ...
    BaselineEpisodeTable, ...
    outputFile, ...
    'Sheet','baseline_A_episodes');


%% 25. LOCK CLASSICAL SVAR(2) BASELINE
%
% Model A is retained as the transparent classical benchmark.
%
% Saving this separately makes it explicit which model is the locked
% baseline before we move to the BVAR.


classical_baseline = struct();


classical_baseline.model = ...
    'SVAR(2) Model A';


classical_baseline.ordering = ...
    baseLabels;


classical_baseline.sample_start = ...
    '1995Q1';


classical_baseline.sample_end = ...
    '2026Q2';


classical_baseline.p = ...
    p;


classical_baseline.n_foreign = ...
    n_foreign;


classical_baseline.max_root = ...
    maxRoot(1);


classical_baseline.results = ...
    results_ordering_HD(1);


classical_baseline.HD_global = ...
    HD_global(:,1);


classical_baseline.HD_commodity = ...
    HD_commodity(:,1);


classical_baseline.HD_vix = ...
    HD_vix(:,1);


classical_baseline.HD_domestic = ...
    HD_domestic(:,1);


classical_baseline.HD_spread = ...
    HD_spread(:,1);


classical_baseline.HD_fx = ...
    HD_fx(:,1);


classical_baseline.HD_commodityRisk = ...
    HD_commodityRisk(:,1);


classical_baseline.HD_yieldFX = ...
    HD_yieldFX(:,1);


classical_baseline.BaselineEpisodeTable = ...
    BaselineEpisodeTable;


save( ...
    fullfile( ...
        resultDir, ...
        'classical_svar2_baseline_locked.mat'), ...
    'classical_baseline', ...
    '-v7.3');


%% 26. SAVE ROBUSTNESS RESULTS

hd_ordering_results = struct();


hd_ordering_results.modelNames = ...
    modelNames;


hd_ordering_results.modelShort = ...
    modelShort;


hd_ordering_results.orderIdx = ...
    orderIdx;


hd_ordering_results.models = ...
    results_ordering_HD;


hd_ordering_results.EpisodeOrderingTable = ...
    EpisodeOrderingTable;


hd_ordering_results.EpisodeSensitivity = ...
    EpisodeSensitivity;


hd_ordering_results.OrderingDiagnostics = ...
    OrderingDiagnostics;


hd_ordering_results.PairInvarianceDiagnostics = ...
    PairInvarianceDiagnostics;


hd_ordering_results.HD_global = ...
    HD_global;


hd_ordering_results.HD_commodity = ...
    HD_commodity;


hd_ordering_results.HD_vix = ...
    HD_vix;


hd_ordering_results.HD_domestic = ...
    HD_domestic;


hd_ordering_results.HD_spread = ...
    HD_spread;


hd_ordering_results.HD_fx = ...
    HD_fx;


hd_ordering_results.HD_commodityRisk = ...
    HD_commodityRisk;


hd_ordering_results.HD_yieldFX = ...
    HD_yieldFX;


save( ...
    fullfile( ...
        resultDir, ...
        'svar_hd_ordering_robustness.mat'), ...
    'hd_ordering_results', ...
    '-v7.3');


%% 27. FINAL SUMMARY

fprintf('\n============================================================\n');
fprintf('HD ORDERING ROBUSTNESS COMPLETE\n');
fprintf('============================================================\n');


fprintf('\nMaximum pair-group differences across full history:\n');

fprintf('Commodity + VIX:      %.12g\n', ...
    maxDiffCommodityRisk);

fprintf('Spread + Residual FX: %.12g\n', ...
    maxDiffYieldFX);


fprintf('\nLocked baseline:\n');

fprintf('SVAR(2), Model A\n');

fprintf('Maximum root: %.4f\n', ...
    maxRoot(1));


fprintf('\nRobustness workbook:\n%s\n', ...
    outputFile);


fprintf('\nLocked baseline MAT file:\n%s\n', ...
    fullfile( ...
        resultDir, ...
        'classical_svar2_baseline_locked.mat'));


%% ================================================================
% LOCAL FUNCTION
%% ================================================================

function baseline = constructVARBaseline( ...
    phi, ...
    gamma, ...
    D, ...
    y, ...
    p)

% ================================================================
% Reconstruct VAR path generated by:
%
%   - intercept
%   - deterministic variables
%   - initial conditions
%
% with all shocks equal to zero.
%
% Uses the same mean-backcasting convention as olsvar_soe.m.
% ================================================================


    [T,N] = ...
        size(y);


    if isempty(D)

        D = ...
            zeros(T,0);

    end


    if isempty(gamma)

        gamma = ...
            zeros(size(D,2),N);

    end


    initialMean = ...
        mean(y,1);


    baseline_ext = [ ...
        repmat(initialMean,p,1); ...
        zeros(T,N)];


    for t = 1:T


        % Intercept

        thisValue = ...
            phi(1,:);


        % Deterministic controls

        if size(D,2) > 0

            thisValue = ...
                thisValue ...
                + D(t,:)*gamma;

        end


        % VAR lags

        for lag = 1:p

            rows = ...
                2 + (lag-1)*N : ...
                1 + lag*N;


            thisValue = ...
                thisValue ...
                + baseline_ext(p+t-lag,:) ...
                * phi(rows,:);

        end


        baseline_ext(p+t,:) = ...
            thisValue;

    end


    baseline = ...
        baseline_ext(p+1:end,:);

end