%% ================================================================
%  AUSTRALIAN DOLLAR DRIVERS - BASELINE SVAR BOOTSTRAP
%
%  Model A:
%
%  FOREIGN BLOCK
%    1. US real GDP gap
%    2. RBA commodity price index (SDR)
%    3. VIX
%
%  DOMESTIC BLOCK
%    4. Australian real GDP gap
%    5. Australian trimmed mean inflation
%    6. AU-US 2-year yield spread
%    7. Australian real TWI
%
%  Sample: 1995Q1-2026Q2
%  VAR lags: 2
%
%  Identification:
%    Recursive Cholesky
%
%  Bootstrap:
%    Kilian (1998) bootstrap-after-bootstrap using
%    bootstrap_after_bootstrap_soe.m
%
%  Outputs:
%    - 85% and 95% bootstrap bands for headline RTWI IRFs
%    - bootstrap FEVD intervals
%    - grouped FEVD intervals
%    - bootstrap stability diagnostics
%% ================================================================

clear;
clc;
close all;


%% 1. PRELIMINARY

folder = fileparts(mfilename('fullpath'));

addpath(fullfile(folder,'_func'));


filePath = ...
    fullfile(folder,'data','data_collected.xlsx');


figDir = ...
    fullfile(folder,'figures');

if ~exist(figDir,'dir')
    mkdir(figDir);
end


resultDir = ...
    fullfile(folder,'results');

if ~exist(resultDir,'dir')
    mkdir(resultDir);
end


assert(exist('olsvar_soe','file') == 2, ...
    'olsvar_soe.m not found.');

assert(exist('calculate_IRF_FEVD','file') == 2, ...
    'calculate_IRF_FEVD.m not found.');

assert(exist('bootstrap_after_bootstrap_soe','file') == 2, ...
    'bootstrap_after_bootstrap_soe.m not found.');


%% 2. IMPORT DATA

data = readtable( ...
    filePath, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


%% 3. DATE VARIABLES

dateVars = { ...
    'quarter_start', ...
    'quarter_end'};


for ii = 1:length(dateVars)

    v = dateVars{ii};

    if ~isdatetime(data.(v))

        if isnumeric(data.(v))

            data.(v) = datetime( ...
                data.(v), ...
                'ConvertFrom','excel');

        else

            data.(v) = ...
                datetime(data.(v));

        end

    end

end


%% 4. MAKE OTHER VARIABLES NUMERIC

varNames = ...
    data.Properties.VariableNames;


for jj = 3:width(data)

    v = varNames{jj};

    if ~isnumeric(data.(v))

        data.(v) = ...
            str2double(string(data.(v)));

    end

end


%% 5. YEARLAB

yr = ...
    year(data.quarter_start);

qtr = ...
    ceil(month(data.quarter_start)/3);


yearlab = ...
    yr + (qtr-1)/4;


quarterlab = ...
    string(yr) + "Q" + string(qtr);


%% 6. SAMPLE

sampleStart = ...
    datetime(1995,1,1);

sampleEnd = ...
    datetime(2026,4,1);


sample = ...
    data.quarter_start >= sampleStart & ...
    data.quarter_start <= sampleEnd;


D = ...
    data(sample,:);

yearlab_svar = ...
    yearlab(sample);

quarterlab_svar = ...
    quarterlab(sample);


T = height(D);


assert(T == 126, ...
    'Unexpected sample size.');


fprintf('\n============================================================\n');
fprintf('BASELINE SVAR BOOTSTRAP\n');
fprintf('============================================================\n');

fprintf('Sample: %s to %s\n', ...
    char(quarterlab_svar(1)), ...
    char(quarterlab_svar(end)));

fprintf('Observations: %d\n',T);


%% 7. CHECK REQUIRED VARIABLES

requiredVars = { ...
    'us_rgdp', ...
    'comm_price', ...
    'vix', ...
    'au_rgdp', ...
    'au_inf_trim', ...
    'au_us_2yr', ...
    'rtwi'};


for ii = 1:length(requiredVars)

    v = requiredVars{ii};

    assert( ...
        ismember(v,D.Properties.VariableNames), ...
        'Missing variable: %s',v);

    assert( ...
        all(isfinite(D.(v))), ...
        'Variable %s contains missing observations.',v);

end


%% 8. TRANSFORM VARIABLES
%
% Same transformations as svar_initial.m


log_us_gdp = ...
    100*log(D.us_rgdp);

log_comm = ...
    100*log(D.comm_price);

log_vix = ...
    100*log(D.vix);

log_au_gdp = ...
    100*log(D.au_rgdp);

trim_inf = ...
    D.au_inf_trim;

spread_2yr = ...
    D.au_us_2yr;

log_rtwi = ...
    100*log(D.rtwi);


%% 9. QUADRATIC GDP DETRENDING

tt = ...
    (1:T)';


Xtrend = [ ...
    ones(T,1) ...
    tt ...
    tt.^2];


% US GDP
b_us = ...
    Xtrend \ log_us_gdp;

trend_us = ...
    Xtrend*b_us;

us_gdp_gap = ...
    log_us_gdp - trend_us;


% Australian GDP
b_au = ...
    Xtrend \ log_au_gdp;

trend_au = ...
    Xtrend*b_au;

au_gdp_gap = ...
    log_au_gdp - trend_au;


%% 10. BASELINE MODEL A DATASET

y = [ ...
    us_gdp_gap ...
    log_comm ...
    log_vix ...
    au_gdp_gap ...
    trim_inf ...
    spread_2yr ...
    log_rtwi];


Variables = { ...
    'US Real GDP', ...
    'Commodity Prices', ...
    'VIX', ...
    'Australian Real GDP', ...
    'Trimmed Mean Inflation', ...
    'AU-US 2yr Spread', ...
    'Real TWI'};


N = ...
    size(y,2);


assert(N == 7);
assert(~any(isnan(y(:))));
assert(~any(isinf(y(:))));


%% 11. MODEL SETTINGS

p = 2;

n_foreign = 3;


shock_us = 1;
shock_comm = 2;
shock_vix = 3;
shock_augdp = 4;
shock_inf = 5;
shock_spread = 6;
shock_er = 7;


hor = 24;

hor_fevd = 40;


% Normalised presentation shocks
size_comm_shock = 10;       % +10 log points
size_vix_shock = 10;        % +10 log points
size_spread_shock = 1;      % +1 ppt = 100 bp


%% 12. BOOTSTRAP SETTINGS

nboot1 = 1000;

nboot2 = 1000;


rng_seed = 12345;


% For a quick code test before the full run, temporarily use:
%
% nboot1 = 100;
% nboot2 = 100;


% 95% and 85% percentile intervals:
%
% col 1 = lower 95
% col 2 = lower 85
% col 3 = upper 85
% col 4 = upper 95

CI_quantiles = ...
    [0.025 0.075 0.925 0.975];


%% 13. NO DETERMINISTIC CONTROLS
%
% IMPORTANT:
%
% bootstrap_after_bootstrap_soe requires d to have T rows even if
% there are zero deterministic variables.
%
% Therefore use zeros(T,0), NOT [].

d = ...
    zeros(T,0);


%% 14. ESTIMATE BASELINE REDUCED-FORM VAR

[phi,gamma,SIGMA,X,e] = ...
    olsvar_soe( ...
        y, ...
        p, ...
        d, ...
        n_foreign);


%% 15. POINT-ESTIMATE STABILITY

Companion_original = [ ...
    phi(2:end,:)'; ...
    eye(N*(p-1)) zeros(N*(p-1),N)];


root_original = ...
    max(abs(eig(Companion_original)));


fprintf('\nOriginal VAR maximum root: %.4f\n', ...
    root_original);


%% 16. POINT-ESTIMATE CHOLESKY

[~,cholFlag] = ...
    chol(SIGMA);


assert(cholFlag == 0, ...
    'Point-estimate SIGMA is not positive definite.');


B = ...
    chol(SIGMA,'lower');


%% 17. POINT-ESTIMATE HEADLINE IRFs

resp_comm = ...
    normalizedShockResponse( ...
        phi, ...
        B, ...
        shock_comm, ...
        size_comm_shock, ...
        hor);


resp_vix = ...
    normalizedShockResponse( ...
        phi, ...
        B, ...
        shock_vix, ...
        size_vix_shock, ...
        hor);


resp_spread = ...
    normalizedShockResponse( ...
        phi, ...
        B, ...
        shock_spread, ...
        size_spread_shock, ...
        hor);


rtwi_comm = ...
    resp_comm(shock_er,:)';

rtwi_vix = ...
    resp_vix(shock_er,:)';

rtwi_spread = ...
    resp_spread(shock_er,:)';


%% 18. POINT-ESTIMATE FEVD
%
% Always use the unnormalised Cholesky B matrix for FEVD.

[~,FEVD_point] = ...
    calculate_IRF_FEVD( ...
        phi, ...
        B, ...
        hor_fevd, ...
        'FEVD');


rtwi_FEVD_point = ...
    squeeze( ...
        FEVD_point( ...
            shock_er, ...
            :, ...
            :));


% Dimensions:
% N shocks x (hor_fevd+1)


%% 19. KILIAN BOOTSTRAP-AFTER-BOOTSTRAP

fprintf('\n============================================================\n');
fprintf('RUNNING KILIAN BOOTSTRAP-AFTER-BOOTSTRAP\n');
fprintf('============================================================\n');

fprintf('First-stage replications:  %d\n',nboot1);
fprintf('Second-stage replications: %d\n',nboot2);


rng(rng_seed);


[phi_boot, ...
 SIGMA_boot, ...
 phi_bias_corrected, ...
 bias] = ...
    bootstrap_after_bootstrap_soe( ...
        phi, ...
        gamma, ...
        X, ...
        e, ...
        d, ...
        p, ...
        n_foreign, ...
        nboot1, ...
        nboot2);


%% 20. BIAS-CORRECTED VAR STABILITY

Companion_bc = [ ...
    phi_bias_corrected(2:end,:)'; ...
    eye(N*(p-1)) zeros(N*(p-1),N)];


root_bc = ...
    max(abs(eig(Companion_bc)));


fprintf('\nBootstrap bias diagnostics:\n');

fprintf('Original VAR maximum root:       %.4f\n', ...
    root_original);

fprintf('Bias-corrected VAR maximum root: %.4f\n', ...
    root_bc);

fprintf('Maximum absolute bias:           %.4f\n', ...
    max(abs(bias(:))));


%% 21. STORAGE FOR BOOTSTRAP IRFs AND FEVD

rtwi_comm_boot = ...
    NaN(hor+1,nboot2);

rtwi_vix_boot = ...
    NaN(hor+1,nboot2);

rtwi_spread_boot = ...
    NaN(hor+1,nboot2);


% RTWI FEVD:
% shock x horizon x bootstrap draw

rtwi_FEVD_boot = ...
    NaN(N,hor_fevd+1,nboot2);


% Stability diagnostics

max_root_boot = ...
    NaN(nboot2,1);

unstable_boot = ...
    false(nboot2,1);


%% 22. BOOTSTRAP IRFs AND FEVD

fprintf('\nConstructing bootstrap IRFs and FEVD...\n');


for jj = 1:nboot2

    %% BOOTSTRAP VAR STABILITY

    Companion_boot = [ ...
        phi_boot(2:end,:,jj)'; ...
        eye(N*(p-1)) zeros(N*(p-1),N)];


    max_root_boot(jj) = ...
        max(abs(eig(Companion_boot)));


    unstable_boot(jj) = ...
        max_root_boot(jj) >= 1;


    %% CHOLESKY IDENTIFICATION

    [B_boot,cholFlag] = ...
        chol( ...
            SIGMA_boot(:,:,jj), ...
            'lower');


    if cholFlag ~= 0

        error( ...
            'Bootstrap covariance matrix not positive definite at draw %d.', ...
            jj);

    end


    %% COMMODITY SHOCK

    resp = ...
        normalizedShockResponse( ...
            phi_boot(:,:,jj), ...
            B_boot, ...
            shock_comm, ...
            size_comm_shock, ...
            hor);


    rtwi_comm_boot(:,jj) = ...
        resp(shock_er,:)';


    %% VIX SHOCK

    resp = ...
        normalizedShockResponse( ...
            phi_boot(:,:,jj), ...
            B_boot, ...
            shock_vix, ...
            size_vix_shock, ...
            hor);


    rtwi_vix_boot(:,jj) = ...
        resp(shock_er,:)';


    %% RELATIVE-YIELD SHOCK

    resp = ...
        normalizedShockResponse( ...
            phi_boot(:,:,jj), ...
            B_boot, ...
            shock_spread, ...
            size_spread_shock, ...
            hor);


    rtwi_spread_boot(:,jj) = ...
        resp(shock_er,:)';


    %% FEVD
    %
    % IMPORTANT:
    % use raw B_boot, not any normalised impact matrix.

    [~,FEVD_j] = ...
        calculate_IRF_FEVD( ...
            phi_boot(:,:,jj), ...
            B_boot, ...
            hor_fevd, ...
            'FEVD');


    rtwi_FEVD_boot(:,:,jj) = ...
        squeeze( ...
            FEVD_j( ...
                shock_er, ...
                :, ...
                :));


    %% PROGRESS

    if mod(jj,100) == 0

        fprintf('Completed bootstrap draw %d of %d\n', ...
            jj,nboot2);

    end

end


%% 23. BOOTSTRAP STABILITY DIAGNOSTICS

unstable_count = ...
    sum(unstable_boot);


fprintf('\n============================================================\n');
fprintf('SECOND-STAGE BOOTSTRAP STABILITY\n');
fprintf('============================================================\n');

fprintf('Unstable draws: %d out of %d (%.1f%%)\n', ...
    unstable_count, ...
    nboot2, ...
    100*unstable_count/nboot2);

fprintf('Median maximum root: %.4f\n', ...
    median(max_root_boot));

fprintf('95th percentile maximum root: %.4f\n', ...
    quantile(max_root_boot,0.95));

fprintf('Maximum maximum root: %.4f\n', ...
    max(max_root_boot));


%% 24. IRF BOOTSTRAP CONFIDENCE INTERVALS

comm_CI = ...
    quantile( ...
        rtwi_comm_boot, ...
        CI_quantiles, ...
        2);


vix_CI = ...
    quantile( ...
        rtwi_vix_boot, ...
        CI_quantiles, ...
        2);


spread_CI = ...
    quantile( ...
        rtwi_spread_boot, ...
        CI_quantiles, ...
        2);


%% 25. HEADLINE IRF FIGURE WITH BOOTSTRAP BANDS

h = ...
    (0:hor)';


figure( ...
    'Color','w', ...
    'Position',[80 100 1250 390]);


tiledlayout( ...
    1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% COMMODITY SHOCK

nexttile;

plot( ...
    h, ...
    rtwi_comm, ...
    '-k', ...
    'LineWidth',2);

hold on;

plot( ...
    h, ...
    comm_CI(:,2:3), ...
    '--b', ...
    'LineWidth',1.2);

plot( ...
    h, ...
    comm_CI(:,[1 4]), ...
    '--r', ...
    'LineWidth',1.2);

yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');

grid on;
box off;

title('+10% commodity-price shock');

xlabel('Quarters');
ylabel('Real TWI response (%)');

xlim([0 hor]);


%% VIX SHOCK

nexttile;

plot( ...
    h, ...
    rtwi_vix, ...
    '-k', ...
    'LineWidth',2);

hold on;

plot( ...
    h, ...
    vix_CI(:,2:3), ...
    '--b', ...
    'LineWidth',1.2);

plot( ...
    h, ...
    vix_CI(:,[1 4]), ...
    '--r', ...
    'LineWidth',1.2);

yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');

grid on;
box off;

title('+10% VIX shock');

xlabel('Quarters');
ylabel('Real TWI response (%)');

xlim([0 hor]);


%% SPREAD SHOCK

nexttile;

plot( ...
    h, ...
    rtwi_spread, ...
    '-k', ...
    'LineWidth',2);

hold on;

plot( ...
    h, ...
    spread_CI(:,2:3), ...
    '--b', ...
    'LineWidth',1.2);

plot( ...
    h, ...
    spread_CI(:,[1 4]), ...
    '--r', ...
    'LineWidth',1.2);

yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');

grid on;
box off;

title('+100 bp AU-US 2yr spread shock');

xlabel('Quarters');
ylabel('Real TWI response (%)');

xlim([0 hor]);


sgtitle( ...
    'Real TWI Responses with Kilian Bootstrap Confidence Intervals');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '15_svar_bootstrap_headline_irfs.png'), ...
    'Resolution',300);


%% 26. SIGNIFICANCE HORIZONS
%
% CI columns:
%
% 1 lower 95
% 2 lower 85
% 3 upper 85
% 4 upper 95


sig95_comm = ...
    (comm_CI(:,1) > 0) | ...
    (comm_CI(:,4) < 0);

sig85_comm = ...
    (comm_CI(:,2) > 0) | ...
    (comm_CI(:,3) < 0);


sig95_vix = ...
    (vix_CI(:,1) > 0) | ...
    (vix_CI(:,4) < 0);

sig85_vix = ...
    (vix_CI(:,2) > 0) | ...
    (vix_CI(:,3) < 0);


sig95_spread = ...
    (spread_CI(:,1) > 0) | ...
    (spread_CI(:,4) < 0);

sig85_spread = ...
    (spread_CI(:,2) > 0) | ...
    (spread_CI(:,3) < 0);


fprintf('\n============================================================\n');
fprintf('RTWI IRF SIGNIFICANCE HORIZONS\n');
fprintf('============================================================\n');


fprintf('\n95%% intervals exclude zero:\n');

fprintf('Commodity: %s\n', ...
    mat2str(find(sig95_comm)'-1));

fprintf('VIX:       %s\n', ...
    mat2str(find(sig95_vix)'-1));

fprintf('Spread:    %s\n', ...
    mat2str(find(sig95_spread)'-1));


fprintf('\n85%% intervals exclude zero:\n');

fprintf('Commodity: %s\n', ...
    mat2str(find(sig85_comm)'-1));

fprintf('VIX:       %s\n', ...
    mat2str(find(sig85_vix)'-1));

fprintf('Spread:    %s\n', ...
    mat2str(find(sig85_spread)'-1));


%% 27. FEVD BOOTSTRAP CONFIDENCE INTERVALS
%
% Dimensions:
%
% N shocks x (hor_fevd+1) x 4 quantiles

FEVD_CI = ...
    quantile( ...
        rtwi_FEVD_boot, ...
        CI_quantiles, ...
        3);


%% 28. GROUPED FEVD BOOTSTRAP DISTRIBUTIONS
%
% These must be calculated draw by draw BEFORE taking quantiles.
%
% Do not add confidence limits from individual FEVD shares.


comm_vix_point = ...
    rtwi_FEVD_point(shock_comm,:) ...
    + rtwi_FEVD_point(shock_vix,:);


spread_fx_point = ...
    rtwi_FEVD_point(shock_spread,:) ...
    + rtwi_FEVD_point(shock_er,:);


comm_vix_boot = ...
    squeeze( ...
        rtwi_FEVD_boot(shock_comm,:,:) ...
        + rtwi_FEVD_boot(shock_vix,:,:));


spread_fx_boot = ...
    squeeze( ...
        rtwi_FEVD_boot(shock_spread,:,:) ...
        + rtwi_FEVD_boot(shock_er,:,:));


% squeeze gives horizon x bootstrap draw


comm_vix_CI = ...
    quantile( ...
        comm_vix_boot, ...
        CI_quantiles, ...
        2);


spread_fx_CI = ...
    quantile( ...
        spread_fx_boot, ...
        CI_quantiles, ...
        2);


%% 29. FEVD FIGURE WITH BOOTSTRAP INTERVALS
%
% Plot H1-H40.
%
% Note:
% calculate_IRF_FEVD returns hor_fevd+1 slices.
% Following our previous FEVD convention, slice 1 is labelled H1,
% slice 40 is labelled H40.


fevd_h = ...
    (1:hor_fevd)';


fevdShockIdx = [ ...
    shock_comm ...
    shock_vix ...
    shock_spread ...
    shock_er];


fevdTitles = { ...
    'Commodity-price shock', ...
    'VIX shock', ...
    'AU-US 2yr spread shock', ...
    'Residual exchange-rate shock'};


figure( ...
    'Color','w', ...
    'Position',[100 60 1050 760]);


tiledlayout( ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


for pp = 1:length(fevdShockIdx)

    shock = ...
        fevdShockIdx(pp);


    pointSeries = ...
        rtwi_FEVD_point( ...
            shock, ...
            1:hor_fevd)';


    ciSeries = ...
        squeeze( ...
            FEVD_CI( ...
                shock, ...
                1:hor_fevd, ...
                :));


    nexttile;


    plot( ...
        fevd_h, ...
        pointSeries, ...
        '-k', ...
        'LineWidth',2);

    hold on;


    plot( ...
        fevd_h, ...
        ciSeries(:,2:3), ...
        '--b', ...
        'LineWidth',1.1);


    plot( ...
        fevd_h, ...
        ciSeries(:,[1 4]), ...
        '--r', ...
        'LineWidth',1.1);


    grid on;
    box off;


    title(fevdTitles{pp});

    xlabel('Forecast horizon');
    ylabel('Share of RTWI FE variance (%)');

    xlim([1 hor_fevd]);

end


sgtitle( ...
    'RTWI Forecast-Error Variance Decomposition with Bootstrap Intervals');


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '16_svar_bootstrap_fevd.png'), ...
    'Resolution',300);


%% 30. SELECTED FEVD HORIZONS

fevdHorizons = [ ...
    1 ...
    4 ...
    8 ...
    12 ...
    20 ...
    40];


headlineShockIdx = [ ...
    shock_comm ...
    shock_vix ...
    shock_spread ...
    shock_er];


headlineShockNames = { ...
    'Commodity', ...
    'VIX', ...
    'AU-US 2yr Spread', ...
    'Residual FX'};


FEVD_CI_Table = table();


for ss = 1:length(headlineShockIdx)

    shock = ...
        headlineShockIdx(ss);


    for hh = 1:length(fevdHorizons)

        H = ...
            fevdHorizons(hh);


        ci = ...
            squeeze( ...
                FEVD_CI( ...
                    shock, ...
                    H, ...
                    :));


        newRow = table( ...
            string(headlineShockNames{ss}), ...
            H, ...
            rtwi_FEVD_point(shock,H), ...
            ci(1), ...
            ci(2), ...
            ci(3), ...
            ci(4), ...
            'VariableNames', ...
            { ...
            'Shock', ...
            'Horizon', ...
            'Point', ...
            'Lower95', ...
            'Lower85', ...
            'Upper85', ...
            'Upper95'});


        FEVD_CI_Table = ...
            [FEVD_CI_Table; newRow];

    end

end


fprintf('\n============================================================\n');
fprintf('RTWI FEVD WITH BOOTSTRAP INTERVALS\n');
fprintf('============================================================\n');

disp(FEVD_CI_Table);


%% 31. GROUPED FEVD TABLE WITH INTERVALS

Grouped_FEVD_CI_Table = table();


groupNames = { ...
    'Commodity + VIX', ...
    'Spread + Residual FX'};


for gg = 1:2

    if gg == 1

        point = ...
            comm_vix_point;

        ciAll = ...
            comm_vix_CI;

    else

        point = ...
            spread_fx_point;

        ciAll = ...
            spread_fx_CI;

    end


    for hh = 1:length(fevdHorizons)

        H = ...
            fevdHorizons(hh);


        newRow = table( ...
            string(groupNames{gg}), ...
            H, ...
            point(H), ...
            ciAll(H,1), ...
            ciAll(H,2), ...
            ciAll(H,3), ...
            ciAll(H,4), ...
            'VariableNames', ...
            { ...
            'Group', ...
            'Horizon', ...
            'Point', ...
            'Lower95', ...
            'Lower85', ...
            'Upper85', ...
            'Upper95'});


        Grouped_FEVD_CI_Table = ...
            [Grouped_FEVD_CI_Table; newRow];

    end

end


fprintf('\n============================================================\n');
fprintf('GROUPED RTWI FEVD WITH BOOTSTRAP INTERVALS\n');
fprintf('============================================================\n');

disp(Grouped_FEVD_CI_Table);


%% 32. IRF TABLES

IRF_Comm_Table = ...
    makeIRFTable( ...
        h, ...
        rtwi_comm, ...
        comm_CI);


IRF_VIX_Table = ...
    makeIRFTable( ...
        h, ...
        rtwi_vix, ...
        vix_CI);


IRF_Spread_Table = ...
    makeIRFTable( ...
        h, ...
        rtwi_spread, ...
        spread_CI);


%% 33. BOOTSTRAP DIAGNOSTICS TABLE

Bootstrap_Diagnostics = table( ...
    nboot1, ...
    nboot2, ...
    rng_seed, ...
    root_original, ...
    root_bc, ...
    max(abs(bias(:))), ...
    unstable_count, ...
    100*unstable_count/nboot2, ...
    median(max_root_boot), ...
    quantile(max_root_boot,0.95), ...
    max(max_root_boot), ...
    'VariableNames', ...
    { ...
    'Nboot1', ...
    'Nboot2', ...
    'RNGSeed', ...
    'OriginalMaxRoot', ...
    'BiasCorrectedMaxRoot', ...
    'MaxAbsoluteBias', ...
    'UnstableDraws', ...
    'UnstablePercent', ...
    'MedianBootstrapRoot', ...
    'P95BootstrapRoot', ...
    'MaximumBootstrapRoot'});


disp(' ');
disp(Bootstrap_Diagnostics);


%% 34. EXPORT RESULTS TO EXCEL

outputFile = ...
    fullfile( ...
        resultDir, ...
        'svar_bootstrap_results.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    IRF_Comm_Table, ...
    outputFile, ...
    'Sheet','IRF_commodity');


writetable( ...
    IRF_VIX_Table, ...
    outputFile, ...
    'Sheet','IRF_VIX');


writetable( ...
    IRF_Spread_Table, ...
    outputFile, ...
    'Sheet','IRF_spread');


writetable( ...
    FEVD_CI_Table, ...
    outputFile, ...
    'Sheet','FEVD_headline');


writetable( ...
    Grouped_FEVD_CI_Table, ...
    outputFile, ...
    'Sheet','FEVD_grouped');


writetable( ...
    Bootstrap_Diagnostics, ...
    outputFile, ...
    'Sheet','diagnostics');


%% 35. SAVE MATLAB RESULTS

results_bootstrap = struct();


% Model information
results_bootstrap.sample_start = ...
    1995;

results_bootstrap.sample_end = ...
    2026 + 1/4;

results_bootstrap.p = ...
    p;

results_bootstrap.n_foreign = ...
    n_foreign;

results_bootstrap.Variables = ...
    Variables;

results_bootstrap.yearlab = ...
    yearlab_svar;


% Bootstrap settings
results_bootstrap.nboot1 = ...
    nboot1;

results_bootstrap.nboot2 = ...
    nboot2;

results_bootstrap.rng_seed = ...
    rng_seed;

results_bootstrap.CI_quantiles = ...
    CI_quantiles;


% Point VAR
results_bootstrap.phi = ...
    phi;

results_bootstrap.gamma = ...
    gamma;

results_bootstrap.SIGMA = ...
    SIGMA;

results_bootstrap.B = ...
    B;


% Bias correction
results_bootstrap.phi_bias_corrected = ...
    phi_bias_corrected;

results_bootstrap.bias = ...
    bias;


% Point IRFs
results_bootstrap.rtwi_comm = ...
    rtwi_comm;

results_bootstrap.rtwi_vix = ...
    rtwi_vix;

results_bootstrap.rtwi_spread = ...
    rtwi_spread;


% Bootstrap IRFs
results_bootstrap.rtwi_comm_boot = ...
    rtwi_comm_boot;

results_bootstrap.rtwi_vix_boot = ...
    rtwi_vix_boot;

results_bootstrap.rtwi_spread_boot = ...
    rtwi_spread_boot;


% IRF bands
results_bootstrap.comm_CI = ...
    comm_CI;

results_bootstrap.vix_CI = ...
    vix_CI;

results_bootstrap.spread_CI = ...
    spread_CI;


% Point FEVD
results_bootstrap.rtwi_FEVD_point = ...
    rtwi_FEVD_point;


% Bootstrap FEVD
results_bootstrap.rtwi_FEVD_boot = ...
    rtwi_FEVD_boot;

results_bootstrap.FEVD_CI = ...
    FEVD_CI;


% Grouped FEVD
results_bootstrap.comm_vix_point = ...
    comm_vix_point;

results_bootstrap.spread_fx_point = ...
    spread_fx_point;

results_bootstrap.comm_vix_CI = ...
    comm_vix_CI;

results_bootstrap.spread_fx_CI = ...
    spread_fx_CI;


% Stability
results_bootstrap.root_original = ...
    root_original;

results_bootstrap.root_bc = ...
    root_bc;

results_bootstrap.max_root_boot = ...
    max_root_boot;

results_bootstrap.unstable_boot = ...
    unstable_boot;


save( ...
    fullfile( ...
        resultDir, ...
        'svar_bootstrap.mat'), ...
    'results_bootstrap', ...
    '-v7.3');


%% 36. FINAL SUMMARY

fprintf('\n============================================================\n');
fprintf('SVAR BOOTSTRAP COMPLETE\n');
fprintf('============================================================\n');

fprintf('Sample: %s to %s\n', ...
    char(quarterlab_svar(1)), ...
    char(quarterlab_svar(end)));

fprintf('Original max root:       %.4f\n', ...
    root_original);

fprintf('Bias-corrected max root: %.4f\n', ...
    root_bc);

fprintf('Unstable bootstrap draws: %d / %d\n', ...
    unstable_count, ...
    nboot2);


fprintf('\n95%% significant RTWI horizons:\n');

fprintf('Commodity: %s\n', ...
    mat2str(find(sig95_comm)'-1));

fprintf('VIX:       %s\n', ...
    mat2str(find(sig95_vix)'-1));

fprintf('Spread:    %s\n', ...
    mat2str(find(sig95_spread)'-1));


fprintf('\nExcel results:\n%s\n', ...
    outputFile);


fprintf('\nMATLAB results:\n%s\n', ...
    fullfile( ...
        resultDir, ...
        'svar_bootstrap.mat'));


%% ================================================================
% LOCAL FUNCTIONS
%% ================================================================

function response = normalizedShockResponse( ...
    phi, ...
    B, ...
    shockIndex, ...
    shockSize, ...
    hor)

% NORMALIZEDSHOCKRESPONSE
%
% Rescale one structural-shock column so that the shocked variable's
% own impact response equals shockSize.


    N = ...
        size(B,1);


    Bn = ...
        B;


    ownImpact = ...
        B(shockIndex,shockIndex);


    if abs(ownImpact) < 1e-12

        error( ...
            'Shock own-impact is effectively zero.');

    end


    Bn(:,shockIndex) = ...
        shockSize * ...
        B(:,shockIndex) ./ ...
        ownImpact;


    IRF = ...
        calculate_IRF_FEVD( ...
            phi, ...
            Bn, ...
            hor);


    IRF3 = ...
        reshape( ...
            IRF, ...
            N,N,hor+1);


    response = ...
        squeeze( ...
            IRF3(:,shockIndex,:));


    assert( ...
        abs(response(shockIndex,1)-shockSize) < 1e-8);

end


function T = makeIRFTable( ...
    h, ...
    point, ...
    CI)

% MAKEIRFTABLE
%
% Create compact point estimate + 85% and 95% interval table.


    T = table( ...
        h(:), ...
        point(:), ...
        CI(:,1), ...
        CI(:,2), ...
        CI(:,3), ...
        CI(:,4), ...
        'VariableNames', ...
        { ...
        'Horizon', ...
        'Point', ...
        'Lower95', ...
        'Lower85', ...
        'Upper85', ...
        'Upper95'});

end