%% ================================================================
%  FINAL ARTICLE-PLANNING HISTORICAL DECOMPOSITION
%  CLASSICAL SOE-SVAR
%
%  This file DOES NOT re-estimate the SVAR.
%
%  It loads:
%
%       results/svar_historical_decomposition.mat
%
%  and produces a common final set of selected historical episodes.
%
%  Displayed components:
%
%   1. Baseline dynamics
%   2. Global activity
%   3. Commodity prices
%   4. Global risk (VIX)
%   5. Domestic macro
%   6. Relative yields
%   7. Other exchange-rate shocks
%
%% ================================================================

clear;
clc;
close all;


%% ================================================================
% 1. PATHS
%% ================================================================

folder = ...
    fileparts(mfilename('fullpath'));


resultDir = ...
    fullfile(folder,'results');


figDir = ...
    fullfile(folder,'figures');


if ~exist(figDir,'dir')
    mkdir(figDir);
end


dataFile = ...
    fullfile( ...
        folder, ...
        'data', ...
        'data_collected.xlsx');


hdFile = ...
    fullfile( ...
        resultDir, ...
        'svar_historical_decomposition.mat');


assert( ...
    isfile(hdFile), ...
    'Run svar_hd.m first.');


%% ================================================================
% 2. LOAD LOCKED SVAR HISTORICAL DECOMPOSITION
%% ================================================================

S = ...
    load(hdFile);


hd = ...
    S.hd_results;


clear S


HD_grouped = ...
    hd.HD_grouped;


rtwi_actual = ...
    hd.rtwi_actual_log;


rtwi_baseline = ...
    hd.rtwi_baseline_log;


assert(size(HD_grouped,2) == 6);


%% ================================================================
% 3. LOAD DATES
%% ================================================================

data = readtable( ...
    dataFile, ...
    'Sheet','data', ...
    'VariableNamingRule','preserve');


data = standardizeMissing( ...
    data, ...
    {'NA','N/A','na',''});


if ~isdatetime(data.quarter_start)

    if isnumeric(data.quarter_start)

        data.quarter_start = ...
            datetime( ...
                data.quarter_start, ...
                'ConvertFrom','excel');

    else

        data.quarter_start = ...
            datetime(data.quarter_start);

    end

end


sample = ...
    data.quarter_start >= datetime(1995,1,1) ...
    & data.quarter_start <= datetime(2026,4,1);


D = ...
    data(sample,:);


assert( ...
    height(D) == length(rtwi_actual), ...
    'Saved SVAR HD and data dates do not match.');


%% ================================================================
% 4. FINAL EPISODES
%
% The recent period is deliberately split into two adjacent,
% non-overlapping episodes:
%
%   2022Q1-2025Q3:
%       change from 2021Q4 to 2025Q3
%
%   2025Q4-2026Q2:
%       change from 2025Q3 to 2026Q2
%
% Therefore the two recent-period contributions add exactly to the
% full 2022Q1-2026Q2 change, apart from numerical precision.
%% ================================================================

episodeNames = { ...
    'GFC', ...
    'Commodity-boom appreciation', ...
    'Post-boom depreciation', ...
    'COVID shock', ...
    'COVID rebound', ...
    '2022Q1-2025Q3', ...
    '2025Q4-2026Q2'};


plotLabels = { ...
    'GFC', ...
    'Commodity boom', ...
    'Post-boom', ...
    'COVID shock', ...
    'COVID rebound', ...
    '2022-25', ...
    'Recent appreciation'};


episodeStart = [ ...
    datetime(2008,7,1); ...    % 2008Q3
    datetime(2009,7,1); ...    % 2009Q3
    datetime(2013,1,1); ...    % 2013Q1
    datetime(2020,1,1); ...    % 2020Q1
    datetime(2020,4,1); ...    % 2020Q2
    datetime(2022,1,1); ...    % 2022Q1
    datetime(2025,10,1)];      % 2025Q4


episodeEnd = [ ...
    datetime(2009,4,1); ...    % 2009Q2
    datetime(2011,4,1); ...    % 2011Q2
    datetime(2015,7,1); ...    % 2015Q3
    datetime(2020,1,1); ...    % 2020Q1
    datetime(2021,4,1); ...    % 2021Q2
    datetime(2025,7,1); ...    % 2025Q3
    datetime(2026,4,1)];       % 2026Q2


nEpisodes = ...
    length(episodeNames);


%% ================================================================
% 5. COMPONENT NAMES
%% ================================================================

componentNames = { ...
    'Baseline dynamics', ...
    'Global activity', ...
    'Commodity prices', ...
    'Global risk (VIX)', ...
    'Domestic macro', ...
    'Relative yields', ...
    'Other exchange-rate shocks'};


nComponents = ...
    length(componentNames);


%% ================================================================
% 6. EPISODE INDICES
%% ================================================================

episode_i0 = ...
    nan(nEpisodes,1);


episode_i1 = ...
    nan(nEpisodes,1);


ActualChange = ...
    nan(nEpisodes,1);


for ee = 1:nEpisodes

    episode_i0(ee) = ...
        find( ...
            D.quarter_start < episodeStart(ee), ...
            1, ...
            'last');


    episode_i1(ee) = ...
        find( ...
            D.quarter_start <= episodeEnd(ee), ...
            1, ...
            'last');


    assert( ...
        ~isempty(episode_i0(ee)) ...
        && ~isempty(episode_i1(ee)));


    ActualChange(ee) = ...
        rtwi_actual(episode_i1(ee)) ...
        - rtwi_actual(episode_i0(ee));

end


%% ================================================================
% 7. CALCULATE SVAR CONTRIBUTIONS
%% ================================================================

Contrib = ...
    nan(nEpisodes,nComponents);


AccountingError = ...
    nan(nEpisodes,1);


for ee = 1:nEpisodes

    i0 = ...
        episode_i0(ee);


    i1 = ...
        episode_i1(ee);


    %% Baseline dynamics

    Contrib(ee,1) = ...
        rtwi_baseline(i1) ...
        - rtwi_baseline(i0);


    %% Structural contributions
    %
    % HD_grouped columns:
    %
    % 1 global activity
    % 2 commodity prices
    % 3 VIX
    % 4 domestic macro
    % 5 relative yields
    % 6 other FX

    Contrib(ee,2:7) = ...
        HD_grouped(i1,:) ...
        - HD_grouped(i0,:);


    AccountingError(ee) = ...
        ActualChange(ee) ...
        - sum(Contrib(ee,:));

end


assert( ...
    max(abs(AccountingError)) < 1e-8);

%% ================================================================
% 7A. RECENT-PERIOD ADDITIVITY CHECK
%
% Episodes 6 and 7 together must reproduce the full change from
% 2021Q4 to 2026Q2.
%% ================================================================

fullRecentStart = ...
    datetime(2022,1,1);


fullRecentEnd = ...
    datetime(2026,4,1);


i0_fullRecent = ...
    find( ...
    D.quarter_start < fullRecentStart, ...
    1, ...
    'last');


i1_fullRecent = ...
    find( ...
    D.quarter_start <= fullRecentEnd, ...
    1, ...
    'last');


FullRecentActual = ...
    rtwi_actual(i1_fullRecent) ...
    - rtwi_actual(i0_fullRecent);


FullRecentContrib = ...
    [ ...
    rtwi_baseline(i1_fullRecent) ...
    - rtwi_baseline(i0_fullRecent), ...
    HD_grouped(i1_fullRecent,:) ...
    - HD_grouped(i0_fullRecent,:) ...
    ];


SplitRecentActual = ...
    ActualChange(6) ...
    + ActualChange(7);


SplitRecentContrib = ...
    Contrib(6,:) ...
    + Contrib(7,:);


fprintf('\n');
fprintf('============================================================\n');
fprintf('SVAR RECENT-PERIOD ADDITIVITY CHECK\n');
fprintf('============================================================\n');

fprintf( ...
    'Full 2022Q1-2026Q2 observed change: %.6f\n', ...
    FullRecentActual);

fprintf( ...
    'Sum of two split episodes:          %.6f\n', ...
    SplitRecentActual);

fprintf( ...
    'Observed-change discrepancy:        %.3e\n', ...
    FullRecentActual-SplitRecentActual);

fprintf( ...
    'Maximum component discrepancy:      %.3e\n', ...
    max(abs(FullRecentContrib-SplitRecentContrib)));


assert( ...
    abs(FullRecentActual-SplitRecentActual) < 1e-8);


assert( ...
    max(abs(FullRecentContrib-SplitRecentContrib)) < 1e-8);

%% ================================================================
% 8. WIDE RESULTS TABLE
%% ================================================================

SVAR_Final = table( ...
    string(episodeNames(:)), ...
    D.quarter_start(episode_i0), ...
    D.quarter_start(episode_i1), ...
    ActualChange, ...
    Contrib(:,1), ...
    Contrib(:,2), ...
    Contrib(:,3), ...
    Contrib(:,4), ...
    Contrib(:,5), ...
    Contrib(:,6), ...
    Contrib(:,7), ...
    AccountingError, ...
    'VariableNames', ...
    { ...
    'Episode', ...
    'PreviousQuarter', ...
    'EndQuarter', ...
    'Observed_RTWI_Change', ...
    'Baseline_Dynamics', ...
    'Global_Activity', ...
    'Commodity_Prices', ...
    'VIX', ...
    'Domestic_Macro', ...
    'Relative_Yields', ...
    'Other_FX', ...
    'Accounting_Error'});


fprintf('\n');
fprintf('============================================================\n');
fprintf('FINAL SVAR HISTORICAL DECOMPOSITION\n');
fprintf('============================================================\n');

disp(SVAR_Final);


%% ================================================================
% 9. FIGURE
%% ================================================================

x = ...
    1:nEpisodes;


componentColors = [ ...
    0.0000 0.4470 0.7410
    0.8500 0.3250 0.0980
    0.9290 0.6940 0.1250
    0.4940 0.1840 0.5560
    0.4660 0.6740 0.1880
    0.3010 0.7450 0.9330
    0.8000 0.0000 0.5000];


figure( ...
    'Color','w', ...
    'Position',[80 100 1400 650]);


b = bar( ...
    x, ...
    Contrib, ...
    'stacked');


for cc = 1:nComponents

    b(cc).FaceColor = ...
        componentColors(cc,:);

end


hold on;


hActual = plot( ...
    x, ...
    ActualChange, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',8);


yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');


xticks(x);

xticklabels(plotLabels);

xtickangle(18);


ylabel( ...
    'Contribution to RTWI change, log points');


title( ...
    'SVAR: What Drove Major Australian Dollar Episodes?');


grid on;
box off;


set( ...
    gca, ...
    'FontSize',11, ...
    'Layer','top');


legend( ...
    [b(:);hActual], ...
    [componentNames {'Observed change'}], ...
    'Location','eastoutside');


%% ================================================================
% 10. EXPORT FIGURE
%% ================================================================

exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '42_svar_hd_final_episodes.png'), ...
    'Resolution',300);


exportgraphics( ...
    gcf, ...
    fullfile( ...
        figDir, ...
        '42_svar_hd_final_episodes.pdf'), ...
    'ContentType','vector');


%% ================================================================
% 11. EXPORT TABLE
%% ================================================================

outputFile = ...
    fullfile( ...
        resultDir, ...
        'svar_hd_final_episodes.xlsx');


if isfile(outputFile)
    delete(outputFile);
end


writetable( ...
    SVAR_Final, ...
    outputFile, ...
    'Sheet','HD');


%% ================================================================
% 12. SAVE MATLAB RESULTS
%% ================================================================

svar_hd_final = struct();


svar_hd_final.episodeNames = ...
    episodeNames;


svar_hd_final.episodeStart = ...
    episodeStart;


svar_hd_final.episodeEnd = ...
    episodeEnd;


svar_hd_final.ActualChange = ...
    ActualChange;


svar_hd_final.Contrib = ...
    Contrib;


svar_hd_final.componentNames = ...
    componentNames;


svar_hd_final.AccountingError = ...
    AccountingError;


svar_hd_final.Table = ...
    SVAR_Final;


save( ...
    fullfile( ...
        resultDir, ...
        'svar_hd_final_episodes.mat'), ...
    'svar_hd_final');


fprintf('\nMaximum accounting error: %.3e\n', ...
    max(abs(AccountingError)));

fprintf('\nFinal SVAR HD complete.\n');